import test from 'node:test';
import assert from 'node:assert/strict';
import {TargetAllocation,allocationAvailable,TARGET_ALLOCATION_VERSION} from './allocation.js';
import {appError} from './model.js';
const detail={kind:'report',intent:'create_report',title:'Monthly revenue'};
const reply=(r,id='allocated-report')=>({version:r.version,kind:r.kind,intent:r.intent,idempotency_key:r.idempotency_key,id});
function host(fn){const calls=[];return {calls,supportsTargetAllocation:()=>true,async allocateTarget(request){calls.push(structuredClone(request));return fn?fn(request):reply(request);}};}
test('allocation is an explicit negotiated host request with exact immutable identity',async()=>{const adapter=host(),a=new TargetAllocation(adapter,detail,'key-one');assert(allocationAvailable(adapter));assert.equal(adapter.calls.length,0);assert.equal(await a.obtain(),'allocated-report');assert.deepEqual(adapter.calls,[{version:TARGET_ALLOCATION_VERSION,...detail,idempotency_key:'key-one'}]);assert.equal(await a.obtain(),'allocated-report');assert.equal(adapter.calls.length,1);assert.throws(()=>{a.request.title='changed';});a.close();assert.equal(a.request,null);assert.equal(a.id,'');await assert.rejects(a.obtain(),/busy/);});
test('copy allocation pins only the exact checked source metadata and rejects malformed locators',async()=>{const source={block:'published-chart',revision:7,expected_version:9,digest:'a'.repeat(64),output:'revenue'},adapter=host(r=>reply(r,'private-copy')),a=new TargetAllocation(adapter,{kind:'block',intent:'copy_chart',title:'Revenue',source},'copy-key');source.revision=8;await a.obtain();assert.equal(adapter.calls[0].source.revision,7);assert(a.matches({...a.request,title:'Changed display title'}));assert(!a.matches({...a.request,source:{...a.request.source,output:'hidden'}}));for(const change of [{tenant:'x'},{revision:0},{expected_version:0},{digest:'bad'},{output:'../hidden'}])assert.throws(()=>new TargetAllocation(adapter,{kind:'block',intent:'copy_chart',title:'Revenue',source:{...a.request.source,...change}},'key'));a.close();});
test('unsupported hosts do not dispatch, invent IDs or use server tools as an allocation fallback',async()=>{for(const supports of [undefined,()=>false]){let calls=0;const adapter={supportsTargetAllocation:supports,allocateTarget:async()=>{calls++;},call:()=>{throw Error('tool fallback');}},a=new TargetAllocation(adapter,detail,'key');await assert.rejects(a.obtain(),e=>e.allocationUnavailable===true);assert.equal(calls,0);assert.equal(a.id,'');assert.equal(a.unknown,false);a.close();}});
test('unknown and denied allocation retries reuse the identical key and frozen request only on explicit action',async()=>{for(const code of ['unavailable','forbidden','cancelled_or_timed_out']){let attempt=0;const adapter=host(r=>{if(!attempt++)throw appError(code,true);return reply(r);}),a=new TargetAllocation(adapter,detail,'same-key');await assert.rejects(a.obtain(),e=>e.allocationUnknown===true);assert.equal(a.unknown,true);await Promise.resolve();assert.equal(adapter.calls.length,1);assert.equal(await a.obtain(),'allocated-report');assert.deepEqual(adapter.calls[0],adapter.calls[1]);assert.equal(a.unknown,false);a.close();}});
test('reply unions and every identity coordinate fail closed without storing a target',async()=>{const changes=[{version:'other'},{kind:'block'},{intent:'create_chart'},{idempotency_key:'other'},{id:'../target'},{id:''},{token:'no'},{source:{block:'hidden'}}];for(const change of changes){const adapter=host(r=>({...reply(r),...change})),a=new TargetAllocation(adapter,detail,'key');await assert.rejects(a.obtain(),e=>e.allocationUnknown===true);assert.equal(a.id,'');assert.equal(a.unknown,true);a.close();}const adapter=host(r=>reply(r,r.source.block)),a=new TargetAllocation(adapter,{kind:'block',intent:'copy_chart',title:'Copy',source:{block:'source',revision:1,expected_version:1,digest:'a'.repeat(64),output:'output'}},'key');await assert.rejects(a.obtain());assert.equal(a.id,'');a.close();});
test('concurrent clicks dispatch once and host teardown fences the delayed reply',async()=>{let resolve;const adapter=host(r=>new Promise(done=>resolve=()=>done(reply(r)))),a=new TargetAllocation(adapter,detail,'key'),pending=a.obtain();await assert.rejects(a.obtain(),/busy/);assert.equal(adapter.calls.length,1);a.close();resolve();await assert.rejects(pending,/unavailable/);assert.equal(a.id,'');assert.equal(a.request,null);assert.equal(a.unknown,false);});
