import test from 'node:test';
import assert from 'node:assert/strict';
import {ReportApp, awaitEmbeddedParent,intrinsicReportSize} from './app.js';
import {Viewer,renderRetainedOutput} from '../report-viewer/app.js';
import {mapView,mapSaved,mapValidation,mapCatalog,mapClone} from './mapping-fixture.mjs';
import {appError, layoutWidgets} from './model.js';
class Element {
 constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.attributes={};this.listeners={};this.dataset={};this.style={setProperty(name,value){this[name]=value;}};this._text='';this.disabled=false;this.value='';}
 set textContent(value){this.children=[];this._text=String(value);}get textContent(){return this._text+this.children.map(c=>c.textContent||'').join('');}
 append(...children){this.children.push(...children);}replaceChildren(...children){this._text='';this.children=children;}
 setAttribute(name,value){this.attributes[name]=String(value);}getAttribute(name){return this.attributes[name]??null;}
 addEventListener(name,fn){this.listeners[name]=fn;}emit(name,event={}){this.listeners[name]?.({target:this,currentTarget:this,preventDefault(){},stopPropagation(){},...event});}focus(){this.focused=true;}setPointerCapture(id){this.pointerID=id;}hasPointerCapture(id){return this.pointerID===id;}releasePointerCapture(){this.pointerID=null;}
 querySelectorAll(tag){return this.children.flatMap(c=>[...(c.tagName===tag.toUpperCase()?[c]:[]),...(c.querySelectorAll?.(tag)||[])]);}
 getBoundingClientRect(){return {width:1000,height:800};}
}
function installDOM(){globalThis.document={createElement:tag=>new Element(tag),createElementNS:(_,tag)=>new Element(tag),documentElement:new Element('html')};return new Element('main');}
const caps=report=>({version:'report-authoring-v1',builder:true,consumer:true,can_create:report==='allowed-new',can_open:!!report,can_save:!!report,can_preview:!!report,can_execute:!!report});
const original=()=>({schema_version:2,metadata:[{locale:'en-US',title:'Operations'}],locale:'en-US',timezone:'UTC',widgets:[{id:'heading',kind:'text',grid:{row:0,column:0,width:12,height:1},text:{format:'plain',text:'Overview'},presentation:{}}],filters:[]});
function fixture(){const calls=[];let stored=original(),state={id:'report-a',version:1,draft_revision:1};const adapter={resize(){},async connect(){},async call(name,args){calls.push({name,args});let result;
 if(name==='reporting_authoring_capabilities_v1')result=caps(args.report);
 else if(name==='reporting_search')result={version:'reporting-view-v1',items:[{target:{kind:args.kind,id:args.kind==='report'?'report-a':'block-a',revision:2},title:'Operations'}],next:''};
 else if(name==='reporting_authoring_drafts_v1')result={items:[{id:state.id,metadata:stored.metadata,version:state.version,revision:state.draft_revision}],next:''};
 else if(name==='reporting_authoring_read_v1')result={state:{...state,id:args.report},revision:state.draft_revision,private:true,definition:stored};
 else if(name==='reporting_authoring_create_v1'||name==='reporting_authoring_save_v1'){stored=args.definition;state={id:args.id||args.report,version:state.version+1,draft_revision:state.draft_revision+1};result=state;}
 else throw new Error(name);
 return {structuredContent:{result}};}};return {adapter,calls,stored:()=>stored};}

test('controller boots through server capability hints and exact creation target',async()=>{const root=installDOM(),f=fixture(),app=new ReportApp(root,f.adapter);await app.start();assert(root.textContent.includes('Choose a published report'));assert.deepEqual(f.calls.map(c=>c.name),['reporting_authoring_capabilities_v1','reporting_search']);await app.changeMode('builder');app.newID='allowed-new';await app.createDraft();assert.equal(app.session.definition.widgets.length,0);app.addHeading();assert.equal(app.session.definition.widgets[0].kind,'text');await app.save();assert.equal(f.calls.find(c=>c.name==='reporting_authoring_create_v1').args.id,'allowed-new');assert(f.calls.some(c=>c.name==='reporting_authoring_capabilities_v1'&&c.args.report==='allowed-new'));app.close();});

test('unsaved navigation requires discard and cancellation keeps exact content',async()=>{const root=installDOM(),f=fixture(),app=new ReportApp(root,f.adapter);await app.start();await app.openDraft('report-a');app.edit(d=>{d.widgets[0].text.text='Unsaved heading';});let navigated=false;app.navigate(async()=>{navigated=true;});assert.equal(navigated,false);assert(root.textContent.includes('Discard them'));root.querySelectorAll('button').find(b=>b.textContent==='Keep editing').emit('click');assert.equal(app.pendingNavigation,null);assert.equal(app.session.definition.widgets[0].text.text,'Unsaved heading');assert.equal(navigated,false);app.close();});

test('edit re-renders save enabled and closing clears draft, callbacks and retained buffers',async()=>{const root=installDOM(),f=fixture(),app=new ReportApp(root,f.adapter);await app.start();app.mode='builder';await app.openDraft('report-a');app.render();assert.equal(root.querySelectorAll('button').find(b=>b.textContent==='Save report').disabled,true);app.edit(d=>{d.metadata[0].title='Changed';});assert.equal(root.querySelectorAll('button').find(b=>b.textContent==='Save report').disabled,false);app.widgetParameters={sensitive:'fixture'};app.close();assert.equal(app.session.definition,null);assert.equal(app.widgetParameters,null);assert.equal(app.pendingNavigation,null);assert.equal(root.textContent,'This report app is closed. Reopen it through your authorized host.');});

test('embedded entry rejects unregistered parents and pagehide removes bootstrap listener',()=>{const root=installDOM(),listeners=new Map(),parent={},win={parent,addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:name=>listeners.delete(name)};assert.throws(()=>awaitEmbeddedParent(root,['http://host.example'],win),/invalid_request/);const boundary=awaitEmbeddedParent(root,['https://host.example'],win);listeners.get('message')({source:{},origin:'https://host.example',data:{protocol:'chartworks-report-app-v1',method:'bootstrap'}});assert(root.textContent.includes('Waiting for'));listeners.get('message')({source:parent,origin:'https://wrong.example',data:{protocol:'chartworks-report-app-v1',method:'bootstrap'}});assert(root.textContent.includes('Waiting for'));listeners.get('pagehide')();assert.equal(listeners.size,0);assert(root.textContent.includes('closed'));boundary.close();});

test('fulfilled bridge response arriving after close cannot repopulate catalogs',async()=>{const root=installDOM();let resolve;const adapter={resize(){},call:()=>new Promise(r=>{resolve=r;})},app=new ReportApp(root,adapter);const read=app.loadBlocks();app.close();resolve({structuredContent:{result:{version:'reporting-view-v1',items:[{target:{kind:'block',id:'private-block',revision:1},title:'Private name'}],next:''}}});await assert.rejects(read,/unavailable/);assert.deepEqual(app.blockCatalog,[]);assert(!root.textContent.includes('Private name'));});

test('known private preview not_found requests host refresh and retry performs retained read only',async()=>{const root=installDOM(),calls=[];let denied=true;const adapter={resize(){},async call(name,args){calls.push({name,args});return denied?{isError:true,structuredContent:{error:{code:'not_found',outcome:'not_started'}}}:{structuredContent:{result:retainedStatus('known-private-preview')}};}};const app=new ReportApp(root,adapter);app.lastMutationRun='known-private-preview';app.lastMutationPrivate=true;app.recoveryOwner='report-a';app.uncertainRun=true;
 await assert.rejects(app.openRun('known-private-preview',true),e=>e.code==='not_found'&&e.needsRunAuthority===true);assert.equal(app.uncertainRun,true);denied=false;await app.openRun('known-private-preview',true);assert.deepEqual(calls.map(c=>c.name),['reporting_view','reporting_view']);assert(calls.every(c=>c.args.run==='known-private-preview'));assert.equal(app.uncertainRun,false);app.close();});

test('not_found for arbitrary or public run IDs preserves nondisclosing generic failure',async()=>{const root=installDOM(),adapter={resize(){},async call(){return {isError:true,structuredContent:{error:{code:'not_found'}}};}},app=new ReportApp(root,adapter);app.lastMutationRun='known-private-preview';app.lastMutationPrivate=true;await assert.rejects(app.openRun('arbitrary-run',true),e=>e.code==='not_found'&&e.needsRunAuthority!==true);app.lastMutationRun='public-run';app.lastMutationPrivate=false;await assert.rejects(app.openRun('public-run',true),e=>e.code==='not_found'&&e.needsRunAuthority!==true);app.close();});

function uncertainPreview(app,report='report-a') {app.recoveryOwner=report;app.lastMutationRun='preview-a';app.lastMutationPrivate=true;app.uncertainRun=true;}
test('switching reports resets recovery but same-report reload preserves uncertainty',async()=>{const root=installDOM(),f=fixture(),app=new ReportApp(root,f.adapter);await app.start();await app.openDraft('report-a');uncertainPreview(app);await app.openDraft('report-a');assert.equal(app.recoveryOwner,'report-a');assert.equal(app.lastMutationRun,'preview-a');assert.equal(app.uncertainRun,true);await assert.rejects(app.previewDraft(),/forbidden/);await app.openDraft('report-b');assert.equal(app.recoveryOwner,'report-b');assert.equal(app.lastMutationRun,null);assert.equal(app.lastMutationPrivate,false);assert.equal(app.uncertainRun,false);app.mode='builder';app.render();assert(!root.querySelectorAll('button').some(b=>b.textContent==='Inspect last retained run'));assert.equal(root.querySelectorAll('button').find(b=>b.textContent==='Private preview').disabled,false);app.close();});

test('new exact-authorized draft resets previous report recovery',async()=>{const root=installDOM(),f=fixture(),app=new ReportApp(root,f.adapter);await app.start();await app.openDraft('report-a');uncertainPreview(app);app.newID='allowed-new';await app.createDraft();assert.equal(app.recoveryOwner,'allowed-new');assert.equal(app.lastMutationRun,null);assert.equal(app.uncertainRun,false);assert.equal(app.session.state,null);app.close();});

test('late failed preview cannot attach old-report recovery to a newer report',async()=>{const root=installDOM(),f=fixture();let rejectPreview;const base=f.adapter.call.bind(f.adapter);f.adapter.call=(name,args)=>name==='reporting_authoring_preview_v1'?new Promise((resolve,reject)=>{rejectPreview=reject;}):base(name,args);const app=new ReportApp(root,f.adapter);await app.start();await app.openDraft('report-a');const preview=app.previewDraft();const rejected=assert.rejects(preview,/unavailable/);assert.equal(app.uncertainRun,true);await app.openDraft('report-b');rejectPreview(appError('unavailable',true));await rejected;assert.equal(app.recoveryOwner,'report-b');assert.equal(app.lastMutationRun,null);assert.equal(app.uncertainRun,false);app.close();});

function retainedStatus(run,state='completed',report='report-a',isPrivate=true,code='') {return {version:'reporting-view-v1',timezone:'UTC',locale:'en-US',page_bounds:{offset:0,limit:100,total:0},summary:{kind:'report',run,target:{kind:'report',id:report,revision:1},private:isPrivate,state,code,expires_at:'2099-01-01T00:00:00Z'},selection:{kind:'report',run},pages:[]};}
test('terminal read after denied private preview enables future preview while pending and foreign reads cannot clear',async()=>{
 const root=installDOM(),f=fixture(),base=f.adapter.call.bind(f.adapter);let denied=true,status='completed',target='report-a';
 f.adapter.call=async(name,args)=>{
  if(name==='reporting_authoring_preview_v1')return {structuredContent:{result:{id:'preview-a',private:true}}};
  if(name==='reporting_authoring_execute_v1')return {structuredContent:{result:{id:'preview-a',private:true,state:'completed'}}};
  if(name==='reporting_view')return denied?{isError:true,structuredContent:{error:{code:'not_found'}}}:{structuredContent:{result:retainedStatus(args.run,status,target)}};
  return base(name,args);
 };
 const app=new ReportApp(root,f.adapter);await app.start();await app.openDraft('report-a');app.mode='builder';
 await assert.rejects(app.previewDraft(),e=>e.needsRunAuthority===true);assert.equal(app.uncertainRun,true);assert.equal(app.lastMutationRun,'preview-a');
 denied=false;status='running';await app.openRun('preview-a',true);assert.equal(app.uncertainRun,true);
 status='unknown';await app.openRun('preview-a',true);assert.equal(app.uncertainRun,true);
 status='completed';await app.openRun('foreign-run',true);assert.equal(app.uncertainRun,true);
 target='report-b';await assert.rejects(app.openRun('preview-a',true),/stale_validation/);assert.equal(app.uncertainRun,true);assert.equal(app.preview,null);
 target='report-a';await app.openRun('preview-a',true);assert.equal(app.uncertainRun,false);app.closePreview();app.render();
 assert.equal(root.querySelectorAll('button').find(b=>b.textContent==='Private preview').disabled,false);
 await app.openDraft('report-a');assert.equal(app.uncertainRun,false);app.close();
});

test('successful pending retained read from preview and published-run callers remains fenced',async()=>{for(const kind of ['preview','published']){const root=installDOM(),f=fixture(),base=f.adapter.call.bind(f.adapter);f.adapter.call=async(name,args)=>{let result;if(name==='reporting_authoring_preview_v1')result={id:'pending-run',private:true};else if(name==='reporting_authoring_execute_v1')result={id:'pending-run',private:true,state:'running'};else if(name==='reporting_run')result={run:'pending-run'};else if(name==='reporting_view')result=retainedStatus('pending-run','running','report-a',kind==='preview');else return base(name,args);return {structuredContent:{result}};};const app=new ReportApp(root,f.adapter);await app.start();await app.openDraft('report-a');if(kind==='preview')await app.previewDraft();else{app.description={resource:{target:{kind:'report',id:'report-a',revision:1}},filters:[],timezone:'UTC'};await app.runPublished();}assert.equal(app.uncertainRun,true,kind);assert.equal(app.lastMutationRun,'pending-run');app.close();}});

test('terminal failed status with indeterminate query code stays fenced',()=>{const root=installDOM(),app=new ReportApp(root,{resize(){}});uncertainPreview(app);app.observeTerminalRecovery(retainedStatus('preview-a','failed','report-a',true,'query_indeterminate'),'preview-a');assert.equal(app.uncertainRun,true);app.observeTerminalRecovery(retainedStatus('preview-a','failed','report-a',true,'query_failed'),'preview-a');assert.equal(app.uncertainRun,false);app.close();});

test('nested retained viewer size requests use the entire report root and one outer size owner',()=>{const root=installDOM(),sizes=[],app=new ReportApp(root,{resize:(width,height)=>sizes.push({width,height})}),bridge=app.retainedBridge();bridge.resize(200,120);assert.deepEqual(sizes,[{width:1000,height:800}]);app.requestRootSize();bridge.resize(500,300);assert.equal(sizes.length,1,'nested and root observers do not compete with duplicate heights');root.getBoundingClientRect=()=>({width:1200,height:1400});bridge.resize(300,150);assert.deepEqual(sizes.at(-1),{width:1200,height:1400});app.close();bridge.resize(100,100);assert.equal(sizes.length,2,'closed app does not resize');});

test('layout control reflects a saved two-column canonical grid after reopen',async()=>{const root=installDOM(),f=fixture(),app=new ReportApp(root,f.adapter);await app.start();app.mode='builder';await app.openDraft('report-a');app.edit(d=>{d.widgets.push({...d.widgets[0],id:'second',presentation:{},text:{format:'plain',text:'Second heading'}});d.widgets=layoutWidgets(d.widgets,2);});await app.save();await app.openDraft('report-a');app.render();const layout=root.querySelectorAll('select').find(e=>e.getAttribute('aria-label')==='Layout');assert.equal(layout.children.find(option=>option.selected).value,'2');assert.equal(app.session.definition.widgets[1].grid.column,6);app.edit(d=>{d.widgets[1].grid.row=5;});const custom=root.querySelectorAll('select').find(e=>e.getAttribute('aria-label')==='Layout');assert.equal(custom.children.find(option=>option.selected).value,'custom');app.close();});

test('connection readiness flushes an unchanged size measured before bridge initialization',async()=>{const root=installDOM(),f=fixture(),sent=[];let finishConnect;const connected=new Promise(resolve=>{finishConnect=resolve;});f.adapter.ready=false;f.adapter.connect=async()=>{await connected;f.adapter.ready=true;};f.adapter.resize=(width,height)=>{if(f.adapter.ready)sent.push({width,height});};const app=new ReportApp(root,f.adapter);app.requestRootSize();assert.equal(app.lastSize,'1000:800');assert.deepEqual(sent,[]);const starting=app.start();finishConnect();await starting;assert.deepEqual(sent,[{width:1000,height:800}]);app.requestRootSize();assert.equal(sent.length,1);app.close();});

function canvasFixture(){
 const f=fixture(),base=f.adapter.call.bind(f.adapter);let admitted,revision,denied=false;
 f.adapter.call=async(name,args)=>{
  if(name==='reporting_authoring_preview_v1'){admitted=JSON.parse(JSON.stringify(f.stored()));revision=args.revision;return {structuredContent:{result:{id:'canvas-preview',private:true}}};}
  if(name==='reporting_authoring_execute_v1')return {structuredContent:{result:{id:args.run,private:true,state:'completed'}}};
  if(name==='reporting_view'){
   if(denied)throw appError('not_found');
   const widget=admitted.widgets.find(w=>w.id===(args.widget||admitted.widgets[0].id)),output=args.output||widget.block?.outputs[0]||'',view={version:'reporting-view-v1',summary:{kind:'report',run:args.run,target:{kind:'report',id:'report-a',revision},private:true,state:'completed',expires_at:'2099-01-01T00:00:00Z'},selection:{...args,page:'main',widget:widget.id,output},pages:[{id:'main',report:'report-a',revision,widgets:admitted.widgets.map(w=>({id:w.id,kind:w.kind,grid:w.grid,presentation:w.presentation,outputs:w.block?.outputs||[],state:'completed'}))}],outputs:output?[{id:output,enabled:true,selected:true}]:[],filters:[],locale:'en-US',timezone:'UTC',page_bounds:{offset:args.offset,limit:1,total:output?2:0,...(output&&args.offset===0?{next:1}:{})}};
   if(widget.text)view.text=widget.text;else view.output={id:output,kind:'table',state:'succeeded',retained_digest:'fixed-'+output,table:{columns:[{id:'amount',name:'Amount',type:'decimal'}],rows:[[{value:args.offset?'5.50':'9007199254740993.01',null:false}]],totals:[],warnings:[]}};
   f.calls.push({name,args});return {structuredContent:{result:view}};
  }
  return base(name,args);
 };
 return {...f,deny:()=>{denied=true;}};
}
async function savedCanvas(app){await app.start();app.mode='builder';await app.openDraft('report-a');app.edit(d=>{d.widgets.push({id:'metric',kind:'block',grid:{row:2,column:3,width:9,height:2},presentation:{title:'Revenue'},block:{block:'block-a',revision:7,outputs:['amount'],policy:'published',narrative:false}});d.filters=[{label:'Maximum',parameter:{name:'maximum',type:'integer',default:{literal:'30'}}}];});await app.save();await app.previewDraft();app.render();}

test('saved canvas reuses retained output during presentation edits and saves, while semantic edits visibly stale it',async()=>{
 const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);assert(root.textContent.includes('9007199254740993.01'));const card=root.querySelectorAll('article').find(e=>e.dataset.widget==='metric');assert.equal(card.style.gridColumn,'4 / span 9');assert.equal(card.style.gridRow,'3 / span 2');const reads=f.calls.filter(c=>c.name==='reporting_view').length,origin=app.previewDefinition;
 app.edit(d=>{d.metadata[0].title='New report title';d.widgets[0].text.text='New heading';d.widgets[1].presentation.title='New widget title';d.widgets[1].grid={row:1,column:0,width:12,height:1};});assert(root.textContent.includes('9007199254740993.01'));assert(root.textContent.includes('New heading'));assert.equal(f.calls.filter(c=>c.name==='reporting_view').length,reads);await app.save();app.render();assert(root.textContent.includes('Values from revision 2'));assert.equal(app.session.revision,3);assert.equal(app.previewDefinition,origin);assert(root.textContent.includes('9007199254740993.01'));
 app.edit(d=>{d.filters[0].parameter.default.literal='31';});assert(root.textContent.includes('Preview is stale. Save and preview'));assert(!root.textContent.includes('9007199254740993.01'));assert.equal(f.calls.filter(c=>c.name==='reporting_view').length,reads);app.edit(d=>{d.filters[0].parameter.default.literal='30';});assert(root.textContent.includes('9007199254740993.01'));app.close();
});
test('denied output page erases the whole canvas and requests exact private-run host refresh',async()=>{
 const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);f.deny();await assert.rejects(app.pageOutput('main','metric','amount',1),e=>e.code==='not_found'&&e.needsRunAuthority===true);app.render();assert(!root.textContent.includes('9007199254740993.01'));assert.equal(app.preview,null);assert.equal(app.retained.entries.size,0);app.close();
});
test('Consumer uses retained canonical grid without editor or Viewer debug selectors',async()=>{
 const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);app.mode='consumer';app.selected={target:{kind:'report',id:'report-a',revision:2},title:'Retained report'};app.render();assert(root.textContent.includes('9007199254740993.01'));assert(root.querySelectorAll('h2').some(e=>e.textContent==='Overview'));const card=root.querySelectorAll('article').find(e=>e.dataset.widget==='metric');assert.equal(card.style.gridColumn,'4 / span 9');assert.equal(card.style.gridRow,'3 / span 2');assert(!root.querySelectorAll('select').length);assert(!root.querySelectorAll('button').some(e=>e.textContent==='Save report'));app.close();
});
test('newer retained opening wins and closing during first read cannot restore stale data',async()=>{
 const root=installDOM(),waiting=new Map(),app=new ReportApp(root,{resize(){},call:(_,args)=>new Promise(resolve=>waiting.set(args.run,()=>resolve({structuredContent:{result:retainedStatus(args.run)}})))});const first=app.openRun('first'),second=app.openRun('second');waiting.get('second')();await second;waiting.get('first')();await first;assert.equal(app.preview.summary.run,'second');const pending=app.openRun('third');app.closePreview();waiting.get('third')();await pending;assert.equal(app.preview,null);assert.equal(app.retained.value,null);app.close();
});

test('Viewer and canvas share exact table, source-row, total, completeness and inert disclosure presentation',async t=>{
 const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);const v=JSON.parse(JSON.stringify(app.retained.get('main','metric','amount')));
 v.output.table.columns[0].format={fraction_digits:3,currency:'USD',unit:'revenue'};v.output.table.row_indices=[7];v.output.table.totals=[{column:'amount',value:{value:'9007199254740998.51',null:false},scope:'complete_result'}];v.output.table.completeness={status:'partial_result',reason:'max_rows'};v.output.table.warnings=['<img src=x onerror=alert(1)>'];v.output.amount_completeness=[{label:'Known amount',evidence:'reviewed_definition',query_outcome:'succeeded',rows_scope:'visible_source_rows',role:'amount',result:{policy:'reviewed-amount-completeness-v1',scope:'returned_query_rows',metric:'amount',unknown_count_metric:'unknown',status:'incomplete',rows:[{row:7,status:'incomplete',unknown_count:'9007199254740993'}]}}];
 const canvas=new Element('section'),viewerRoot=new Element('main'),pages=[];renderRetainedOutput(canvas,v,{locale:'en-US',onPage:offset=>pages.push(offset)});const viewer=new Viewer(viewerRoot,{resize(){}},{allowRun:false});t.after(()=>{viewer.close();app.close();});viewer.show(v);
 assert.equal(canvas.querySelectorAll('table')[0].textContent,viewerRoot.querySelectorAll('table')[0].textContent);for(const value of ['9,007,199,254,740,993.010 USD revenue','9,007,199,254,740,998.510 USD revenue','Total scope: complete_result','Result completeness: partial_result · max_rows','Unknown amount count (displayed rows): 9007199254740993','<img src=x onerror=alert(1)>']){assert(canvas.textContent.includes(value),value);assert(viewerRoot.textContent.includes(value),value);}assert.equal(canvas.querySelectorAll('tr')[1].dataset.sourceRow,'7');assert.equal(canvas.querySelectorAll('img').length,0);canvas.querySelectorAll('button').find(b=>b.textContent==='Next').emit('click');assert.deepEqual(pages,[1]);viewer.close();app.close();
});

test('uncaptured private runs never overlay draft defaults even at the same revision',async()=>{
 const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);const reads=f.calls.filter(c=>c.name==='reporting_view').length;app.context({locale:'es-ES',theme:'dark'});assert.equal(f.calls.filter(c=>c.name==='reporting_view').length,reads);assert(root.textContent.includes('9007199254740993.01'));assert.equal(document.documentElement.dataset.theme,'dark');
 app.closePreview();assert(!root.textContent.includes('9007199254740993.01'),'closing erases DOM values synchronously');app.lastMutationRun=null;app.lastPreviewDefinition=null;await app.openRun('reopened-private',true);app.render();assert.equal(app.session.revision,app.preview.summary.target.revision);assert.equal(app.compatiblePreview(),false);assert(root.textContent.includes('Preview is stale'));assert(!root.textContent.includes('9007199254740993.01'));app.close();
});

test('malformed matching terminal retained response cannot clear the unknown-execution fence',async()=>{
 for(const change of [v=>delete v.summary.expires_at,v=>v.timezone='not-a-timezone',v=>delete v.page_bounds]){const root=installDOM(),view=retainedStatus('preview-a');change(view);const app=new ReportApp(root,{resize(){},async call(){return {structuredContent:{result:view}};}});uncertainPreview(app);await assert.rejects(app.openRun('preview-a',true));assert.equal(app.uncertainRun,true);assert.equal(app.preview,null);assert.equal(app.retained.entries.size,0);app.close();}
});

const cardFor=(root,id)=>root.querySelectorAll('article').find(e=>e.dataset.widget===id);
const pointer=(handle,name,x=0,y=0)=>handle.emit(name,{button:0,pointerId:1,clientX:x,clientY:y});
test('pointer move previews without mutating, cancels cleanly, commits once and rejects collisions without reflow',async()=>{
 const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);app.selectWidget('metric');const original=JSON.stringify(app.session.definition),calls=f.calls.length,heading=JSON.stringify(app.session.definition.widgets[0]);let card=cardFor(root,'metric'),handle=card.querySelectorAll('button').find(e=>e.dataset.action==='move');pointer(handle,'pointerdown');pointer(handle,'pointermove',0,92);assert.equal(app.session.dirty,false);assert.equal(JSON.stringify(app.session.definition),original);assert.equal(card.style.gridRow,'4 / span 2');handle.emit('keydown',{key:'Escape'});assert.equal(app.drag,null);assert.equal(JSON.stringify(app.session.definition),original);assert.equal(card.style.gridRow,'3 / span 2');card=cardFor(root,'metric');handle=card.querySelectorAll('button').find(e=>e.dataset.action==='move');pointer(handle,'pointerdown');pointer(handle,'pointermove',0,92);pointer(handle,'pointerup',0,92);assert.equal(app.session.definition.widgets[1].grid.row,3);assert.equal(JSON.stringify(app.session.definition.widgets[0]),heading);assert(app.compatiblePreview());assert(root.textContent.includes('9007199254740993.01'));card=cardFor(root,'metric');handle=card.querySelectorAll('button').find(e=>e.dataset.action==='move');const before=JSON.stringify(app.session.definition);pointer(handle,'pointerdown');pointer(handle,'pointermove',0,-276);assert.equal(card.dataset.invalid,'true');pointer(handle,'pointerup',0,-276);assert.equal(JSON.stringify(app.session.definition),before);assert(root.textContent.includes('Your layout is unchanged'));assert.equal(f.calls.length,calls);app.close();
});
test('all eight resize handles commit atomic rectangles and preserve sibling geometry',async()=>{
 const expected={nw:{column:5,row:4,width:3,height:2},n:{column:4,row:4,width:4,height:2},ne:{column:4,row:4,width:5,height:2},e:{column:4,row:3,width:5,height:3},se:{column:4,row:3,width:5,height:4},s:{column:4,row:3,width:4,height:4},sw:{column:5,row:3,width:3,height:4},w:{column:5,row:3,width:3,height:3}};
 for(const [edge,grid] of Object.entries(expected)){const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);app.edit(d=>{d.widgets[1].grid={column:4,row:3,width:4,height:3};});app.selectWidget('metric');const before=JSON.stringify(app.session.definition),heading=JSON.stringify(app.session.definition.widgets[0]),card=cardFor(root,'metric'),handle=card.querySelectorAll('button').find(e=>e.dataset.edge===edge);assert(handle,edge);pointer(handle,'pointerdown');pointer(handle,'pointermove',84.333333,92);assert.equal(JSON.stringify(app.session.definition),before);pointer(handle,'pointerup',84.333333,92);assert.deepEqual(app.session.definition.widgets[1].grid,grid,edge);assert.equal(JSON.stringify(app.session.definition.widgets[0]),heading);app.close();}
});
test('pointercancel, capture loss and closing during drag never change or restore a definition',async()=>{for(const cancel of ['pointercancel','lostpointercapture','close']){const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);app.selectWidget('metric');const original=JSON.stringify(app.session.definition),handle=cardFor(root,'metric').querySelectorAll('button').find(e=>e.dataset.edge==='se');pointer(handle,'pointerdown');pointer(handle,'pointermove',-84.333333,92);if(cancel==='close')app.close();else handle.emit(cancel);pointer(handle,'pointerup',-84.333333,92);assert.equal(app.drag,null);if(cancel==='close'){assert.equal(app.session.definition,null);assert(root.textContent.includes('This report app is closed'));}else assert.equal(JSON.stringify(app.session.definition),original);app.close();}});
test('keyboard and numeric alternatives retain siblings, input deletion and focused-card continuation',async()=>{const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);app.selectWidget('metric');const heading=JSON.stringify(app.session.definition.widgets[0]),calls=f.calls.length;let card=cardFor(root,'metric');card.emit('keydown',{key:'ArrowDown'});await Promise.resolve();assert.equal(app.session.definition.widgets[1].grid.row,3);assert.equal(cardFor(root,'metric').focused,true);card=cardFor(root,'metric');card.emit('keydown',{key:'ArrowLeft',shiftKey:true});assert.equal(app.session.definition.widgets[1].grid.width,8);const input=root.querySelectorAll('input').find(e=>e.getAttribute('aria-label')==='Widget title');cardFor(root,'metric').emit('keydown',{key:'Delete',target:input});assert.equal(app.session.definition.widgets.length,2);app.setWidgetGrid('metric','column','2');assert.equal(app.session.definition.widgets[1].grid.column,1);app.setWidgetGrid('metric','width','13');assert.equal(app.session.definition.widgets[1].grid.width,8);assert(root.textContent.includes('Your layout is unchanged'));assert.equal(JSON.stringify(app.session.definition.widgets[0]),heading);assert.equal(f.calls.length,calls);app.close();});
test('duplicate and delete preserve exact source references without reflow or reads',async()=>{const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);const original=JSON.stringify(app.session.definition.widgets),calls=f.calls.length;app.duplicateSelected('metric');assert.equal(app.session.definition.widgets.length,3);const duplicate=app.session.definition.widgets[2];assert.notEqual(duplicate.id,'metric');assert.deepEqual(duplicate.block,app.session.definition.widgets[1].block);assert.equal(JSON.stringify(app.session.definition.widgets.slice(0,2)),original);assert.equal(app.compatiblePreview(),false);app.removeSelected(duplicate.id);assert.equal(JSON.stringify(app.session.definition.widgets),original);assert.equal(app.compatiblePreview(),true);assert.equal(f.calls.length,calls);app.close();});
test('new reports are genuine blank canvases and approved components retain meaningful independent sizes',async()=>{const root=installDOM(),f=fixture(),app=new ReportApp(root,f.adapter);await app.start();app.mode='builder';app.newID='allowed-new';await app.createDraft();assert.equal(app.session.definition.widgets.length,0);assert.equal(app.catalogCollapsed,true);assert.equal(root.querySelectorAll('button').find(b=>b.textContent==='Save report').disabled,true);app.blockDescription={resource:{target:{id:'source',revision:7}}};app.addOutput({id:'kpi',kind:'kpi'});app.addOutput({id:'trend',kind:'chart'});app.addOutput({id:'detail',kind:'table'});assert.deepEqual(app.session.definition.widgets.map(w=>[w.grid.width,w.grid.height]),[[4,3],[8,4],[12,4]]);assert.equal(app.panelTab,'components');app.close();});
test('scoped input focus and uncommitted values survive redraw without crossing selection',async()=>{const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);app.selectWidget('metric');const input=root.querySelectorAll('input').find(e=>e.getAttribute('aria-label')==='Widget title');input.value='Typing now';input.selectionStart=3;input.selectionEnd=6;document.activeElement=input;app.render();const restored=root.querySelectorAll('input').find(e=>e.getAttribute('aria-label')==='Widget title');assert.equal(restored.value,'Typing now');assert.equal(restored.focused,true);app.selectWidget('heading');assert(!root.querySelectorAll('input').some(e=>e.value==='Typing now'));app.close();});
test('direct title editing commits inert text and Escape discards without data reads',async()=>{const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);app.selectWidget('metric');const calls=f.calls.length;cardFor(root,'metric').querySelectorAll('button').find(b=>b.textContent==='Edit title').emit('click');let input=root.querySelectorAll('input').find(e=>e.getAttribute('aria-label')==='Edit component title');input.value='Cancelled title';input.emit('keydown',{key:'Escape'});assert.equal(app.session.definition.widgets[1].presentation.title,'Revenue');cardFor(root,'metric').querySelectorAll('button').find(b=>b.textContent==='Edit title').emit('click');input=root.querySelectorAll('input').find(e=>e.getAttribute('aria-label')==='Edit component title');input.value='<img src=x onerror=alert(1)>';input.emit('keydown',{key:'Enter'});assert.equal(app.session.definition.widgets[1].presentation.title,'<img src=x onerror=alert(1)>');assert.equal(root.querySelectorAll('img').length,0);assert(app.compatiblePreview());assert(root.textContent.includes('9007199254740993.01'));assert.equal(f.calls.length,calls);app.close();});

test('explicit pages upgrade preserves v2 until selected, then independent page edits save and reopen without reads',async()=>{const root=installDOM(),f=fixture(),app=new ReportApp(root,f.adapter);await app.start();app.mode='builder';await app.openDraft('report-a');app.render();assert.equal(app.session.definition.schema_version,2);assert(root.querySelectorAll('button').some(b=>b.textContent==='Enable pages'));const original=JSON.stringify(app.session.definition.widgets),before=f.calls.length;app.enablePages();assert.equal(app.session.definition.schema_version,3);assert.equal(JSON.stringify(app.activePage().widgets),original);app.addPage();assert.equal(app.activePageID,'page-1');assert.equal(app.activePage().widgets.length,0);assert.equal(root.querySelectorAll('button').find(b=>b.textContent==='Save report').disabled,false);app.addHeading();const id=app.selectedWidget;app.setWidgetGrid(id,'row','5');assert.equal(app.activePage().widgets[0].grid.row,4);assert.equal(JSON.stringify(app.session.definition.report_pages[0].widgets),original);app.switchPage('main');assert(root.querySelectorAll('article').some(c=>c.dataset.widget==='heading'));assert(!root.querySelectorAll('article').some(c=>c.dataset.widget===id));app.switchPage('page-1');assert.equal(cardFor(root,id).style.gridRow,'5 / span 1');assert.equal(f.calls.length,before);await app.save();await app.openDraft('report-a');assert.equal(app.activePageID,'page-1');assert.equal(app.activePage().widgets[0].id,id);assert.equal(app.activePage().widgets[0].grid.row,4);app.removePage();assert.equal(app.activePageID,'main');assert.equal(app.session.definition.report_pages.length,1);app.removePage();assert.equal(app.session.definition.report_pages.length,1);app.close();});
test('identical filter names remain page-local and detached controls cannot mutate a newer page',async()=>{const root=installDOM(),f=fixture(),app=new ReportApp(root,f.adapter);await app.start();app.mode='builder';await app.openDraft('report-a');app.enablePages();app.editPage(p=>{p.filters=[{label:'Period',parameter:{name:'period',type:'integer',default:{literal:'1'}}}];p.defaults=[{name:'period',value:{literal:'2'}}];});const first=root.querySelectorAll('input').find(e=>e.getAttribute('aria-label')==='Default value');assert.equal(first.value,'2');app.addPage();app.editPage(p=>{p.filters=[{label:'Other period',parameter:{name:'period',type:'integer',default:{literal:'3'}}}];p.defaults=[{name:'period',value:{literal:'4'}}];});const second=root.querySelectorAll('input').find(e=>e.getAttribute('aria-label')==='Default value');assert.equal(second.value,'4');first.value='999';first.emit('change');assert.equal(app.activePage().defaults[0].value.literal,'4');second.value='5';second.emit('change');assert.equal(app.activePage().defaults[0].value.literal,'5');assert.equal(app.session.definition.report_pages[0].defaults[0].value.literal,'2');root.querySelectorAll('button').find(b=>b.textContent==='Remove filter').emit('click');assert.deepEqual(app.activePage().filters,[]);assert.equal(app.session.definition.report_pages[0].filters.length,1);app.close();});
test('page switch cancels pointer previews and delayed metadata cannot populate another page',async()=>{const root=installDOM(),f=fixture(),app=new ReportApp(root,f.adapter);await app.start();app.mode='builder';await app.openDraft('report-a');app.enablePages();app.addPage();app.switchPage('main');app.selectWidget('heading');const handle=cardFor(root,'heading').querySelectorAll('button').find(b=>b.dataset.action==='move'),before=JSON.stringify(app.session.definition);pointer(handle,'pointerdown');pointer(handle,'pointermove',0,92);app.switchPage('page-1');pointer(handle,'pointerup',0,92);assert.equal(app.drag,null);assert.equal(JSON.stringify(app.session.definition),before);assert.equal(app.activePageID,'page-1');let resolve;f.adapter.call=()=>new Promise(done=>{resolve=done;});const loading=app.loadWidgetParameters({id:'old-widget',block:{block:'source',revision:1,outputs:['out']}});app.switchPage('main');resolve({structuredContent:{result:{resource:{target:{id:'source',revision:1}},filters:[{label:'Private old filter'}]}}});await loading;assert.equal(app.widgetParameters,null);assert(!root.textContent.includes('Private old filter'));app.close();});
test('consumer tabs use exact retained page IDs without editor controls, reads or accidental first-page substitution',async()=>{const root=installDOM(),f=fixture(),app=new ReportApp(root,f.adapter);await app.start();app.selected={target:{kind:'report',id:'report-a',revision:1},title:'Report'};const pages=[{id:'summary',title:'Summary',report:'report-a',revision:1,widgets:[{id:'first',kind:'text',grid:{row:0,column:0,width:12,height:1},presentation:{},outputs:[]}]},{id:'detail',title:'Detail',report:'report-a',revision:1,widgets:[{id:'second',kind:'text',grid:{row:4,column:6,width:6,height:2},presentation:{},outputs:[]}]}];const calls=[];f.adapter.call=async(name,args)=>{calls.push({name,args});const page=args.page||'summary',widget=args.widget||(page==='summary'?'first':'second');return {structuredContent:{result:{...retainedStatus(args.run),selection:{...args,page,widget,output:''},pages,outputs:[],text:{text:widget==='first'?'First-page retained heading':'Second-page retained heading'}}}};};await app.openRun('pages-run');app.render();assert.equal(app.consumerPageID,'summary');assert(root.textContent.includes('First-page retained heading'));assert(!root.textContent.includes('Second-page retained heading'));const count=calls.length;app.switchPage('detail',true);assert(!root.textContent.includes('First-page retained heading'));assert(root.textContent.includes('Second-page retained heading'));assert.equal(cardFor(root,'second').style.gridRow,'5 / span 2');assert(!root.querySelectorAll('button').some(b=>['Add page','Enable pages','Save report','Remove page','Move widget'].includes(b.textContent)));app.switchPage('missing',true);assert.equal(app.consumerPageID,'detail');assert.equal(calls.length,count);assert(calls.every(c=>c.name==='reporting_view'));app.close();});

async function mappingApp(){
 const root=installDOM(),f=fixture(),base=f.adapter.call.bind(f.adapter);let privateView=null,fail='',delayed=null;
 f.adapter.call=async(name,args)=>{let result;
  if(name==='chart_catalog')result=mapClone(mapCatalog);
  else if(name==='reporting_authoring_block_read_v1'){if(fail.startsWith('read:'))throw appError(fail.slice(5));result=privateView&&args.block===privateView.block.state.id?mapClone(privateView):mapView(args.block,args.revision);}
  else if(name==='reporting_authoring_block_copy_v1'||name==='reporting_authoring_block_mapping_v1'){if(fail==='save')throw appError('unavailable',true);privateView=mapSaved(args,name.includes('block_copy'));result=mapClone(privateView);}
  else if(name==='reporting_authoring_block_validate_v1'){if(fail==='validate')throw appError('unavailable',true);if(delayed)return new Promise(resolve=>{delayed.resolve=()=>resolve({structuredContent:{result:mapValidation(privateView)}});});result=mapValidation(privateView);privateView.block.state=mapClone(result.state);privateView.block.validation=mapClone(result.evidence);}
  else return base(name,args);
  f.calls.push({name,args});return {structuredContent:{result}};
 };
 const app=new ReportApp(root,f.adapter);await app.start();app.mode='builder';await app.openDraft('report-a');app.enablePages();app.blockDescription={resource:{target:{id:'source',revision:7}}};app.addOutput({id:'amount',kind:'chart',title:'Revenue'});app.selectWidget(app.selectedWidget);await app.save();app.render();return {app,root,...f,widget:()=>app.activePage().widgets.find(w=>w.block),fail:kind=>{fail=kind;},delay:()=>{delayed={};return delayed;}};
}
test('real mapping inspector stages type and fields without calls; Cancel keeps exact report references',async()=>{const f=await mappingApp(),{app,root}=f,original=JSON.stringify(app.session.definition);await app.perform(()=>app.openMapping(f.widget()));assert(root.textContent.includes('Edit chart'));const calls=f.calls.length,kind=root.querySelectorAll('select').find(e=>e.getAttribute('aria-label')==='Chart type');kind.value='line';kind.emit('change');assert.equal(app.mapping.draft.kind,'line');const category=root.querySelectorAll('select').find(e=>e.getAttribute('aria-label')==='Category / time');category.value='date';category.emit('change');const value=root.querySelectorAll('select').find(e=>e.getAttribute('aria-label')==='Value');value.value='amount';value.emit('change');assert(app.mapping.valid());assert.equal(f.calls.length,calls);assert.equal(JSON.stringify(app.session.definition),original);app.cancelMapping();assert.equal(JSON.stringify(app.session.definition),original);assert.equal(app.mapping,null);assert.equal(f.calls.length,calls);app.close();});
test('copy adopts an exact visibly unvalidated private pin, saves without execution, then validates explicitly',async()=>{const f=await mappingApp(),{app,root}=f,original=JSON.stringify(app.activePage().widgets[0]);await app.perform(()=>app.openMapping(f.widget()));app.mapping.edit(d=>d.kind='column');app.mapping.newBlock='host-authorized-chart';await app.perform(()=>app.saveMapping());assert.equal(app.mapping,null);const block=f.widget().block;assert.equal(block.block,'host-authorized-chart');assert.equal(block.policy,'private_preview');assert.equal(block.revision,1);assert.equal(block.digest,'c'.repeat(64));assert.equal(JSON.stringify(app.activePage().widgets[0]),original);assert(root.textContent.includes('Unvalidated'));assert.equal(root.querySelectorAll('button').find(b=>b.textContent==='Save report').disabled,false);assert.equal(root.querySelectorAll('button').find(b=>b.textContent==='Private preview').disabled,true);assert(!f.calls.some(c=>c.name.includes('validate')||c.name.includes('execute')||c.name==='reporting_run'));await app.save();assert.equal(f.stored().report_pages[0].widgets[1].block.block,'host-authorized-chart');assert.equal(app.session.dirty,false);assert.equal(app.privatePreviewReady(),false);await app.perform(()=>app.validateChart(f.widget()));assert.equal(f.calls.filter(c=>c.name==='reporting_authoring_block_validate_v1').length,1);assert.equal(app.privatePreviewReady(),true);assert.equal(root.querySelectorAll('button').find(b=>b.textContent==='Private preview').disabled,false);assert.equal(app.session.dirty,false);assert(!f.calls.some(c=>c.name.includes('execute')||c.name==='reporting_run'));app.close();});
test('private mapping edits pin a new revision, preserve siblings and invalidate old validation without querying',async()=>{const f=await mappingApp(),{app}=f;await app.perform(()=>app.openMapping(f.widget()));app.mapping.newBlock='private-chart';app.mapping.edit(d=>d.kind='column');await app.perform(()=>app.saveMapping());await app.save();await app.perform(()=>app.validateChart(f.widget()));assert(app.privatePreviewReady());const sibling=JSON.stringify(app.activePage().widgets[0]),calls=f.calls.length;await app.perform(()=>app.openMapping(f.widget()));assert.equal(app.mapping.copy,false);app.mapping.edit(d=>d.kind='bar');await app.perform(()=>app.saveMapping());assert.equal(f.widget().block.revision,2);assert.equal(app.privatePreviewReady(),false);assert.equal(JSON.stringify(app.activePage().widgets[0]),sibling);assert(f.calls.slice(calls).some(c=>c.name==='reporting_authoring_block_mapping_v1'));assert(!f.calls.slice(calls).some(c=>c.name.includes('validate')||c.name.includes('execute')));app.close();});
test('unknown chart save remains fenced after closing and reopening the editor',async()=>{const f=await mappingApp(),{app}=f;await app.perform(()=>app.openMapping(f.widget()));app.mapping.newBlock='uncertain-chart';app.mapping.edit(d=>d.kind='column');f.fail('save');await assert.rejects(app.saveMapping(),e=>e.unknown===true);assert(app.mapping.unknown);const original=f.widget().block.block;app.cancelMapping();const calls=f.calls.length;await app.openMapping(f.widget());assert.equal(app.mapping,null);assert.equal(f.calls.length,calls);assert.equal(f.widget().block.block,original);assert(app.message.includes('unknown outcome'));app.close();});
test('unknown validation cannot be cleared by a status read or converted into another mapping mutation',async()=>{const f=await mappingApp(),{app}=f;await app.perform(()=>app.openMapping(f.widget()));app.mapping.newBlock='private-chart';app.mapping.edit(d=>d.kind='column');await app.perform(()=>app.saveMapping());f.fail('validate');await assert.rejects(app.validateChart(f.widget()),e=>e.unknown===true);await app.checkPrivateChart(f.widget());assert.equal(app.privatePreviewReady(),false);const count=f.calls.length;await assert.rejects(app.validateChart(f.widget()),/busy/);await app.openMapping(f.widget());assert.equal(app.mapping,null);assert.equal(f.calls.length,count);app.close();});
test('closing during explicit validation fences metadata and uncertainty callbacks',async()=>{const f=await mappingApp(),{app}=f;await app.perform(()=>app.openMapping(f.widget()));app.mapping.newBlock='private-chart';app.mapping.edit(d=>d.kind='column');await app.perform(()=>app.saveMapping());const delayed=f.delay(),validating=app.validateChart(f.widget());for(let i=0;i<20&&!delayed.resolve;i++)await Promise.resolve();assert(delayed.resolve);app.close();delayed.resolve();await assert.rejects(validating,/unavailable/);assert.equal(app.privateCharts.size,0);assert.equal(app.mappingFailures.size,0);assert.equal(app.mapping,null);});

test('table selection, column order, visibility and page size stay staged with zero tool calls',async()=>{const f=await mappingApp(),{app,root}=f;await app.perform(()=>app.openMapping(f.widget()));const calls=f.calls.length,original=JSON.stringify(app.session.definition);let kind=root.querySelectorAll('select').find(e=>e.getAttribute('aria-label')==='Chart type');kind.value='table';kind.emit('change');for(const id of ['category','amount']){const add=root.querySelectorAll('select').find(e=>e.getAttribute('aria-label')==='Add Table columns');add.value=id;add.emit('change');}const visible=root.querySelectorAll('input').find(e=>e.getAttribute('aria-label')==='Show column amount');visible.checked=false;visible.emit('change');root.querySelectorAll('button').find(e=>e.textContent==='Move Table columns 1 down').emit('click');const size=root.querySelectorAll('input').find(e=>e.getAttribute('aria-label')==='Table page size');size.value='25';size.emit('change');assert.deepEqual(app.mapping.draft.bindings.columns,['amount','category']);assert.deepEqual(app.mapping.draft.table.columns,[{column:'amount',visible:false},{column:'category',visible:true}]);assert.equal(app.mapping.draft.table.page_size,25);assert(app.mapping.valid());assert.equal(f.calls.length,calls);assert.equal(JSON.stringify(app.session.definition),original);app.cancelMapping();app.close();});
test('choosing a rich binding variant remains staged while its required fields are completed',async()=>{const f=await mappingApp(),{app,root}=f;await app.perform(()=>app.openMapping(f.widget()));const calls=f.calls.length,variant=root.querySelectorAll('select').find(e=>e.getAttribute('aria-label')==='Binding variant');variant.value='multi_measure';variant.emit('change');assert.equal(app.mapping.variant,'multi_measure');assert(!app.mapping.valid());const measures=root.querySelectorAll('select').find(e=>e.getAttribute('aria-label')==='Add Measures');assert(measures);measures.value='amount';measures.emit('change');assert.deepEqual(app.mapping.draft.bindings.values,['amount']);assert(!app.mapping.draft.bindings.value);assert(app.mapping.valid());assert.equal(f.calls.length,calls);app.close();});
test('staged chart changes hide an otherwise compatible retained result and cancellation restores it',async()=>{const root=installDOM(),f=canvasFixture(),app=new ReportApp(root,f.adapter);await savedCanvas(app);assert(app.compatiblePreview());const reads=f.calls.length;app.mapping={dirty:true};app.render();assert(!root.textContent.includes('9007199254740993.01'));assert(root.textContent.includes('Preview is stale'));app.mapping=null;app.render();assert(root.textContent.includes('9007199254740993.01'));assert.equal(f.calls.length,reads);app.close();});

test('private metadata denial clears old validation hints and retained values without another source execution',async()=>{for(const code of ['forbidden','unauthenticated','not_found']){const f=await mappingApp(),{app,root}=f;await app.perform(()=>app.openMapping(f.widget()));app.mapping.newBlock='private-chart';app.mapping.edit(d=>d.kind='column');await app.perform(()=>app.saveMapping());assert(root.textContent.includes('Private chart · Unvalidated'));assert.equal(cardFor(root,f.widget().id).getAttribute('aria-label'),'Report output widget');await app.validateChart(f.widget());assert(app.privatePreviewReady());const evidence=app.privateCharts.get(app.mappingKey(f.widget().block));assert(!evidence.block.outputs);assert(!evidence.block.expected_schema);app.preview=retainedStatus('old-retained');const reads=f.calls.filter(c=>c.name==='reporting_authoring_block_validate_v1').length;f.fail('read:'+code);await assert.rejects(app.checkPrivateChart(f.widget()),e=>e.code===code);assert.equal(app.privateCharts.size,0);assert.equal(app.preview,null);assert.equal(app.retained.entries.size,0);assert.equal(app.privatePreviewReady(),false);assert.equal(f.calls.filter(c=>c.name==='reporting_authoring_block_validate_v1').length,reads);app.close();}});
test('validation hint cache keeps at most 100 lightweight exact coordinates',async()=>{const f=await mappingApp(),{app}=f;for(let i=0;i<101;i++){const view=mapView('private-'+i,1,true);view.block.validation=mapValidation(view).evidence;app.rememberPrivateChart({block:'private-'+i,revision:1,digest:view.block.digest},view);}assert.equal(app.privateCharts.size,100);assert([...app.privateCharts.values()].every(v=>!v.block.outputs&&!v.block.validation.schema));app.close();assert.equal(app.privateCharts.size,0);});

async function datasetAppFixture(){const {datasetFixture}=await import('./dataset-fixture.mjs');const root=installDOM(),f=fixture(),native=datasetFixture(),base=f.adapter.call.bind(f.adapter);f.adapter.call=async(name,args)=>['list_topics','describe_topic','reporting_authoring_dataset_v1','reporting_authoring_prepare_chart_v1','reporting_authoring_preparation_v1','reporting_authoring_preparation_control_v1','reporting_authoring_create_prepared_v1'].includes(name)?{structuredContent:{result:await native.invoke(name,args)}}:base(name,args);const app=new ReportApp(root,f.adapter);await app.start();app.mode='builder';await app.openDraft('report-a');app.enablePages();return {app,root,f,native};}
async function stageDataset(app){await app.openDataset();const s=app.datasetSession;await s.selectTopic(s.topics[0]);await s.selectDataset('orders');s.newBlock='private-chart';s.edit(d=>{d.title='Prepared revenue';d.dimensions=['region'];d.measure='revenue';});app.render();return s;}
test('dataset creation adds exact unvalidated pin on active page and report save does not query',async()=>{const {app,root,f,native}=await datasetAppFixture();app.addPage();const page=app.activePageID,original=JSON.stringify(app.session.definition.report_pages[0]);await stageDataset(app);assert.equal(root.querySelectorAll('button').find(b=>b.textContent==='Prepare chart').disabled,false);assert.equal(root.querySelectorAll('button').find(b=>b.textContent==='Save report').disabled,true);const before=native.calls.length;app.datasetSession.edit(d=>{d.kind='table';d.pageSize=7;});assert.equal(native.calls.length,before);await app.prepareDataset();await app.createDatasetChart();const widget=app.activePage().widgets.at(-1);assert.deepEqual(widget.block,{block:'private-chart',revision:1,digest:'c'.repeat(64),outputs:['chart'],policy:'private_preview',narrative:false});assert.equal(app.activePageID,page);assert.equal(JSON.stringify(app.session.definition.report_pages[0]),original);assert.equal(app.privatePreviewReady(),false);const reads=native.calls.length;await app.save();assert.equal(native.calls.length,reads);assert(f.calls.some(c=>c.name==='reporting_authoring_save_v1'));assert.equal(app.datasetSession,null);assert.equal(app.datasetCustody.size,0);app.close();});
test('dataset setup closes without source work and unknown custody survives close/reopen',async()=>{const {app,root,native}=await datasetAppFixture();await stageDataset(app);const before=native.calls.length;app.cancelDataset();assert.equal(native.calls.length,before);assert.equal(app.datasetSession,null);const s=await stageDataset(app),invoke=s.invoke;s.invoke=async(name,args)=>{const v=await invoke(name,args);if(name.includes('prepare_chart'))throw appError('unavailable',true);return v;};await assert.rejects(app.prepareDataset(),/unavailable/);const operation=s.custody.operation;app.cancelDataset();assert.equal(s.view,null);assert.equal(s.preparation,null);app.render();assert(root.querySelectorAll('button').some(b=>b.textContent==='Resume chart setup'));await app.openDataset();assert.equal(app.datasetSession,s);assert.equal(s.custody.operation,operation);await app.inspectDataset();assert.equal(s.canCreate(),true);assert.equal(native.calls.filter(c=>c.name.includes('prepare_chart')).length,1);app.close();assert.equal(app.datasetCustody.size,0);});
test('dataset page/mode navigation is blocked during staged edits and close fences late create',async()=>{const {app,native}=await datasetAppFixture();app.addPage();const page=app.activePageID;const s=await stageDataset(app);app.switchPage('main');assert.equal(app.activePageID,page);let navigated=false;app.navigate(()=>{navigated=true;});assert.equal(navigated,false);await app.prepareDataset();const {datasetCreated}=await import('./dataset-fixture.mjs');const result=datasetCreated(s.preparation);let resolve;const invoke=s.invoke;s.invoke=(name,args)=>name.includes('create_prepared')?new Promise(r=>{resolve=()=>r(result);}):invoke(name,args);const creating=app.createDatasetChart();app.close();resolve();await creating;assert.equal(app.session.definition,null);assert.equal(app.datasetSession,null);assert.equal(app.privateCharts.size,0);});
test('dataset metadata denial clears prior retained values and prevents stale field reuse',async()=>{const {app}=await datasetAppFixture();const s=await stageDataset(app);app.preview={summary:{}};s.invoke=async()=>{throw appError('forbidden');};await assert.rejects(app.datasetRead(()=>s.selectDataset('orders')),/forbidden/);assert.equal(app.preview,null);assert.equal(s.view,null);assert.equal(s.publication,null);assert.equal(s.valid(),false);app.close();});

test('intrinsic frame height converges independently of host viewport padding',()=>{const root=installDOM(),sizes=[];let viewport=900;const app=new ReportApp(root,{resize:(width,height)=>{sizes.push({width,height});viewport=height+16;}});root.getBoundingClientRect=()=>({top:0,width:1440,height:viewport});root.children.forEach((child,index)=>{child.getBoundingClientRect=()=>({bottom:index===0?52:720});});app.requestRootSize();app.requestRootSize();app.requestRootSize();assert.deepEqual(sizes,[{width:1440,height:720}]);assert.equal(viewport,736);assert.equal(intrinsicReportSize(root).height,720);app.close();});
test('shared KPI separates units, preserves every exact digit and keeps incomplete amounts visible',async()=>{const {capturedViews}=await import('./browser_fixture.mjs');const root=installDOM(),v=JSON.parse(JSON.stringify(capturedViews.kpi));v.output.amount_completeness=[{label:'Known revenue',evidence:'reviewed_definition',query_outcome:'succeeded',rows_scope:'returned_query_rows',role:'amount',result:{policy:'reviewed-amount-completeness-v1',scope:'returned_query_rows',metric:'revenue',unknown_count_metric:'unknown',status:'incomplete',rows:[{row:0,status:'incomplete',unknown_count:'2'}]}}];renderRetainedOutput(root,v,{locale:'en-US'});const p=root.querySelectorAll('p').find(e=>e.className==='kpi');assert.equal(p.textContent,'9,007,199,254,740,993.125 USD revenue');assert.equal(p.children[0].textContent,'9,007,199,254,740,993.125');assert.equal(p.children[1].textContent,' USD revenue');assert.equal(p.getAttribute('aria-label'),p.textContent);assert.equal(p.children[0].getAttribute('title'),'9007199254740993.125');assert(Number(p.style['--kpi-width'])>10);assert(root.querySelectorAll('details').some(e=>e.className==='retained-values'));assert(!root.querySelectorAll('p').some(e=>e.textContent==='geometry_approximate_labels_exact'));const disclosure=root.querySelectorAll('div').find(e=>e.className==='amount-disclosure');assert(disclosure.children.some(e=>e.textContent==='Known revenue: incomplete'));assert(disclosure.children.some(e=>e.textContent==='Unknown amount count (returned rows): 2'));assert(disclosure.querySelectorAll('details')[0].textContent.includes('Evidence: reviewed definition'));});
test('shared line axes retain complete labels outside shrinking SVG coordinates',async()=>{const {capturedViews}=await import('./browser_fixture.mjs');const root=installDOM(),v=JSON.parse(JSON.stringify(capturedViews.trend));renderRetainedOutput(root,v,{locale:'en-US'});const axis=root.querySelectorAll('div').find(e=>e.className==='chart-axis');assert.deepEqual(axis.children.map(e=>e.textContent),['2026-01-02','2026-01-03']);assert(root.querySelectorAll('details').some(e=>e.className==='rendering-details'));assert.equal(root.querySelectorAll('circle').length,2);});
