import {Viewer, boundedJSON} from '../report-viewer/app.js';
import {DraftSession, authoringTool, appError, copyData, manualDocument, layoutWidgets, unpack, titleFor, validID} from './model.js';
import {MCPReportAdapter, EmbeddedReportAdapter} from './bridge.js';

function node(tag,text,cls) { const e=document.createElement(tag);if(text!==undefined)e.textContent=String(text);if(cls)e.className=cls;return e; }
function action(label,fn,{primary=false,disabled=false}={}) { const b=node('button',label,primary?'primary':'');b.type='button';b.disabled=disabled;b.addEventListener('click',fn);return b; }
function inputField(label,value,onchange,{type='text',max=256,disabled=false}={}) { const l=node('label',label),i=node(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;i.value=value??'';i.maxLength=max;i.disabled=disabled;i.setAttribute('aria-label',label);i.addEventListener('change',()=>onchange(i.value));l.append(i);return l; }
function optionsField(label,items,value,onchange) { const l=node('label',label),select=node('select');select.setAttribute('aria-label',label);for(const item of items){const o=node('option',item.label);o.value=item.value;o.selected=item.value===value;select.append(o);}select.addEventListener('change',()=>onchange(select.value));l.append(select);return l; }
function notice(text,error=false) { const p=node('p',text,error?'notice error':'notice');p.setAttribute('role',error?'alert':'status');return p; }
function responseView(value) { return {structuredContent:{result:value}}; }
function readValue(parameter,raw) { if(parameter.type==='relative_period'){let period;try{period=JSON.parse(raw);}catch{throw appError('invalid_request');}boundedJSON(period,4096);return {period};}if(parameter.type.endsWith('_list')){let items;try{items=JSON.parse(raw);}catch{throw appError('invalid_request');}if(!Array.isArray(items)||items.some(x=>typeof x!=='string')||items.length!==parameter.list_length)throw appError('invalid_request');return {items};}return {literal:raw}; }
function valueText(value) { return value?.period?JSON.stringify(value.period):value?.items?JSON.stringify(value.items):value?.literal??''; }

export class ReportApp {
  constructor(root,adapter) {
    this.root=root;this.adapter=adapter;this.closed=false;this.epoch=0;this.mode='consumer';this.busy=false;this.message='';this.error=false;this.capabilities={};this.catalog=[];this.catalogNext='';this.drafts=[];this.draftsNext='';this.selected=null;this.description=null;this.runs=[];this.runsNext='';this.blockCatalog=[];this.blockNext='';this.blockDescription=null;this.selectedWidget='';this.showLibrary=false;this.preview=null;this.viewer=null;this.pendingNavigation=null;this.locale='en-US';this.timezone='UTC';this.newID='';this.startingNew=false;this.filterValues=new Map();this.recoveryOwner='';this.lastMutationRun=null;this.lastMutationPrivate=false;this.uncertainRun=false;
    this.session=new DraftSession((name,args)=>this.invoke(name,args));
    adapter.oncontext=c=>this.context(c);adapter.onclose=()=>this.close();adapter.onfailure=e=>this.reportError(e);adapter.onresult=result=>this.hostResult(result);
    this.observer=typeof ResizeObserver==='function'?new ResizeObserver(()=>{if(!this.closed){const box=root.getBoundingClientRect();adapter.resize(box.width,box.height);}}):null;this.observer?.observe(root);
    this.render();
  }
  resetRecovery(report='') { this.recoveryOwner=report;this.lastMutationRun=null;this.lastMutationPrivate=false;this.uncertainRun=false; }
  async invoke(name,args) { if(this.closed)throw appError('unavailable');const result=await this.adapter.call(name,args);if(this.closed)throw appError('unavailable');return unpack(result); }
  context(context) { boundedJSON(context,65536);document.documentElement.dataset.theme=context?.theme==='dark'?'dark':'light';if(typeof context?.locale==='string'){try{this.locale=Intl.getCanonicalLocales(context.locale)[0]||this.locale;}catch{}}document.documentElement.lang=this.locale; }
  async start() { try{await this.adapter.connect();if(this.closed)return;await this.refreshCapabilities();if(this.capabilities.consumer)await this.loadCatalog();else if(this.capabilities.builder){this.mode='builder';await this.loadDrafts();}else this.message='No report access is available under the current authority.';}catch(e){this.reportError(e);}this.render(); }
  async refreshCapabilities(report='') { const c=await this.invoke(authoringTool('capabilities'),{report});if(this.closed)return;this.session.setCapabilities(c);this.capabilities=c; }
  reportError(e) { if(this.closed)return;this.error=true;this.message=e?.needsRunAuthority?'The preview was created. Your host must refresh access to this exact retained run before it can be viewed. Use Inspect last retained run after access is refreshed; it will not execute again.':e?.code==='conflict'?'This draft changed elsewhere. Your edits are still here. Reload the latest draft before saving again.':e?.unknown||this.session.uncertain?'The outcome is unknown. Reload the draft or inspect retained runs before submitting another change.':`Report action unavailable: ${e?.code||'unavailable'}.`;this.render(); }
  async perform(fn) { if(this.busy||this.closed)return;this.busy=true;this.error=false;this.message='';this.render();try{await fn();}catch(e){this.reportError(e);}finally{this.busy=false;if(!this.closed)this.render();} }
  navigate(fn) { if(this.busy)return;if(this.session.dirty){this.pendingNavigation=fn;this.render();}else void this.perform(fn); }
  async changeMode(mode) { this.epoch++;this.mode=mode;this.selected=null;this.description=null;this.closePreview();this.session.definition=null;this.session.state=null;this.session.dirty=false;this.selectedWidget='';await this.refreshCapabilities();if(mode==='builder')await this.loadDrafts();else await this.loadCatalog(); }
  async loadCatalog(after='') { const epoch=this.epoch,r=await this.invoke('reporting_search',{kind:'report',query:'',locale:this.locale,after,limit:40});if(this.closed||epoch!==this.epoch)return;if(r.version!=='reporting-view-v1'||!Array.isArray(r.items))throw appError('unavailable');this.catalog=after?[...this.catalog,...r.items].slice(0,200):r.items;this.catalogNext=this.catalog.length<200?r.next:''; }
  async loadDrafts(after='') { const epoch=this.epoch,r=await this.invoke(authoringTool('drafts'),{after,limit:40});if(this.closed||epoch!==this.epoch)return;if(!Array.isArray(r.items))throw appError('unavailable');this.drafts=after?[...this.drafts,...r.items].slice(0,200):r.items;this.draftsNext=this.drafts.length<200?r.next:''; }
  async selectPublished(item) { const epoch=++this.epoch;this.closePreview();this.selected=item;this.description=null;this.runs=[];this.filterValues.clear();const [d,r,c]=await Promise.all([this.invoke('reporting_describe',{target:item.target,locale:this.locale,outputs:null}),this.invoke('reporting_runs',{kind:'report',resource:item.target.id,after:'',limit:40}),this.invoke(authoringTool('capabilities'),{report:item.target.id})]);if(this.closed||epoch!==this.epoch)return;if(d.resource?.target?.id!==item.target.id||d.resource.target.revision!==item.target.revision)throw appError('stale_validation');if(this.recoveryOwner!==item.target.id)this.resetRecovery(item.target.id);this.description=d;this.runs=r.items||[];this.runsNext=r.next||'';this.capabilities=c; }
  async openDraft(id) { ++this.epoch;this.closePreview();if(await this.session.open(id)){if(this.recoveryOwner!==id)this.resetRecovery(id);this.capabilities=this.session.capabilities;this.newID=id;this.selectedWidget=this.session.definition.widgets?.[0]?.id||'';this.showLibrary=false;this.startingNew=false;this.message=`Draft revision ${this.session.revision} loaded.`;} }
  async createDraft() { if(!validID(this.newID))throw appError('invalid_request');this.closePreview();await this.refreshCapabilities(this.newID);this.session.new('Untitled report',this.locale,this.timezone);this.startingNew=false;this.resetRecovery(this.newID);this.addHeading();this.message='This new draft is only in this window until you save.'; }
  edit(fn) { try{this.session.edit(fn);this.error=false;this.message='Unsaved changes';this.render();}catch(e){this.reportError(e);} }
  addHeading() { const id='heading-'+crypto.randomUUID().slice(0,8);this.edit(d=>{d.widgets.push({id,kind:'text',grid:{column:0,row:nextRow(d),width:12,height:1},presentation:{},text:{format:'plain',text:'Section heading'}});});this.selectedWidget=id;this.render(); }
  async loadBlocks(after='') { const r=await this.invoke('reporting_search',{kind:'block',query:'',locale:this.locale,after,limit:40});this.blockCatalog=after?[...this.blockCatalog,...r.items].slice(0,200):r.items;this.blockNext=this.blockCatalog.length<200?r.next:'';this.showLibrary=true; }
  async chooseBlock(item) { const d=await this.invoke('reporting_describe',{target:item.target,locale:this.locale,outputs:null});if(d.resource?.target?.id!==item.target.id||d.resource.target.revision!==item.target.revision)throw appError('stale_validation');this.blockDescription=d; }
  addOutput(output) { const description=this.blockDescription;if(!description||output.enabled===false||!['chart','kpi','table'].includes(output.kind))return;const id='widget-'+crypto.randomUUID().slice(0,8);this.edit(d=>{d.widgets.push({id,kind:'block',grid:{column:0,row:nextRow(d),width:12,height:1},presentation:{title:output.title||output.id},block:{block:description.resource.target.id,revision:description.resource.target.revision,outputs:[output.id],policy:'published',narrative:false}});});this.selectedWidget=id;this.showLibrary=false;this.render(); }
  addFilter(widget,parameter) { let index=1;while(this.session.definition.filters?.some(f=>f.parameter.name==='filter_'+index))index++;const name='filter_'+index;this.edit(d=>{d.filters||=[];if(d.filters.some(f=>f.parameter.name===name))throw appError('conflict');d.filters.push({parameter:{...copyData(parameter),name},label:parameter.name});const w=d.widgets.find(w=>w.id===widget.id);w.bindings||=[];if(w.bindings.some(b=>b.parameter===parameter.name))throw appError('conflict');w.bindings.push({filter:name,parameter:parameter.name});});this.render(); }
  async loadWidgetParameters(widget) { const d=await this.invoke('reporting_describe',{target:{kind:'block',id:widget.block.block,revision:widget.block.revision},locale:this.locale,outputs:widget.block.outputs});if(d.resource?.target?.id!==widget.block.block||d.resource.target.revision!==widget.block.revision)throw appError('stale_validation');this.widgetParameters={widget:widget.id,filters:d.filters||[]}; }
  async save() { if(await this.session.save(this.newID)){this.message=`Saved private draft revision ${this.session.revision}.`;await this.refreshCapabilities(this.session.state.id);await this.loadDrafts();} }
  async previewDraft() { if(this.session.dirty||!this.session.capabilities.can_preview||this.uncertainRun)throw appError('forbidden');const epoch=this.epoch,report=this.session.state.id,revision=this.session.revision;this.resetRecovery(report);this.uncertainRun=true;let result;try{result=await this.invoke(authoringTool('preview'),{report,key:crypto.randomUUID(),revision,resolution:{at:new Date().toISOString(),timezone:this.session.definition.timezone},pages:[]});if(this.closed||epoch!==this.epoch)return;if(!validID(result.id)||result.private!==true)throw appError('unavailable',true);this.lastMutationRun=result.id;this.lastMutationPrivate=true;result=await this.invoke(authoringTool('execute'),{run:result.id,resume:false});if(this.closed||epoch!==this.epoch)return;await this.openRun(result.id,true);if(!this.closed&&epoch===this.epoch&&this.recoveryOwner===report)this.uncertainRun=false;}catch(e){if(!this.closed&&epoch===this.epoch&&this.recoveryOwner===report)this.uncertainRun=!!this.lastMutationRun||e.unknown===true||['unavailable','cancelled_or_timed_out'].includes(e.code);throw e;} }
  async runPublished() { if(!this.capabilities.can_execute||!this.description||this.uncertainRun)throw appError('forbidden');const d=this.description,epoch=this.epoch,pages=new Map();for(const f of d.filters||[]){const raw=this.filterValues.get(`${f.page}:${f.parameter.name}`);if(raw===undefined)continue;if(!pages.has(f.page))pages.set(f.page,[]);pages.get(f.page).push({name:f.parameter.name,value:readValue(f.parameter,raw)});}this.resetRecovery(d.resource.target.id);this.uncertainRun=true;try{const r=await this.invoke('reporting_run',{target:d.resource.target,key:crypto.randomUUID(),arguments:[],pages:Array.from(pages,([page,filters])=>({page,filters,overrides:[]})),outputs:[],policy:'',locale:this.locale,timezone:d.timezone,narrative:false,dynamic:false,partial_failure:''});if(this.closed||epoch!==this.epoch)return;this.lastMutationRun=r.run;this.lastMutationPrivate=false;await this.openRun(r.run);if(!this.closed&&epoch===this.epoch&&this.recoveryOwner===d.resource.target.id)this.uncertainRun=false;}catch(e){if(!this.closed&&epoch===this.epoch&&this.recoveryOwner===d.resource.target.id)this.uncertainRun=!!this.lastMutationRun||e.unknown===true||['unavailable','cancelled_or_timed_out'].includes(e.code);throw e;} }
  async openRun(run,privateExpected=false) { const epoch=this.epoch;let v;try{v=await this.invoke('reporting_view',{kind:'report',run,page:'',widget:'',output:'',offset:0,limit:100});}catch(e){if(privateExpected&&run===this.lastMutationRun&&this.lastMutationPrivate&&['forbidden','unauthenticated','not_found'].includes(e.code))e.needsRunAuthority=true;throw e;}if(this.closed||epoch!==this.epoch)return;if(privateExpected&&!v.summary?.private)throw appError('unavailable');this.closePreview();this.preview=v;this.message=v.summary?.private?'Private preview. This retained result stays private.':'Viewing retained results. Opening and paging do not run queries.'; }
  closePreview() { this.viewer?.close();this.viewer=null;this.preview=null; }
  hostResult(result) { if(this.closed)return;try{const value=unpack(result);if(value.version==='reporting-view-v1'&&value.summary&&value.selection){this.closePreview();this.preview=value;this.render();}}catch{/* Opening tools may also return capabilities or a saved draft state. */} }
  render() {
    if(this.closed)return;this.viewer?.close();this.viewer=null;this.root.replaceChildren();
    const header=node('header',undefined,'app-header'),brand=node('div');brand.append(node('p','CHARTWORKS','eyebrow'),node('h1','Reports'));const tabs=node('nav',undefined,'mode-tabs');tabs.setAttribute('aria-label','Report mode');for(const [mode,label,enabled] of [['consumer','Browse',this.capabilities.consumer],['builder','Build',this.capabilities.builder]]){const b=action(label,()=>this.navigate(()=>this.changeMode(mode)),{disabled:!enabled||this.busy});b.setAttribute('aria-current',this.mode===mode?'page':'false');tabs.append(b);}header.append(brand,tabs,node('span',this.mode==='builder'?'Builder':'Consumer','mode-badge'));this.root.append(header);
    if(this.message)this.root.append(notice(this.message,this.error));if(this.busy)this.root.append(notice('Working…'));
    if(this.pendingNavigation){const prompt=node('section',undefined,'notice');prompt.append(node('p','You have unsaved edits. Discard them and continue?'),action('Keep editing',()=>{this.pendingNavigation=null;this.render();}),action('Discard and continue',()=>{const fn=this.pendingNavigation;this.pendingNavigation=null;this.session.dirty=false;void this.perform(fn);}));this.root.append(prompt);}
    const layout=node('div',undefined,'app-layout'),sidebar=node('aside',undefined,'catalog'),workspace=node('section',undefined,'workspace');layout.append(sidebar,workspace);this.root.append(layout);
    if(this.mode==='builder')this.renderBuilder(sidebar,workspace);else this.renderConsumer(sidebar,workspace);
    if(this.preview){const preview=node('section',undefined,'retained-preview');preview.append(action('Close retained view',()=>{this.closePreview();this.render();}));const target=node('div');preview.append(target);workspace.append(preview);const bridge={call:(name,args)=>{if(name==='reporting_run'&&(!this.capabilities.can_execute||args.dynamic||args.narrative))throw appError('forbidden');return this.adapter.call(name,args);},resize:(w,h)=>this.adapter.resize(w,h)};this.viewer=new Viewer(target,bridge,{allowRun:!!this.capabilities.can_execute,allowGenerated:false});this.viewer.context({locale:this.locale,theme:document.documentElement.dataset.theme});this.viewer.accept(responseView(this.preview));}
  }
  renderConsumer(sidebar,workspace) {
    sidebar.append(node('h2','Published reports'),node('p','Available under your current access.','metadata'),action('Refresh catalog',()=>void this.perform(()=>this.loadCatalog()),{disabled:this.busy||!this.capabilities.consumer}));for(const item of this.catalog){const b=action(item.title||item.target.id,()=>void this.perform(()=>this.selectPublished(item)),{disabled:this.busy});b.className='catalog-item';b.setAttribute('aria-pressed',String(this.selected?.target.id===item.target.id));sidebar.append(b);}if(this.catalogNext)sidebar.append(action('More reports',()=>void this.perform(()=>this.loadCatalog(this.catalogNext)),{disabled:this.busy}));if(!this.catalog.length)sidebar.append(node('p','No published reports are visible.','empty'));
    if(!this.selected){workspace.append(node('p','Your governed reports, in one place','eyebrow'),node('h2','Choose a published report'),node('p','Open retained results or explicitly run an approved report with business filters.','muted'));return;}
    workspace.append(node('h2',this.selected.title||this.selected.target.id),node('p',this.selected.description||'','muted'),node('p',`Published revision ${this.selected.target.revision}`,'badge'));
    if(this.description){const form=node('fieldset');form.append(node('legend','Run this report'),node('p','A run may query approved sources and creates a new retained result.','metadata'));for(const f of this.description.filters||[]){const key=`${f.page}:${f.parameter.name}`,field=inputField(f.label||f.parameter.name,this.filterValues.get(key)??'',v=>{if(v==='')this.filterValues.delete(key);else this.filterValues.set(key,v);},{type:f.parameter.type==='date'?'date':'text',max:4096,disabled:!this.capabilities.can_execute||this.busy});field.append(node('span',`Blank uses the published default · ${f.parameter.type}`,'metadata'));form.append(field);}form.append(action('Run with these filters',()=>void this.perform(()=>this.runPublished()),{primary:true,disabled:this.busy||!this.capabilities.can_execute||this.uncertainRun||this.description.dynamic}));if(this.description.dynamic)form.append(node('p','This report contains dynamic widgets outside this manual app slice.','metadata'));if(!this.capabilities.can_execute)form.append(node('p','Current access permits retained reads only.','metadata'));workspace.append(form);}
    const history=node('section',undefined,'run-history');history.append(node('h3','Retained runs'),action('Refresh runs',()=>void this.perform(async()=>{const r=await this.invoke('reporting_runs',{kind:'report',resource:this.selected.target.id,after:'',limit:40});this.runs=r.items;this.runsNext=r.next;this.message=this.uncertainRun?'Review existing runs before starting a new operation.':'';}),{disabled:this.busy}));for(const run of this.runs){const row=node('div',undefined,'run-row');row.append(node('div',`${run.state} · ${run.created_at}${run.private?' · Private preview':''}`),action('Open retained run',()=>void this.perform(()=>this.openRun(run.run)),{disabled:this.busy||run.state==='expired'}));history.append(row);}if(!this.runs.length)history.append(node('p','No retained runs are visible.','metadata'));if(this.runsNext)history.append(action('More runs',()=>void this.perform(async()=>{const r=await this.invoke('reporting_runs',{kind:'report',resource:this.selected.target.id,after:this.runsNext,limit:40});this.runs=[...this.runs,...r.items].slice(0,200);this.runsNext=this.runs.length<200?r.next:'';}),{disabled:this.busy}));workspace.append(history);
  }
  renderBuilder(sidebar,workspace) {
    sidebar.append(node('h2','Private drafts'),action('New report',()=>this.navigate(async()=>{this.startingNew=true;this.session.definition=null;this.newID='';}),{primary:true,disabled:!this.capabilities.builder||this.busy}),action('Refresh drafts',()=>void this.perform(()=>this.loadDrafts()),{disabled:this.busy}));for(const draft of this.drafts){const b=action(titleFor(draft.metadata,this.locale),()=>this.navigate(()=>this.openDraft(draft.id)),{disabled:this.busy});b.className='catalog-item';b.setAttribute('aria-pressed',String(this.session.state?.id===draft.id));sidebar.append(b);}if(this.draftsNext)sidebar.append(action('More drafts',()=>void this.perform(()=>this.loadDrafts(this.draftsNext)),{disabled:this.busy}));if(!this.drafts.length)sidebar.append(node('p','No editable drafts are visible.','empty'));
    if(this.startingNew){workspace.append(node('h2','Create a private report'),node('p','Enter a report ID that your host has authorized for creation. Access is checked before the editor opens.','metadata'),inputField('Proposed report ID',this.newID,value=>{this.newID=value;},{max:128,disabled:this.busy}),action('Check access and start',()=>void this.perform(()=>this.createDraft()),{primary:true,disabled:this.busy}));return;}const d=this.session.definition;if(!d){workspace.append(node('p','MANUAL COMPOSITION','eyebrow'),node('h2','Build from approved outputs'),node('p','Start a private report, add headings and published KPIs, charts or tables, then save and preview.','muted'));return;}
    const editable=manualDocument(d)&&(this.session.state?this.session.capabilities.can_save:this.session.capabilities.can_create)&&!this.busy&&!this.session.conflict&&!this.session.uncertain;
    const fields=node('div',undefined,'document-fields');fields.append(inputField('Report title',titleFor(d.metadata,d.locale),value=>{this.edit(next=>{if(!value.trim())throw appError('invalid_request');next.metadata.find(m=>m.locale===next.locale).title=value;});},{disabled:!editable}));if(!this.session.state)fields.append(inputField('Report ID',this.newID,value=>{this.newID=value;},{max:128,disabled:!editable}));workspace.append(fields);
    workspace.append(node('p',this.session.state?`Private draft · revision ${this.session.revision} · version ${this.session.state.version}`:'Not saved yet','metadata'));
    const controls=node('div',undefined,'toolbar');controls.append(action('Save report',()=>void this.perform(()=>this.save()),{primary:true,disabled:!editable||!this.session.dirty}),action('Reload latest',()=>this.navigate(()=>this.openDraft(this.session.state?.id||this.newID)),{disabled:this.busy||!this.session.state&&!((this.session.conflict||this.session.uncertain)&&validID(this.newID))}),action('Private preview',()=>void this.perform(()=>this.previewDraft()),{disabled:this.busy||this.session.dirty||!this.session.state||!this.session.capabilities.can_preview||this.uncertainRun}));workspace.append(controls);if(this.lastMutationRun&&this.recoveryOwner===this.session.state?.id)workspace.append(action('Inspect last retained run',()=>void this.perform(()=>this.openRun(this.lastMutationRun,this.lastMutationPrivate)),{disabled:this.busy}));
    if(!manualDocument(d)){workspace.append(notice('This draft uses widgets outside the manual editing slice. It is available for inspection; editing here is disabled.'));return;}
    const editor=node('fieldset',undefined,'editor-controls');editor.disabled=!editable;const toolbar=node('div',undefined,'toolbar');toolbar.append(action('Add heading',()=>this.addHeading()),action('Add published output',()=>void this.perform(()=>this.loadBlocks())),optionsField('Layout',[{value:'1',label:'Single column'},{value:'2',label:'Two columns'},{value:'3',label:'Three columns'}],'1',value=>{this.edit(next=>{next.widgets=layoutWidgets(next.widgets,Number(value));});this.render();}));editor.append(toolbar);
    if(this.showLibrary)this.renderLibrary(editor);
    const canvas=node('section',undefined,'composition-canvas');canvas.setAttribute('aria-label','Report composition');for(const widget of [...d.widgets].sort((a,b)=>a.grid.row-b.grid.row||a.grid.column-b.grid.column)){const card=node('article',undefined,`widget-card width-${widget.grid.width}`);card.dataset.widget=widget.id;card.setAttribute('aria-label',widget.kind==='text'?'Heading widget':'Published output widget');const select=action(widget.kind==='text'?(widget.text?.text||'Empty heading'):(widget.presentation?.title||widget.block?.block||widget.id),()=>{this.selectedWidget=widget.id;this.widgetParameters=null;this.render();});select.className='widget-select';select.setAttribute('aria-pressed',String(this.selectedWidget===widget.id));card.append(node('p',widget.kind==='text'?'HEADING':'PUBLISHED OUTPUT','eyebrow'),select);if(widget.block)card.append(node('p',`${widget.block.block} · revision ${widget.block.revision} · ${widget.block.outputs.join(', ')}`,'metadata'));card.append(node('p',`Row ${widget.grid.row+1} · column ${widget.grid.column+1} · width ${widget.grid.width}/12`,'metadata'));canvas.append(card);}if(!d.widgets.length)canvas.append(node('p','Add a heading or an approved output to get started.','empty'));editor.append(canvas);
    const selected=d.widgets.find(w=>w.id===this.selectedWidget);if(selected)this.renderInspector(editor,selected);
    this.renderFilters(editor,d);workspace.append(editor);
  }
  renderLibrary(parent) { const library=node('section',undefined,'output-library');library.append(node('h3','Approved published outputs'),action('Close library',()=>{this.showLibrary=false;this.render();}));for(const item of this.blockCatalog)library.append(action(item.title||item.target.id,()=>void this.perform(()=>this.chooseBlock(item))));if(this.blockNext)library.append(action('More blocks',()=>void this.perform(()=>this.loadBlocks(this.blockNext))));if(this.blockDescription){library.append(node('h4',this.blockDescription.resource.title));for(const output of this.blockDescription.outputs||[])if(output.enabled!==false&&['kpi','chart','table'].includes(output.kind))library.append(action(`Add ${output.kind}: ${output.title||output.id}`,()=>this.addOutput(output)));library.append(node('p','The approved mapping is preserved. Chart outputs include any published trend mapping.','metadata'));}parent.append(library); }
  renderInspector(parent,widget) { const panel=node('section',undefined,'inspector');panel.append(node('h3','Selected widget'));if(widget.kind==='text')panel.append(inputField('Heading text',widget.text.text,value=>{this.edit(d=>{d.widgets.find(w=>w.id===widget.id).text={format:'plain',text:value};});},{type:'textarea',max:32768}));else panel.append(inputField('Widget title',widget.presentation?.title||'',value=>{this.edit(d=>{d.widgets.find(w=>w.id===widget.id).presentation.title=value;});}));
    panel.append(action('Save selected content',()=>void this.perform(async()=>{if(await this.session.saveWidget(widget.id)){this.message=`Saved selected widget in draft revision ${this.session.revision}.`;await this.loadDrafts();}}),{disabled:!this.session.canSaveWidget(widget.id)}),node('p','Selected-content save changes only this widget’s text or presentation. Layout and filter changes use Save report.','metadata'));
    const move=direction=>{this.edit(d=>{const i=d.widgets.findIndex(w=>w.id===widget.id),j=i+direction;if(j<0||j>=d.widgets.length)return;[d.widgets[i],d.widgets[j]]=[d.widgets[j],d.widgets[i]];d.widgets=layoutWidgets(d.widgets,1);});this.render();};panel.append(action('Move up',()=>move(-1),{disabled:this.session.definition.widgets[0]?.id===widget.id}),action('Move down',()=>move(1),{disabled:this.session.definition.widgets.at(-1)?.id===widget.id}),action('Remove widget',()=>{this.edit(d=>{d.widgets=d.widgets.filter(w=>w.id!==widget.id);});this.selectedWidget='';this.render();}));
    if(widget.block){panel.append(action('Choose business filter',()=>void this.perform(()=>this.loadWidgetParameters(widget))));if(this.widgetParameters?.widget===widget.id)for(const f of this.widgetParameters.filters)panel.append(action(`Add filter: ${f.label||f.parameter.name}`,()=>this.addFilter(widget,f.parameter),{disabled:widget.bindings?.some(b=>b.parameter===f.parameter.name)}));}parent.append(panel);
  }
  renderFilters(parent,definition) { const section=node('section',undefined,'filter-editor');section.append(node('h3','Business filters'),node('p','Filter declarations and bindings use the approved block parameter types. Filters do not grant data access.','metadata'));for(const filter of definition.filters||[]){const name=filter.parameter.name,card=node('div',undefined,'filter-card');card.append(inputField('Filter label',filter.label,value=>{this.edit(d=>{d.filters.find(f=>f.parameter.name===name).label=value;});}),node('p',`${name} · ${filter.parameter.type}`,'metadata'),inputField('Default value',valueText(filter.parameter.default),value=>{this.edit(d=>{const p=d.filters.find(f=>f.parameter.name===name).parameter;if(value==='')delete p.default;else p.default=readValue(p,value);});},{max:4096}),action('Remove filter',()=>{this.edit(d=>{d.filters=d.filters.filter(f=>f.parameter.name!==name);d.defaults=d.defaults?.filter(a=>a.name!==name);for(const w of d.widgets)w.bindings=w.bindings?.filter(b=>b.filter!==name);});this.render();}));section.append(card);}parent.append(section); }
  close() { if(this.closed)return;this.closed=true;this.epoch++;this.closePreview();this.session.close();this.observer?.disconnect();this.catalog=[];this.drafts=[];this.description=null;this.runs=[];this.blockCatalog=[];this.blockDescription=null;this.widgetParameters=null;this.pendingNavigation=null;this.selected=null;this.resetRecovery();this.filterValues.clear();this.root.replaceChildren(notice('This report app is closed. Reopen it through your authorized host.')); }
}
function nextRow(definition) { return definition.widgets.reduce((max,w)=>Math.max(max,w.grid.row+w.grid.height),0); }
export function mountReportApp(root,adapter) { const app=new ReportApp(root,adapter);void app.start();return app; }
export function mountEmbeddedReportApp(root,registration) { return mountReportApp(root,new EmbeddedReportAdapter(registration)); }
// This entrypoint is selected by the separately registered embedded resource.
// The public origin registration is routing configuration, never a user grant.
export function awaitEmbeddedParent(root,parents,win=window) {
  if(!Array.isArray(parents)||!parents.length||parents.length>16||parents.some(origin=>{try{const u=new URL(origin);return u.protocol!=='https:'||u.origin!==origin||u.username||u.password;}catch{return true;}}))throw appError('invalid_request');
  const allowed=new Set(parents);let closed=false,timer;
  const cleanup=()=>{win.removeEventListener('message',receive);win.removeEventListener('pagehide',close);clearTimeout(timer);};
  const close=()=>{if(closed)return;closed=true;cleanup();root.replaceChildren(notice('This report app is closed. Reopen it through your authorized host.'));};
  const receive=event=>{if(closed||event.source!==win.parent||!allowed.has(event.origin))return;try{const m=boundedJSON(event.data,4096);if(m?.protocol!=='chartworks-report-app-v1'||m.method!=='bootstrap'||Object.keys(m).some(k=>!['protocol','method','frame','generation','params'].includes(k))||!m.params||Object.keys(m.params).some(k=>k!=='challenge'))return;const adapter=new EmbeddedReportAdapter({win,origin:event.origin,frame:m.frame,generation:m.generation,challenge:m.params.challenge});closed=true;cleanup();mountReportApp(root,adapter);}catch{/* Invalid bootstrap does not select a host or broaden authority. */}};
  root.replaceChildren(notice('Waiting for the registered embedded host…'));
  win.addEventListener('message',receive);win.addEventListener('pagehide',close);timer=setTimeout(close,65000);
  return {close};
}
const appRoot=typeof document==='undefined'?null:document.getElementById('report-app');
if(appRoot){if(window.parent===window)appRoot.replaceChildren(notice('Open this report app through an authorized host.'));else if(typeof REPORT_APP_EMBEDDED_PARENTS!=='undefined')awaitEmbeddedParent(appRoot,REPORT_APP_EMBEDDED_PARENTS);else mountReportApp(appRoot,new MCPReportAdapter());}
