import test from 'node:test';
import assert from 'node:assert/strict';
import {MCPReportAdapter,EmbeddedReportAdapter} from './bridge.js';
function harness() { const sent=[],listeners=new Map(),parent={postMessage:(message,origin)=>sent.push({message,origin})},win={parent,addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:(name,fn)=>{if(listeners.get(name)===fn)listeners.delete(name);}};return {sent,listeners,parent,win,receive:(message,origin='https://host.example',source=parent)=>listeners.get('message')?.({data:message,origin,source})}; }
async function connected() {const h=harness(),bridge=new MCPReportAdapter(h.win),pending=bridge.connect();h.receive({jsonrpc:'2.0',id:h.sent[0].message.id,result:{protocolVersion:'2026-01-26',hostCapabilities:{serverTools:{}},hostContext:{}}});await pending;return {...h,bridge};}

test('MCP initialization pins only the exact parent and valid origin',async()=>{const h=harness(),b=new MCPReportAdapter(h.win),p=b.connect();const response={jsonrpc:'2.0',id:1,result:{protocolVersion:'2026-01-26',hostCapabilities:{serverTools:{}}}};h.receive(response,'https://host.example',{});assert.equal(b.ready,false);h.receive(response,'null');assert.equal(b.ready,false);h.receive(response);await p;assert.equal(b.origin,'https://host.example');assert.equal(h.sent[1].origin,'https://host.example');b.close();});

test('calls use tools/call only and foreign origin/frame replies cannot settle them',async()=>{const h=await connected(),p=h.bridge.call('reporting_search',{kind:'report'});const m=h.sent.at(-1).message;assert.equal(m.method,'tools/call');assert.equal(m.params.name,'reporting_search');h.receive({jsonrpc:'2.0',id:m.id,result:{value:'bad'}},'https://wrong.example');assert.equal(h.bridge.pending.size,1);h.receive({jsonrpc:'2.0',id:m.id,result:{value:'bad'}},'https://host.example',{});assert.equal(h.bridge.pending.size,1);h.receive({jsonrpc:'2.0',id:m.id,result:{value:'good'}});assert.deepEqual(await p,{value:'good'});await assert.rejects(h.bridge.call('arbitrary_execute',{}),/forbidden/);h.bridge.close();});

test('pending requests are capped and teardown fences every late reply',async()=>{const h=await connected(),promises=Array.from({length:16},()=>h.bridge.call('reporting_view',{}));const handled=promises.map(p=>p.catch(e=>e.code));await assert.rejects(h.bridge.call('reporting_view',{}),/busy/);h.receive({jsonrpc:'2.0',id:99,method:'ui/resource-teardown'});assert.equal(h.bridge.closed,true);assert.equal(h.bridge.pending.size,0);assert((await Promise.all(handled)).every(c=>c==='unavailable'));h.receive({jsonrpc:'2.0',id:2,result:{}});assert.equal(h.bridge.ready,false);});

test('pagehide closes the transport and unknown methods never invoke tools',async()=>{const h=await connected();h.receive({jsonrpc:'2.0',id:100,method:'unknown'});assert.equal(h.sent.at(-1).message.error.code,-32601);h.listeners.get('pagehide')();assert.equal(h.bridge.closed,true);assert.equal(h.listeners.size,0);});

test('embedded boundary requires exact public registration and one-use challenge',async()=>{const h=harness();assert.throws(()=>new EmbeddedReportAdapter({win:h.win,origin:'*',frame:'f',generation:1,challenge:'a'.repeat(16)}),/invalid_request/);const b=new EmbeddedReportAdapter({win:h.win,origin:'https://host.example',frame:'frame-a',generation:7,challenge:'a'.repeat(16)}),p=b.connect();const m=h.sent[0].message;assert.equal(h.sent[0].origin,'https://host.example');const reply={protocol:'chartworks-report-app-v1',frame:'frame-a',generation:7,id:m.id,result:{challenge:'a'.repeat(16),tools:true}};h.receive({...reply,frame:'frame-b'});h.receive({...reply,generation:6});assert.equal(b.pending.size,1);h.receive(reply);await p;assert.equal(b.challenge,null);assert.equal(b.ready,true);const call=b.call('reporting_runs',{});const handled=call.catch(e=>e.code);assert.equal(h.sent.at(-1).message.generation,7);h.receive({protocol:'chartworks-report-app-v1',frame:'frame-a',generation:7,method:'close'});assert.equal(await handled,'unavailable');assert.equal(b.closed,true);});

test('wrong embedded challenge closes rather than accepting authority hints',async()=>{const h=harness(),b=new EmbeddedReportAdapter({win:h.win,origin:'https://host.example',frame:'frame-a',generation:1,challenge:'a'.repeat(16)}),p=b.connect();h.receive({protocol:'chartworks-report-app-v1',frame:'frame-a',generation:1,id:1,result:{challenge:'b'.repeat(16),tools:true}});await assert.rejects(p,/forbidden/);assert.equal(b.closed,true);});
