// Actual compiled resource + deterministic host/provider fixture in Chromium.
// The fixture does not issue credentials or establish live host admission.
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {createServer} from 'node:http';
import {spawn} from 'node:child_process';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {cleanupBrowserFixture} from './browser_cleanup.mjs';
const [htmlPath,screenshotPath,mode="mcp"]=process.argv.slice(2);
assert(["mcp","embedded"].includes(mode),"explicit transport mode required");
assert(htmlPath,'provide actual Go-compiled resource HTML');
const html=await readFile(htmlPath,'utf8');
const host=`<!doctype html><meta charset="utf-8"><title>Report app browser fixture</title><style>body{margin:0}iframe{border:0;width:100%;height:1500px}</style><iframe id="app" title="Chartworks report app" src="/resource"></iframe><script>
const embedded=${mode==='embedded'};const frame=document.getElementById('app');window.calls=[];window.lastResizeAt=0;window.resizeCount=0;window.saveDelay=0;window.rejectSave=false;window.denyPrivate=false;window.consumerOnly=false;window.privateRuns=new Set();window.waiting=[];
const clone=v=>JSON.parse(JSON.stringify(v));const wrap=v=>({structuredContent:{result:clone(v)}});const failure=code=>({isError:true,structuredContent:{error:{code,outcome:'not_started'}}});
window.state={id:'report-a',kind:'report',version:4,draft_revision:3,published_revision:2};
window.definition={schema_version:2,metadata:[{locale:'en-US',title:'Weekly operations'}],locale:'en-US',timezone:'UTC',partial_failure:'fail_closed',widgets:[{id:'intro',kind:'text',grid:{column:0,row:0,width:12,height:1},presentation:{},text:{format:'plain',text:'Weekly overview'}}],filters:[]};
const target={kind:'report',id:'report-a',revision:2};
const filter={page:'main',label:'Maximum rows',parameter:{name:'maximum',type:'integer',required:false,default:{literal:'10'},min:'1',max:'100'}};
window.makeView=run=>({version:'reporting-view-v1',summary:{kind:'report',run,target,private:privateRuns.has(run),state:'completed',created_at:'2026-10-03T12:00:00Z',expires_at:'2099-01-01T00:00:00Z'},selection:{kind:'report',run,page:'main',widget:'metric',output:'detail',offset:0,limit:100},locale:'en-US',timezone:'UTC',pages:[{id:'main',title:'Main',report:'report-a',revision:2,widgets:[{id:'metric',kind:'block',state:'completed',grid:{row:0,column:0,width:12,height:1},presentation:{},outputs:['detail']}]}],outputs:[{id:'detail',kind:'table',title:'Exact amount',enabled:true,selected:true}],filters:[filter],output:{id:'detail',kind:'table',state:'succeeded',retained_digest:'fixture',table:{columns:[{id:'amount',name:'Amount',type:'decimal'}],rows:[[{value:'9007199254740993.01',null:false}]],totals:[],warnings:[]}},page_bounds:{offset:0,limit:100,total:1},redacted:false});
const caps=report=>({version:'report-authoring-v1',consumer:true,builder:!consumerOnly,can_create:!consumerOnly&&['new-report','report-a'].includes(report),can_open:!consumerOnly&&!!report,can_save:!consumerOnly&&!!report,can_preview:!consumerOnly&&!!report,can_execute:!consumerOnly&&!!report});
window.dispatch=(name,a)=>{
 if(name==='reporting_authoring_capabilities_v1')return wrap(caps(a.report));
 if(name==='reporting_search')return wrap({version:'reporting-view-v1',items:a.kind==='block'?[{target:{kind:'block',id:'approved-block',revision:7},title:'Approved business metrics',description:'',locale:'en-US'}]:[{target,title:'Weekly operations',description:'Reviewed KPIs and operational detail',locale:'en-US'}],next:''});
 if(name==='reporting_authoring_drafts_v1')return wrap({items:[{id:state.id,version:state.version,revision:state.draft_revision,metadata:definition.metadata,updated_at:'2026-10-03T12:00:00Z'}],next:''});
 if(name==='reporting_authoring_read_v1')return wrap({state,revision:state.draft_revision,private:true,digest:'synthetic',definition});
 if(name==='reporting_authoring_create_v1'){state={id:a.id,kind:'report',version:1,draft_revision:1,published_revision:0};definition=clone(a.definition);return wrap(state);}
 if(name==='reporting_authoring_save_v1'){if(rejectSave){rejectSave=false;return failure('conflict');}if(a.expected_version!==state.version)return failure('conflict');state={...state,version:state.version+1,draft_revision:state.draft_revision+1};definition=clone(a.definition);return wrap(state);}
 if(name==='reporting_describe')return wrap(a.target.kind==='block'?{version:'reporting-view-v1',resource:{target:a.target,title:'Approved business metrics'},outputs:[{id:'amount',kind:'kpi',title:'Amount',enabled:true,selected:true},{id:'trend',kind:'chart',title:'Amount trend',enabled:true,selected:true},{id:'detail',kind:'table',title:'<img src=x onerror=alert(1)>',enabled:true,selected:true},{id:'story',kind:'narrative',title:'Narrative',enabled:true,selected:true}],filters:[filter],dynamic:false,timezone:'UTC'}:{version:'reporting-view-v1',resource:{target,title:'Weekly operations'},outputs:[],filters:[filter],pages:[],dynamic:false,timezone:'UTC'});
 if(name==='reporting_runs')return wrap({version:'reporting-view-v1',items:[{kind:'report',run:'retained-one',target,state:'completed',private:false,created_at:'2026-10-03T12:00:00Z',expires_at:'2099-01-01T00:00:00Z'}],next:''});
 if(name==='reporting_run')return wrap({version:'reporting-view-v1',kind:'report',run:'new-run',state:'completed',code:'',target});
 if(name==='reporting_authoring_preview_v1'){privateRuns.add('private-one');return wrap({id:'private-one',kind:'report',document:a.report,revision:a.revision,private:true,state:'admitted',pages:[]});}
 if(name==='reporting_authoring_execute_v1')return wrap({id:a.run,kind:'report',document:state.id,revision:state.draft_revision,private:true,state:'completed',pages:[]});
 if(name==='reporting_view'){if(denyPrivate&&privateRuns.has(a.run))return failure('not_found');return wrap(makeView(a.run));}
 return failure('forbidden');
};
frame.addEventListener('load',()=>{if(embedded)frame.contentWindow.postMessage({protocol:'chartworks-report-app-v1',method:'bootstrap',frame:'fixture-frame',generation:1,params:{challenge:'fixture-challenge-0001'}},location.origin);});
window.addEventListener('message',event=>{if(event.source!==frame.contentWindow||event.origin!==location.origin)return;const m=event.data;if(embedded?m?.protocol!=='chartworks-report-app-v1':m?.jsonrpc!=='2.0')return;const send=result=>frame.contentWindow.postMessage(embedded?{protocol:'chartworks-report-app-v1',frame:'fixture-frame',generation:1,id:m.id,result}:{jsonrpc:'2.0',id:m.id,result},location.origin);if(m.method==='initialize'&&embedded){send({challenge:'fixture-challenge-0001',tools:true,context:{theme:'light',locale:'en-US'}});return;}if(m.method==='ui/initialize'&&!embedded){send({protocolVersion:'2026-01-26',hostCapabilities:{serverTools:{}},hostContext:{theme:'light',locale:'en-US'}});return;}if(m.method==='ui/notifications/size-changed'){window.lastResizeAt=performance.now();window.resizeCount++;frame.style.height=Math.min(2416,Math.max(500,Math.ceil(m.params.height)+16))+'px';return;}if(m.method==='tools/call'){calls.push(clone(m.params));const result=dispatch(m.params.name,m.params.arguments);setTimeout(()=>send(result),m.params.name==='reporting_authoring_save_v1'?saveDelay:5);}});
window.closeApp=()=>frame.contentWindow.postMessage(embedded?{protocol:'chartworks-report-app-v1',frame:'fixture-frame',generation:1,method:'close'}:{jsonrpc:'2.0',id:900,method:'ui/resource-teardown'},location.origin);
</script>`;
const requests=[];const server=createServer((req,res)=>{requests.push(req.url);if(req.url==='/'){res.writeHead(200,{'Content-Type':'text/html'});res.end(host);}else if(req.url==='/resource'){res.writeHead(200,{'Content-Type':'text/html','Cache-Control':'no-store'});res.end(html);}else{res.writeHead(404);res.end();}});server.listen(0,'127.0.0.1');await once(server,'listening');
if(process.env.CHARTWORKS_COMPONENT_SERVE_ONLY==='1'){console.log('http://127.0.0.1:'+server.address().port);await new Promise(()=>{});}
const directory=await mkdtemp(join(tmpdir(),'chartworks-app-browser-')),errors=[],pending=new Map();let seq=0,socket;
const browser=spawn(process.env.CHARTWORKS_CHROME_BIN||'chromium',['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-background-networking','--disable-component-update','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+directory,'about:blank'],{stdio:['ignore','ignore','pipe']});let browserStderr='';browser.stderr.on('data',data=>{if(browserStderr.length<16384)browserStderr+=data.toString();});const browserClosed=new Promise(resolve=>browser.once('close',resolve));let browserError;browser.on('error',e=>browserError=e);
const pause=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,message){const end=Date.now()+15000;while(Date.now()<end){if(browserError)throw browserError;if(browser.exitCode!==null||browser.signalCode!==null)throw new Error('Chromium exited: '+browserStderr);if(await fn())return;await pause(25);}throw new Error(message);}
function rpc(method,params={}){const id=++seq;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error('CDP timeout: '+method));},10000);pending.set(id,{resolve,reject,timer});socket.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const r=await rpc('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result?.value;}
const doc="document.getElementById('app').contentDocument",body=`${doc}.getElementById('report-app')`;
async function click(label){await evaluate(`(()=>{const b=Array.from(${body}.querySelectorAll('button')).find(b=>b.textContent===${JSON.stringify(label)}&&!b.disabled);if(!b)throw new Error('Missing enabled button '+${JSON.stringify(label)});b.click();})()`);}
async function fill(label,value){await evaluate(`(()=>{const i=Array.from(${body}.querySelectorAll('input,textarea')).find(i=>i.getAttribute('aria-label')===${JSON.stringify(label)});if(!i)throw new Error('Missing field');i.value=${JSON.stringify(value)};i.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
async function textHas(text){await until(()=>evaluate(`${body}?.textContent.includes(${JSON.stringify(text)})`),'missing text: '+text);}
async function ready(){await until(()=>evaluate(`${body}&&!Array.from(${body}.querySelectorAll('[role=status]')).some(p=>p.textContent==='Working…')`),'operation did not settle');}
async function checkRetainedFitsFrame(){
 const visible=`(()=>{const frame=document.getElementById('app'),cell=Array.from(frame.contentDocument.querySelectorAll('.retained-preview td')).find(e=>e.textContent==='9007199254740993.01');if(!cell||!window.resizeCount||performance.now()-window.lastResizeAt<100)return false;const bounds=cell.getBoundingClientRect(),root=frame.contentDocument.getElementById('report-app').getBoundingClientRect();return bounds.width>0&&bounds.height>0&&bounds.top>=0&&bounds.bottom<=frame.clientHeight&&bounds.left>=0&&bounds.right<=frame.clientWidth&&root.bottom<=frame.clientHeight+1;})()`;
 await until(()=>evaluate(visible),'retained exact amount is clipped after host resize settles');
 await check(visible,'retained exact amount is inside full-app iframe bounds after settled resize');
}
async function captureProof(path){const metrics=await rpc('Page.getLayoutMetrics'),size=metrics.cssContentSize||metrics.contentSize;const proof=await rpc('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,fromSurface:true,clip:{x:0,y:0,width:Math.min(1600,Math.ceil(size.width)),height:Math.min(6000,Math.ceil(size.height)),scale:1}});await writeFile(path,Buffer.from(proof.data,'base64'));}
let checks=0,runError;async function check(expression,message){assert.equal(await evaluate(expression),true,message);checks++;}
try{
 let port;await until(async()=>{try{port=Number((await readFile(join(directory,'DevToolsActivePort'),'utf8')).split('\n')[0]);return port>0;}catch{return false;}},'Chromium not ready');
 const target=await(await fetch(`http://127.0.0.1:${port}/json/new?about:blank`,{method:'PUT'})).json();socket=new WebSocket(target.webSocketDebuggerUrl);await once(socket,'open');socket.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);if(!p)return;clearTimeout(p.timer);pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);}else if(m.method==='Fetch.requestPaused'){const u=new URL(m.params.request.url);requests.push(u.pathname);const content=u.pathname==='/resource'?html:u.pathname==='/'?host:'';void rpc('Fetch.fulfillRequest',{requestId:m.params.requestId,responseCode:content?200:404,responseHeaders:[{name:'Content-Type',value:'text/html'}],body:Buffer.from(content).toString('base64')});}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);});
 await rpc('Runtime.enable');await rpc('Page.enable');await rpc('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await rpc('Page.addScriptToEvaluateOnNewDocument',{source:`window.storageTouches=0;for(const n of ['localStorage','sessionStorage','indexedDB']){Object.defineProperty(window,n,{get(){window.storageTouches++;throw new Error('unexpected browser storage');}});}`});
 if(mode==='embedded')await rpc('Fetch.enable',{patterns:[{urlPattern:'https://report-host.example/*'}]});
 await rpc('Page.navigate',{url:mode==='embedded'?'https://report-host.example/':`http://127.0.0.1:${server.address().port}`});await textHas('Weekly operations');await ready();await click('Weekly operations');await textHas('Retained runs');await ready();
 await click('Open retained run');await textHas('9007199254740993.01');await ready();await check("calls.every(c=>!['reporting_run','reporting_authoring_execute_v1'].includes(c.name))",'catalog and retained read make zero execution calls');
 await click('Close retained view');await fill('Maximum rows','25');await click('Run with these filters');await textHas('9007199254740993.01');await ready();await check("calls.find(c=>c.name==='reporting_run').arguments.pages[0].filters[0].value.literal==='25'",'explicit consumer filter run');
 await click('Build');await textHas('Private drafts');await ready();await click('Weekly operations');await textHas('Draft revision 3 loaded.');await ready();
 await fill('Report title','Edited weekly operations');await click('Browse');await textHas('You have unsaved edits.');await click('Keep editing');await check(`${body}.querySelector('input[aria-label="Report title"]').value==='Edited weekly operations'`,'cancel navigation preserves edits');
 await click('Add published output');await textHas('Approved business metrics');await ready();await click('Approved business metrics');await textHas('Add kpi: Amount');await ready();await check(`!${body}.textContent.includes('Add narrative:')`,'narrative outputs absent from manual slice');await click('Add table: <img src=x onerror=alert(1)>');await check(`${body}.querySelector('img')===null`,'untrusted output title remains inert text');await fill('Widget title','Revenue detail');
 await click('Choose business filter');await textHas('Add filter: Maximum rows');await ready();await click('Add filter: Maximum rows');await fill('Filter label','Rows shown');await fill('Default value','30');await evaluate(`(()=>{const s=${body}.querySelector('select[aria-label="Layout"]');s.value='2';s.dispatchEvent(new Event('change',{bubbles:true}));})()`);
 await click('Save report');await textHas('Saved private draft revision 4.');await ready();await check("calls.filter(c=>c.name==='reporting_authoring_save_v1').length===1&&calls.find(c=>c.name==='reporting_authoring_save_v1').arguments.expected_version===4",'one explicit report CAS save');await check("definition.filters[0].label==='Rows shown'&&definition.filters[0].parameter.default.literal==='30'&&definition.widgets[1].bindings[0].parameter==='maximum'",'typed filter and exact binding saved');await check("definition.widgets[1].block.revision===7&&definition.widgets[1].block.outputs[0]==='detail'",'published output pin preserved');await check(`${body}.querySelector('select[aria-label="Layout"]').value==='2'`,'layout selector reflects saved two-column canonical grid');await click('Reload latest');await textHas('Draft revision 4 loaded.');await ready();await check(`${body}.querySelector('select[aria-label="Layout"]').value==='2'`,'reopening saved two-column report preserves layout selector');
 await evaluate('denyPrivate=true');await click('Private preview');await textHas('Your host must refresh access');await ready();await check("calls.filter(c=>c.name==='reporting_authoring_preview_v1').length===1&&calls.filter(c=>c.name==='reporting_authoring_execute_v1').length===1",'private admission executes only once');await evaluate('denyPrivate=false');await click('Inspect last retained run');await textHas('Private preview. This retained result stays private.');await ready();await check("calls.filter(c=>c.name==='reporting_authoring_execute_v1').length===1",'authority refresh retry reads without another execution');await click('Close retained view');await check(`Array.from(${body}.querySelectorAll('button')).some(b=>b.textContent==='Private preview'&&!b.disabled)`,'terminal private read releases only the resolved execution fence');
 await fill('Report title','Unsaved conflict title');await evaluate('rejectSave=true');await click('Save report');await textHas('This draft changed elsewhere.');await ready();await check(`${body}.querySelector('input[aria-label="Report title"]').value==='Unsaved conflict title'`,'conflict preserves local buffer');await click('Reload latest');await textHas('You have unsaved edits.');await click('Discard and continue');await textHas('Draft revision 4 loaded.');await ready();await check(`${body}.querySelector('input[aria-label="Report title"]').value==='Edited weekly operations'`,'reload restores authoritative latest');
 await fill('Report title','Weekly operations');await evaluate('saveDelay=300');await evaluate(`(()=>{const b=Array.from(${body}.querySelectorAll('button')).find(b=>b.textContent==='Save report');b.click();b.click();Array.from(${body}.querySelectorAll('button')).find(b=>b.textContent==='Browse').click();})()`);await textHas('Saved private draft revision 5.');await ready();await check("calls.filter(c=>c.name==='reporting_authoring_save_v1').length===3",'double save emits one mutation and pending navigation stays fenced');await check(`${body}.textContent.includes('Private drafts')`,'pending save cannot navigate away');
 if(screenshotPath)await captureProof(screenshotPath);
 await click('New report');await textHas('Proposed report ID');await fill('Proposed report ID','new-report');await click('Check access and start');await textHas('This new draft is only in this window');await ready();await click('Save report');await textHas('Saved private draft revision 1.');await ready();await check("calls.filter(c=>c.name==='reporting_authoring_create_v1').length===1&&calls.find(c=>c.name==='reporting_authoring_create_v1').arguments.id==='new-report'",'new report checks exact proposed target and saves once');
 await fill('Report title','Delayed close');await evaluate('saveDelay=400');await click('Save report');await evaluate('closeApp()');await textHas('This report app is closed.');await pause(500);await check(`${body}.textContent==='This report app is closed. Reopen it through your authorized host.'`,'close fences delayed save result and clears private content');
 await evaluate('consumerOnly=true;document.getElementById("app").src="/resource"');await textHas('Weekly operations');await ready();await check(`Array.from(${body}.querySelectorAll('button')).find(b=>b.textContent==='Build').disabled`,'consumer cannot enter builder');await click('Weekly operations');await textHas('Current access permits retained reads only.');await ready();await click('Open retained run');await textHas('9007199254740993.01');await ready();await check(`!${body}.querySelector('.retained-preview fieldset')`,'shared retained renderer respects read-only mode');await check(`document.getElementById('app').contentWindow.storageTouches===0`,'resource uses no browser storage');await checkRetainedFitsFrame();
 if(screenshotPath)await captureProof(screenshotPath.replace(/\.png$/,'.consumer.png'));
 assert.deepEqual(errors,[],'no browser exceptions');assert(requests.every(path=>['/','/resource','/favicon.ico'].includes(path)),'no remote or injected asset requests');
}catch(error){runError=error;if(socket&&screenshotPath){try{await captureProof(screenshotPath.replace(/\.png$/,'.failure.png'));}catch{}}console.error(JSON.stringify({mode,checks,browserErrors:errors,browserStderr},null,2));throw error;}finally{
 try{
  await cleanupBrowserFixture({browser,closed:browserClosed,directory,
   requestClose:()=>socket?.readyState===WebSocket.OPEN?rpc('Browser.close'):undefined,
   closeTransport:()=>{for(const p of pending.values()){clearTimeout(p.timer);p.reject(new Error('test closed'));}pending.clear();socket?.close();},
   closeServer:()=>new Promise((resolve,reject)=>server.close(error=>error?reject(error):resolve())),removeProfile:rm});
 }catch(cleanupError){if(runError)throw new AggregateError([runError,cleanupError],'Browser assertions and fixture cleanup failed');throw cleanupError;}
}
console.log(JSON.stringify({mode,checks,requests,passed:true}));
