import test from 'node:test';
import assert from 'node:assert/strict';
import {inclusiveFilterRange,displayFilterRange,selectionFilterValue,FilterValueDraft,FilterOptionLookup} from './filters.js';
const key=n=>`option:1791095400:${String(n).padStart(32,'0')}`,digest='a'.repeat(64),target={report:{policy:'private_preview',report:'report',revision:1,digest,page:'main',filter:'region'}};
const reply=(operation,extra={})=>({operation,input_digest:digest,status:'completed',values_available:true,new_operation_allowed:true,source_revision:1,options:[{value:'North',label:'North'}],complete:true,...extra});
test('civil dates are inclusive in controls, half-open on wire, stable across DST and leap day',()=>{for(const [a,b,end] of [['2024-02-29','2024-02-29','2024-03-01'],['2026-03-08','2026-03-08','2026-03-09'],['0001-01-01','0001-01-01','0001-01-02']]){const v=inclusiveFilterRange(a,b);assert.deepEqual(v,{date_range:{start:a,end_exclusive:end}});assert.deepEqual(displayFilterRange(v),{start:a,end:b});}for(const pair of [['2023-02-29','2023-03-01'],['2026-01-02','2026-01-01'],['9999-12-31','9999-12-31'],['0000-01-01','0001-01-01'],['1900-01-01','2026-01-01']])assert.throws(()=>inclusiveFilterRange(...pair));});
test('set values are exact and distinct, including empty string; source null is never a choice',()=>{assert.deepEqual(selectionFilterValue(['','x\' OR true --'],true),{items:['','x\' OR true --']});assert.deepEqual(selectionFilterValue([''],false),{literal:''});for(const items of [[],['x','x'],[null],Array.from({length:17},(_,i)=>String(i))])assert.throws(()=>selectionFilterValue(items,true));});
test('staging Cancel and Done cannot mutate saved defaults',()=>{const saved={items:['North']},d=new FilterValueDraft(saved);d.select(['South'],true);assert.deepEqual(saved,{items:['North']});assert.deepEqual(d.cancel(),saved);d.select(['West'],true);const result=d.commit();result.items.push('East');assert.deepEqual(d.value,{items:['West']});assert.deepEqual(saved,{items:['North']});});
test('explicit search only; no query on construction or response inspection',async()=>{let calls=[];const s=new FilterOptionLookup(async(name,args)=>{calls.push({name,args});return reply(args.operation);},target,{operation:()=>key(1)});assert.equal(calls.length,0);await s.search('North');assert.equal(calls.length,1);assert.equal(s.values[0].value,'North');assert.equal(s.canSearch(),true);assert.deepEqual(calls[0].args.target,target);});
test('unknown lookup requires status before a fresh explicit search and never auto-retries',async()=>{let calls=[],n=0;const s=new FilterOptionLookup(async(name,args)=>{calls.push(name);if(name.endsWith('report_options_v1'))throw Error('lost');return reply(args.operation,{values_available:false,options:[],complete:false,code:'result_not_retained'});},target,{operation:()=>key(++n)});await assert.rejects(s.search('North'));assert.equal(s.canSearch(),false);await assert.rejects(s.search('South'));assert.equal(calls.length,1);await s.inspect();assert.equal(calls.length,2);assert.equal(s.canSearch(),true);assert.equal(s.values.length,0);assert.equal(s.result.code,'result_not_retained');});
test('in-flight duplicate click, cancel status, and close discard late values',async()=>{let resolve,calls=0;const s=new FilterOptionLookup(()=>{calls++;return new Promise(r=>resolve=r);},target,{operation:()=>key(1)});const pending=s.search();await assert.rejects(s.search());assert.equal(calls,1);s.close();resolve(reply(key(1)));assert.equal(await pending,false);assert.deepEqual(s.values,[]);assert.equal(s.request,null);});
test('wrong operation or contradictory empty result fails closed and keeps unresolved fence',async()=>{for(const result of [reply(key(2)),reply(key(1),{values_available:false}),reply(key(1),{complete:false}),reply(key(1),{options:[{value:null,label:'null'}]})]){const s=new FilterOptionLookup(async()=>result,target,{operation:()=>key(1)});await assert.rejects(s.search());assert.equal(s.canSearch(),false);assert.deepEqual(s.values,[]);}});
test('pagination binds cursor to same search and creates a new explicit operation',async()=>{let n=0,calls=[];const s=new FilterOptionLookup(async(name,args)=>{calls.push(args);return reply(args.operation,{complete:false,next:'opaque-cursor'});},target,{operation:()=>key(++n)});await s.search('North');await assert.rejects(s.search('South','opaque-cursor'));assert.equal(calls.length,1);await s.search('North','opaque-cursor');assert.equal(calls.length,2);assert.notEqual(calls[0].operation,calls[1].operation);});
import {filterInputState,filterInputValue} from './filter-controls.js';
test('typed control stage keeps blank category distinct from using a saved default',()=>{const saved={literal:''},stage=filterInputState({type:'dimension_value'},saved);assert.deepEqual(stage.items,['']);assert.deepEqual(filterInputValue(stage),saved);stage.items=[];assert.throws(()=>filterInputValue(stage));assert.deepEqual(saved,{literal:''});});
test('date control only produces a value on explicit conversion and leaves saved default unchanged',()=>{const saved={date_range:{start:'2026-03-08',end_exclusive:'2026-03-09'}},stage=filterInputState({type:'date_range'},saved);stage.end='2026-03-10';assert.deepEqual(saved.date_range,{start:'2026-03-08',end_exclusive:'2026-03-09'});assert.deepEqual(filterInputValue(stage),{date_range:{start:'2026-03-08',end_exclusive:'2026-03-11'}});});
import {renderFilterInput} from './filter-controls.js';
class FilterTestNode{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.value='';this.disabled=false;}append(...nodes){for(const n of nodes){n.parent=this;this.children.push(n);}}setAttribute(){}addEventListener(name,fn){this.listeners[name]=fn;}replaceWith(n){const at=this.parent.children.indexOf(this);n.parent=this.parent;this.parent.children[at]=n;}querySelectorAll(tag){return this.children.flatMap(child=>[...(child.tagName===tag.toUpperCase()?[child]:[]),...child.querySelectorAll(tag)]);}focus(){document.activeElement=this;}get firstChild(){return this.children[0];}}
function filterDOM(){globalThis.document={createElement:tag=>new FilterTestNode(tag)};return new FilterTestNode('main');}
const filterFind=(root,predicate)=>[root,...root.children.flatMap(x=>filterFind(x,()=>true))].filter(predicate);
test('rendered date Done commits only on click while Cancel keeps the saved value',()=>{const root=filterDOM(),saved={date_range:{start:'2026-03-08',end_exclusive:'2026-03-09'}},state=filterInputState({type:'date_range'},saved);let result,cancelled=0;renderFilterInput(root,state,{onDone:v=>result=v,onCancel:()=>cancelled++});const inputs=filterFind(root,n=>n.tagName==='INPUT');inputs[1].value='2026-03-10';inputs[1].listeners.input();assert.equal(result,undefined);filterFind(root,n=>n.textContent==='Cancel')[0].listeners.click();assert.equal(cancelled,1);assert.equal(result,undefined);filterFind(root,n=>n.textContent==='Done')[0].listeners.click();assert.deepEqual(result,{date_range:{start:'2026-03-08',end_exclusive:'2026-03-11'}});assert.equal(saved.date_range.end_exclusive,'2026-03-09');});
test('rendered option search is explicit, empty text visible, choice changes do not query or commit',()=>{const root=filterDOM(),state=filterInputState({type:'dimension_set'},{items:['North']}),calls=[];let committed;const lookup={canSearch:()=>true,pending:false,request:{search:''},result:{values_available:true,complete:true},values:[{value:'',label:''},{value:'North',label:'North'}]};renderFilterInput(root,state,{lookup,onSearch:(...args)=>calls.push(args),onDone:v=>committed=v});const input=filterFind(root,n=>n.type==='search')[0];input.value='South';input.listeners.input();assert.deepEqual(calls,[]);filterFind(root,n=>n.textContent==='Search options')[0].listeners.click();assert.deepEqual(calls,[['South','']]);assert.equal(filterFind(root,n=>n.textContent==='Empty text').length,1);const empty=filterFind(root,n=>n.type==='checkbox')[0];empty.checked=true;empty.listeners.change();assert.equal(document.activeElement.type,'checkbox');assert.equal(document.activeElement.value,'');assert.equal(committed,undefined);assert.equal(calls.length,1);filterFind(root,n=>n.textContent==='Done')[0].listeners.click();assert.deepEqual(committed,{items:['North','']});});
test('oversized option response is refused before values enter UI custody',async()=>{const options=Array.from({length:199},(_,i)=>({value:String(i)+'x'.repeat(2048),label:'x'.repeat(2048)}));const s=new FilterOptionLookup(async()=>reply(key(1),{options}),target,{operation:()=>key(1)});await assert.rejects(s.search(),/limit_exceeded/);assert.equal(s.values.length,0);assert.equal(s.canSearch(),false);});
