import test from 'node:test';
import assert from 'node:assert/strict';
import {MappingSession,mappingDraft,validateMappingDraft,bindingCandidates,checkMappingView,validationArguments,validatePrivateMapping,hasFreshMappingEvidence} from './mapping.js';
import {mapView,mapSaved,mapValidation,mapCatalog,mapFields,mapClone} from './mapping-fixture.mjs';
import {appError} from './model.js';
const callsFor=()=>{const calls=[];return {calls,invoke:async(name,args)=>{calls.push({name,args});if(name==='chart_catalog')return mapClone(mapCatalog);if(name.endsWith('block_read_v1'))return mapView(args.block,args.revision,args.block==='private');if(name.endsWith('block_copy_v1'))return mapSaved(args);if(name.endsWith('block_mapping_v1'))return mapSaved(args,false);throw new Error(name);}};};
test('exact metadata and catalog open is read-only; staged changes cancel without a mutation',async()=>{const f=callsFor(),s=new MappingSession(f.invoke);await s.open('source',7,'amount');assert.equal(s.dirty,false);s.edit(d=>{d.kind='column';});assert(s.valid());assert(s.dirty);assert.deepEqual(f.calls.map(c=>c.name),['reporting_authoring_block_read_v1','chart_catalog']);s.close();assert.equal(s.draft,null);assert.equal(f.calls.length,2);});
test('copy saves only closed mapping under source CAS and keeps selected output metadata server-owned',async()=>{const f=callsFor(),s=new MappingSession(f.invoke);await s.open('source',7,'amount');s.edit(d=>d.kind='column');s.newBlock='authorized-copy';const saved=await s.save(),call=f.calls.at(-1);assert.equal(call.name,'reporting_authoring_block_copy_v1');assert.equal(call.args.block,'source');assert.equal(call.args.new_block,'authorized-copy');assert.equal(call.args.expected_version,8);assert.equal(call.args.revision,7);assert.equal(call.args.digest,'a'.repeat(64));assert.equal(call.args.output,'amount');for(const forbidden of ['columns','rows','sql','version','amount_completeness'])assert(!Object.hasOwn(call.args.mapping,forbidden));assert.equal(saved.block.private,true);assert.equal(saved.data_validation,'not_performed');assert.equal(saved.block.validation,undefined);assert.equal(saved.block.outputs[1].id,'other');assert.equal(f.calls.length,3);});
test('only the current private draft maps in place and subsequent mapping invalidates prior evidence',async()=>{const f=callsFor(),s=new MappingSession(f.invoke);await s.open('private',7,'amount',false);s.edit(d=>d.kind='column');const saved=await s.save();assert.equal(f.calls.at(-1).name,'reporting_authoring_block_mapping_v1');assert(!Object.hasOwn(f.calls.at(-1).args,'new_block'));assert.equal(saved.block.revision,8);assert.equal(saved.block.validation,undefined);});
test('invalid copy target, injected payload and duplicate or incompatible fields cause no mutation',async()=>{const f=callsFor(),s=new MappingSession(f.invoke);await s.open('source',7,'amount');s.edit(d=>d.kind='column');await assert.rejects(s.save());s.newBlock='source';await assert.rejects(s.save());s.newBlock='copy';s.edit(d=>d.sql='SELECT secret');await assert.rejects(s.save());assert.equal(f.calls.length,2);for(const edit of [d=>d.bindings.value='category',d=>d.bindings.value='hidden',d=>d.bindings.value=d.bindings.category,d=>d.order=[{column:'hidden',direction:'asc'}],d=>d.options.formatter='javascript']){const draft=mappingDraft(mapView().block.outputs[0].mapping);edit(draft);assert.throws(()=>validateMappingDraft(draft,mapFields,mapCatalog));}});
test('all fourteen kinds use real closed slots and temporal/numeric field compatibility',()=>{for(const item of mapCatalog.kinds){const d={kind:item.kind,bindings:{},order:[],options:{title:'',legend:{visible:true,position:'bottom'},label_max_runes:80}};for(const slot of item.required_slots)d.bindings[slot]=slot==='columns'?['category','amount']:slot==='category'?(['line','area'].includes(item.kind)?'date':'category'):slot==='value'?'amount':slot==='series'?'series':slot==='x'?(item.kind==='heatmap'?'category':'x'):slot==='y'?(item.kind==='heatmap'?'series':'y'):'';validateMappingDraft(d,mapFields,mapCatalog);}assert.deepEqual(bindingCandidates(mapFields,'line','category').map(c=>c.id),['date']);assert(!bindingCandidates(mapFields,'kpi','value').some(c=>c.id==='category'));});
test('KPI and table controls preserve exact reviewed semantics and enforce staged display constraints',()=>{const k={kind:'kpi',bindings:{value:'amount',comparison:'comparison',target:'target'},order:[],options:{title:'',legend:{visible:false,position:'bottom'},label_max_runes:80},kpi:{value_row:'last',comparison_mode:'comparison_column',show_delta:true,show_percent_delta:true,show_target_difference:true,sparkline:false,thresholds:[]}};validateMappingDraft(k,mapFields,mapCatalog);const t={kind:'table',bindings:{columns:['category','amount']},order:[{column:'amount',direction:'desc'}],options:k.options,table:{columns:[{column:'category',visible:false},{column:'amount',visible:true}],page_size:25,show_totals:true}};validateMappingDraft(t,mapFields,mapCatalog);for(const change of [v=>v.table.page_size=0,v=>v.table.columns.reverse(),v=>v.table.columns.forEach(c=>c.visible=false)]){const bad=mapClone(t);change(bad);assert.throws(()=>validateMappingDraft(bad,mapFields,mapCatalog));}assert.equal(mapFields.find(c=>c.id==='amount').aggregation,'sum');});
test('unknown or malformed mutation responses fence all retries and read inspection cannot clear them',async()=>{for(const failure of ['unknown','wrong-target','wrong-revision','wrong-digest']){const f=callsFor(),s=new MappingSession(async(name,args)=>{if(name.endsWith('block_copy_v1')){if(failure==='unknown')throw appError('unavailable',true);const v=mapSaved(args);if(failure==='wrong-target')v.block.state.id='foreign';if(failure==='wrong-revision')v.block.revision++;if(failure==='wrong-digest')v.block.digest='bad';return v;}return f.invoke(name,args);});await s.open('source',7,'amount');s.newBlock='copy';s.edit(d=>d.kind='column');await assert.rejects(s.save());assert.equal(s.unknown,true);await assert.rejects(s.save(),/busy/);await s.inspect();assert.equal(s.unknown,true);}});
test('close fences delayed read and copy responses without restoring private metadata',async()=>{for(const phase of ['read','save']){const f=callsFor();let finish;const s=new MappingSession((name,args)=>(phase==='read'&&name.endsWith('block_read_v1')||phase==='save'&&name.endsWith('block_copy_v1'))?new Promise(r=>finish=()=>r(phase==='read'?mapView():mapSaved(args))):f.invoke(name,args));let work;if(phase==='read')work=s.open('source',7,'amount');else{await s.open('source',7,'amount');s.newBlock='copy';s.edit(d=>d.kind='column');work=s.save();}s.close();finish();await work;assert.equal(s.view,null);assert.equal(s.draft,null);}});
test('metadata identity, selected output and digest are checked before fields become editable',()=>{for(const mutate of [v=>v.block.state.id='foreign',v=>v.block.revision++,v=>v.block.digest='bad',v=>v.block.outputs[0].editable=false,v=>v.output_columns[0].columns.push(v.output_columns[0].columns[0])]){const v=mapView();mutate(v);assert.throws(()=>checkMappingView(v,'source',7,'amount'));}});
test('explicit validation receives exact block pins and page-local arguments, never rows or SQL',async()=>{const view=mapView('private',7,true),widget={block:{block:'private',revision:7,digest:view.block.digest,outputs:['amount']},bindings:[{filter:'period',parameter:'maximum'}]},page={filters:[{parameter:{name:'period',default:{literal:'2'}}}],defaults:[{name:'period',value:{literal:'3'}}]},calls=[];assert.deepEqual(validationArguments(view,widget,page),[{name:'maximum',value:{literal:'2'}}]);const result=await validatePrivateMapping(async(name,args)=>{calls.push({name,args});return mapValidation(view);},view,widget,page,{at:'2026-10-03T12:00:00Z',timezone:'UTC'});assert.equal(calls.length,1);assert.equal(calls[0].name,'reporting_authoring_block_validate_v1');assert.deepEqual(calls[0].args.arguments,[{name:'maximum',value:{literal:'2'}}]);assert.equal(calls[0].args.digest,view.block.digest);assert(hasFreshMappingEvidence(result));assert(!hasFreshMappingEvidence(view));});
test('malformed or foreign validation evidence is an unknown outcome, never fresh evidence',async()=>{const v=mapView('private',7,true),w={block:{block:'private',revision:7,digest:v.block.digest,outputs:['amount']}};for(const mutate of [r=>r.state.id='foreign',r=>r.evidence.revision++,r=>r.evidence.definition_digest='f'.repeat(64),r=>r.evidence.execution_digest='f'.repeat(64),r=>r.evidence.expires_at='invalid',r=>r.evidence.expires_at='2000-01-01T00:00:00Z'])await assert.rejects(validatePrivateMapping(async()=>{const r=mapValidation(v);mutate(r);return r;},v,w,{},{}),e=>e.unknown===true);});

test('a pinned older private revision is edited by explicit new-target copy rather than rolling back current head',async()=>{const s=new MappingSession(async(name,args)=>{if(name==='chart_catalog')return mapClone(mapCatalog);const v=mapView(args.block,args.revision,true);v.block.state.draft_revision=args.revision+1;return v;});await s.open('private',7,'amount',false);assert.equal(s.copy,true);s.edit(d=>d.kind='column');await assert.rejects(s.save(),/invalid_request/);s.close();});
test('mapping CAS conflict keeps staged fields and blocks duplicate mutation attempts',async()=>{const f=callsFor();let writes=0;const s=new MappingSession(async(name,args)=>{if(name.endsWith('block_copy_v1')){writes++;throw appError('conflict');}return f.invoke(name,args);});await s.open('source',7,'amount');s.newBlock='copy';s.edit(d=>d.kind='column');await assert.rejects(s.save(),/conflict/);assert.equal(s.conflict,true);assert.equal(s.draft.kind,'column');assert.equal(s.unknown,false);await assert.rejects(s.save(),/busy/);assert.equal(writes,1);});

test('private validation uses native block fallback, literal, bound-filter precedence and parameter order',()=>{
 const view={block:{parameters:[{name:'maximum'},{name:'other'}]}},widget={literals:[{name:'maximum',value:{literal:'4'}}],bindings:[{filter:'period',parameter:'maximum'}]},page={defaults:[{name:'other',value:{literal:'9'}},{name:'maximum',value:{literal:'3'}},{name:'period',value:{literal:'99'}}],filters:[{parameter:{name:'period',default:{literal:'2'}}}]};
 const original=structuredClone({view,widget,page});
 assert.deepEqual(validationArguments(view,widget,page),[{name:'maximum',value:{literal:'2'}},{name:'other',value:{literal:'9'}}]);
 delete page.filters[0].parameter.default;assert.deepEqual(validationArguments(view,widget,page),[{name:'maximum',value:{literal:'4'}},{name:'other',value:{literal:'9'}}]);
 widget.literals=[];assert.deepEqual(validationArguments(view,widget,page),[{name:'maximum',value:{literal:'3'}},{name:'other',value:{literal:'9'}}]);
 const args=validationArguments(original.view,original.widget,original.page);args[0].value.literal='changed';assert.equal(original.page.filters[0].parameter.default.literal,'2');
});
test('private validation rejects duplicate names within each layer without rejecting valid precedence overrides',()=>{
 const view={block:{parameters:[{name:'p'}]}},w={literals:[],bindings:[]},page={defaults:[],filters:[]};
 for(const [widget,p]of [[{...w,literals:[{name:'p',value:{literal:'1'}},{name:'p',value:{literal:'2'}}]},page],[w,{...page,defaults:[{name:'foreign',value:{literal:'1'}},{name:'foreign',value:{literal:'2'}}]}],[{...w,bindings:[{filter:'f',parameter:'p'},{filter:'f',parameter:'p'}]},{...page,filters:[{parameter:{name:'f'}}]}]])assert.throws(()=>validationArguments(view,widget,p));
});
