import test from 'node:test';
import assert from 'node:assert/strict';
import {DraftSession, authoringTool, appError, manualDocument, newDefinition, layoutWidgets, layoutPreset, validateManualDefinition, unpack} from './model.js';
const caps={version:'report-authoring-v1',builder:true,consumer:true,can_create:true,can_open:true,can_save:true,can_preview:true,can_execute:true};
const definition=()=>({schema_version:2,metadata:[{locale:'en-US',title:'Weekly operations'}],locale:'en-US',timezone:'UTC',partial_failure:'fail_closed',filters:[],widgets:[{id:'intro',kind:'text',grid:{row:0,column:0,width:12,height:1},presentation:{},text:{format:'plain',text:'Heading'}}]});
const view=()=>({state:{id:'report-a',version:4,draft_revision:3},revision:3,private:true,definition:definition()});
const deferred=()=>{let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j;});return {promise,resolve,reject};};

test('one canonical document DTO preserves exact published output references',()=>{const d=definition();d.widgets.push({id:'kpi',kind:'block',grid:{row:1,column:0,width:12,height:1},presentation:{title:'Net amount'},block:{block:'approved-block',revision:7,outputs:['revenue'],policy:'published',narrative:false}});assert.equal(validateManualDefinition(d),d);assert.equal(d.schema_version,2);assert.equal(d.widgets[1].block.revision,7);assert.throws(()=>validateManualDefinition({...d,widgets:[...d.widgets,{...d.widgets[1],id:'copy'}]}),/invalid_request/);assert.equal(manualDocument({...d,widgets:[{kind:'query'}]}),false);assert.equal(manualDocument({...d,widgets:[{kind:'block',block:{narrative:true}}]}),false);});

test('layout edits preserve semantic payload and create a bounded nonoverlapping grid',()=>{const w=Array.from({length:5},(_,i)=>({...definition().widgets[0],id:'w'+i}));const laid=layoutWidgets(w,2);assert.deepEqual(laid[3].grid,{column:6,row:1,width:6,height:1});assert.deepEqual(laid[4].text,w[4].text);validateManualDefinition({...definition(),widgets:laid});assert.throws(()=>layoutWidgets(w,4),/invalid_request/);});

test('save creates a new immutable revision with returned CAS, never overwrites publication',async()=>{const calls=[];const s=new DraftSession(async(name,args)=>{calls.push({name,args});return {id:'report-a',version:5,draft_revision:4,published_revision:2};});s.setCapabilities(caps);s.replace(view());s.edit(d=>{d.metadata[0].title='Updated';});await s.save();assert.equal(calls[0].name,authoringTool('save'));assert.equal(calls[0].args.expected_version,4);assert.equal(calls[0].args.revision,3);assert.equal(calls[0].args.definition.metadata[0].title,'Updated');assert.equal(s.revision,4);assert.equal(s.state.version,5);assert.equal(s.dirty,false);});

test('create uses explicit admitted ID and does not call execute',async()=>{const calls=[];const s=new DraftSession(async(name,args)=>{calls.push({name,args});return {id:args.id,version:1,draft_revision:1};});s.setCapabilities(caps);s.new('New');await s.save('exact-report');assert.deepEqual(calls[0].args.definition,newDefinition('New'));assert.equal(calls.length,1);assert.equal(calls[0].name,authoringTool('create'));assert.equal(calls[0].args.id,'exact-report');});

test('conflict keeps local edits and blocks retries until authoritative reload',async()=>{let calls=0;const s=new DraftSession(async()=>{calls++;throw appError('conflict');});s.setCapabilities(caps);s.replace(view());s.edit(d=>{d.metadata[0].title='Unsaved';});await assert.rejects(s.save(),/conflict/);assert.equal(s.definition.metadata[0].title,'Unsaved');assert.equal(s.conflict,true);await assert.rejects(s.save(),/busy/);assert.equal(calls,1);s.replace(view());assert.equal(s.conflict,false);});

test('unknown outcome preserves local edits and never automatically retries',async()=>{let calls=0;const s=new DraftSession(async()=>{calls++;throw appError('unavailable',true);});s.setCapabilities(caps);s.replace(view());s.edit(d=>{d.widgets[0].text.text='Unsaved';});await assert.rejects(s.save(),/unavailable/);await assert.rejects(s.save(),/busy/);assert.equal(calls,1);assert.equal(s.dirty,true);});

test('repeated save and edits during pending save are fenced',async()=>{const pending=deferred();const s=new DraftSession(()=>pending.promise);s.setCapabilities(caps);s.replace(view());s.edit(d=>{d.metadata[0].title='Saved';});const first=s.save();await assert.rejects(s.save(),/busy/);assert.throws(()=>s.edit(()=>{}),/forbidden/);pending.resolve({id:'report-a',version:5,draft_revision:4});await first;assert.equal(s.dirty,false);});

test('late read and save responses cannot restore a closed app',async()=>{const pending=deferred();const s=new DraftSession(()=>pending.promise);s.setCapabilities(caps);s.replace(view());s.edit(d=>{d.metadata[0].title='Saved';});const first=s.save();s.close();pending.resolve({id:'report-a',version:5,draft_revision:4});assert.equal(await first,false);assert.equal(s.definition,null);assert.equal(s.state,null);});

test('newer navigation wins over a delayed opening response',async()=>{const old=deferred();const s=new DraftSession((name,args)=>name===authoringTool('capabilities')?Promise.resolve(caps):args.report==='old'?old.promise:Promise.resolve({...view(),state:{...view().state,id:'new'}}));const first=s.open('old');assert.equal(await s.open('new'),true);old.resolve({...view(),state:{...view().state,id:'old'}});assert.equal(await first,false);assert.equal(s.state.id,'new');});

test('consumer capability cannot mutate and untrusted result text is bounded data',()=>{const s=new DraftSession(()=>{});s.setCapabilities({...caps,can_save:false,can_create:false});s.replace(view());assert.throws(()=>s.edit(()=>{}),/forbidden/);assert.throws(()=>s.new('new'),/forbidden/);assert.throws(()=>unpack({isError:true,structuredContent:{error:{code:'forbidden',message:'secret'}}}),e=>e.message==='forbidden');assert.throws(()=>unpack({structuredContent:{result:{cycle:undefined}}}),/invalid_request/);});

test('selected content save sends only patch and refuses report-wide edits',async()=>{const calls=[];const s=new DraftSession(async(name,args)=>{calls.push({name,args});return {id:'report-a',version:5,draft_revision:4};});s.setCapabilities(caps);s.replace(view());s.edit(d=>{d.widgets[0].text.text='Changed heading';});assert.equal(s.canSaveWidget('intro'),true);await s.saveWidget('intro');assert.equal(calls[0].name,authoringTool('widget'));assert.equal(Object.hasOwn(calls[0].args,'definition'),false);assert.equal(calls[0].args.patch.text.text,'Changed heading');assert.equal(s.state.version,5);s.edit(d=>{d.metadata[0].title='Report-wide change';});assert.equal(s.canSaveWidget('intro'),false);await assert.rejects(s.saveWidget('intro'),/forbidden/);assert.equal(calls.length,1);});

test('retained decoder accepts viewer-sized dual-form results without expanding editor buffers',()=>{const result={version:'reporting-view-v1',text:'x'.repeat(3<<20)},body={result};const envelope={structuredContent:body,content:[{type:'text',text:JSON.stringify(body)}]};assert.equal(unpack(envelope).text.length,3<<20);const oversized={result:{text:'x'.repeat(4<<20)}};assert.throws(()=>unpack({structuredContent:oversized}),/limit_exceeded/);assert.throws(()=>unpack({structuredContent:{result:{ok:true}},content:[{type:'text',text:'x'.repeat(16<<20)}]}),/limit_exceeded/);const session=new DraftSession(()=>{});session.setCapabilities(caps);assert.throws(()=>session.replace({...view(),definition:{...definition(),description:'x'.repeat(3<<20)}}),/limit_exceeded/);});

test('canonical layout preset derives from stored cells and custom grids stay explicit',()=>{const widgets=Array.from({length:4},(_,index)=>({...definition().widgets[0],id:'w'+index}));for(const columns of [1,2,3])assert.equal(layoutPreset(layoutWidgets(widgets,columns)),String(columns));const custom=layoutWidgets(widgets,2);custom[1].grid.row=8;assert.equal(layoutPreset(custom),'custom');assert.equal(custom[1].grid.row,8);assert.equal(layoutPreset([]),'1');assert.equal(layoutPreset(null),'custom');});

test('new reports alone use a genuine blank v3 page and need no invented widget before save',()=>{
 const d=newDefinition('  New report  ');assert.equal(d.schema_version,3);assert.deepEqual(d.report_pages,[{id:'main',title:'Summary',widgets:[]}]);assert.equal(d.metadata[0].title,'New report');for(const key of ['widgets','filters','defaults'])assert.equal(Object.hasOwn(d,key),false);assert.equal(validateManualDefinition(d),d);
 const legacy=definition(),s=new DraftSession(()=>{});s.setCapabilities(caps);const before=JSON.stringify(legacy);s.replace({...view(),definition:legacy});assert.equal(JSON.stringify(s.definition),before);assert.equal(s.definition.schema_version,2);
});

test('native authoring hints intersect host tools without turning registration into permission',()=>{
 const names=['capabilities','create','read','save'].map(authoringTool);
 for(const missing of names){const s=new DraftSession(()=>{},name=>names.includes(name)&&name!==missing);s.setCapabilities(caps);assert.equal(s.capabilities.can_create,false);assert.throws(()=>s.new('Unavailable'),/forbidden/);}
 const s=new DraftSession(()=>{},name=>names.includes(name));s.setCapabilities({...caps,can_create:false});assert.equal(s.capabilities.can_create,false);assert.equal(s.capabilities.can_save,true);assert.equal(s.capabilities.can_preview,false);assert.equal(s.capabilities.can_execute,false);assert.equal(s.capabilities.consumer,false);assert.throws(()=>s.new('Denied'),/forbidden/);
});

test('text-only sessions retain full CAS editing while hiding unavailable narrow patches and rejecting nontext changes',async()=>{
 const names=['capabilities','read','save','create'].map(authoringTool),calls=[],s=new DraftSession(async(name,args)=>{calls.push({name,args});return {id:'report-a',version:5,draft_revision:4};},name=>names.includes(name));s.setCapabilities(caps);s.replace(view());
 s.edit(d=>{d.widgets[0].text.text='Text update';});assert.equal(s.canSaveWidget('intro'),false);await assert.rejects(s.saveWidget('intro'),/forbidden/);await s.save();assert.equal(calls[0].name,authoringTool('save'));assert.equal(calls[0].args.definition.schema_version,2);assert.equal(Object.hasOwn(calls[0].args.definition,'report_pages'),false);
 const before=JSON.stringify(s.definition);for(const change of [d=>{d.filters=[{parameter:{name:'filter'}}];},d=>{d.defaults=[{name:'filter',value:{literal:'x'}}];},d=>{d.widgets[0].bindings=[{parameter:'x',filter:'x'}];},d=>{d.widgets[0]={...d.widgets[0],kind:'block',block:{narrative:false}};}]){assert.throws(()=>s.edit(change),/forbidden/);assert.equal(JSON.stringify(s.definition),before);}
});
test('review and published edits require full CAS amendment rather than current-draft widget patch',async()=>{for(const stage of ['review','published']){const calls=[],s=new DraftSession(async(name,args)=>{calls.push({name,args});return {id:'report-a',version:5,draft_revision:4,review_revision:stage==='review'?3:0,published_revision:stage==='published'?3:0};});s.setCapabilities(caps);const v=view();v.state.draft_revision=0;v.state[stage+'_revision']=3;v.private=stage!=='published';s.replace(v);s.edit(d=>{d.widgets[0].text.text='Amendment';});assert.equal(s.canSaveWidget('intro'),false);await assert.rejects(s.saveWidget('intro'));await s.save();assert.equal(calls.length,1);assert.equal(calls[0].name,authoringTool('save'));assert.equal(calls[0].args.revision,3);assert.equal(s.stage,'draft');}});

test('exact publication reads reject an incorrect report or revision before replacing the working copy',async()=>{
 for(const change of [v=>v.state.id='another-report',v=>v.revision=2]){
  const value=view();change(value);const session=new DraftSession(async name=>name===authoringTool('capabilities')?caps:value);session.setCapabilities(caps);session.replace(view());const before=JSON.stringify(session.definition);
  await assert.rejects(session.open('report-a','',3),e=>e.code==='stale_validation');assert.equal(JSON.stringify(session.definition),before);assert.equal(session.revision,3);session.close();
 }
});
