import test from 'node:test';
import assert from 'node:assert/strict';
import {reportPages,pageContent,effectivePage,upgradeReportPages,addReportPage,renameReportPage,moveReportPage,removeReportPage,unusedWidgetID} from './pages.js';
import {newDefinition,validateManualDefinition,DraftSession,appError} from './model.js';
import {executionFingerprint} from './retained.js';
const clone=v=>JSON.parse(JSON.stringify(v));
const heading=(id='intro')=>({id,kind:'text',grid:{column:0,row:0,width:12,height:1},presentation:{title:'Introduction'},text:{format:'plain',text:'Hello'}});
const flat=()=>({schema_version:2,metadata:[{locale:'en-US',title:'Original'}],locale:'en-US',timezone:'UTC',partial_failure:'fail_closed',widgets:[heading()],filters:[{parameter:{name:'period',type:'integer',default:{literal:'1'}},label:'Period'}],defaults:[{name:'period',value:{literal:'2'}}],audience:['Original audience']});
const paged=()=>addReportPage(upgradeReportPages(flat()),'detail','Details');
const caps={version:'report-authoring-v1',can_save:true,can_create:true};
function session(d,invoke){const s=new DraftSession(invoke);s.setCapabilities(caps);s.replace({state:{id:'report-a',version:4,draft_revision:3},revision:3,definition:d});return s;}
test('v2 remains untouched until explicit upgrade, which preserves complete root and page state',()=>{const d=flat(),before=clone(d);assert.deepEqual(reportPages(d).map(p=>p.id),['main']);assert.equal(pageContent(d,'main'),d);assert.throws(()=>pageContent(d,'other'),/invalid_request/);const next=upgradeReportPages(d);assert.deepEqual(d,before);assert.equal(next.schema_version,3);assert.deepEqual(next.audience,d.audience);for(const key of ['widgets','filters','defaults']){assert(!Object.hasOwn(next,key));assert.deepEqual(next.report_pages[0][key],d[key]);}validateManualDefinition(next);assert.throws(()=>upgradeReportPages(next));});
test('page mutations retain stable coordinates and every sibling byte',()=>{const d=paged();d.report_pages[1].widgets.push(heading('detail-heading'));d.report_pages[1].locale='es-AR';d.report_pages[1].timezone='America/Argentina/Buenos_Aires';const saved=clone(d.report_pages[0]);let next=renameReportPage(d,'detail','Renamed');next=moveReportPage(next,'detail',-1);assert.equal(next.report_pages[0].id,'detail');assert.deepEqual(next.report_pages[1],saved);assert.equal(d.report_pages[1].title,'Details');assert.deepEqual(removeReportPage(next,'detail').report_pages,[saved]);assert.throws(()=>removeReportPage(removeReportPage(next,'detail'),'main'));assert.throws(()=>moveReportPage(d,'main',-1));assert.throws(()=>renameReportPage(d,'absent','No'));assert.throws(()=>addReportPage(d,'main','Duplicate'));assert.throws(()=>renameReportPage(d,'main',' '));assert.equal(effectivePage(d,'main').timezone,'UTC');assert.equal(effectivePage(d,'detail').locale,'es-AR');assert.throws(()=>pageContent(d,''));});
test('v3 empty pages save and overlap is page-local while widget IDs and budgets are report-global',()=>{const d=paged();assert.equal(validateManualDefinition(d),d);d.report_pages[1].widgets=[heading('second')];validateManualDefinition(d);d.report_pages[1].widgets[0].id='intro';assert.throws(()=>validateManualDefinition(d));d.report_pages[1].widgets=[];d.report_pages[1].filters=clone(d.report_pages[0].filters);d.report_pages[1].defaults=clone(d.report_pages[0].defaults);validateManualDefinition(d);for(const change of [v=>v.report_pages=[],v=>v.report_pages[1].id='main',v=>v.report_pages[1].timezone='invalid-zone',v=>v.report_pages[1].widgets=[{kind:'query'}],v=>v.report_pages[1].filters=Array(100).fill(v.report_pages[0].filters[0]),v=>v.report_pages[1].defaults=Array(64).fill(v.report_pages[0].defaults[0]),v=>v.report_pages=Array.from({length:101},(_,i)=>({id:'p'+i,title:'Page',widgets:[]})),v=>v.widgets=[heading('wrong-root')]]){const next=clone(d);change(next);assert.throws(()=>validateManualDefinition(next));}});
test('widget ID allocation checks every page and never reuses collision across pages',()=>{const d=paged();d.report_pages[1].widgets=[heading('widget-taken')];const ids=['taken','fresh'];assert.equal(unusedWidgetID(d,'widget',()=>ids.shift()),'widget-fresh');assert.throws(()=>unusedWidgetID(d,'widget',()=> 'taken'),/conflict/);});
test('v3 selected-content patch pins page and refuses unselected page or document changes',async()=>{const d=paged();d.report_pages[1].widgets=[heading('second')];const calls=[],s=session(d,async(name,args)=>{calls.push({name,args});return {id:'report-a',version:5,draft_revision:4};});s.edit(next=>pageContent(next,'detail').widgets[0].text.text='Changed');assert.equal(s.canSaveWidget('second'),false);assert.equal(s.canSaveWidget('second','main'),false);assert.equal(s.canSaveWidget('second','detail'),true);await s.saveWidget('second','detail');assert.equal(calls[0].args.page,'detail');assert.equal(calls[0].args.widget,'second');assert(!calls[0].args.definition);assert.deepEqual(s.definition.report_pages[0],d.report_pages[0]);s.edit(next=>pageContent(next,'main').widgets[0].text.text='Other page changed');assert.equal(s.canSaveWidget('second','detail'),false);});
test('v3 fingerprint ignores page titles/reordering and presentation while retaining every page semantic',()=>{const d=paged(),key=executionFingerprint(d),safe=clone(d);safe.report_pages.reverse();safe.report_pages[0].title='Display title';safe.report_pages[1].widgets[0].text.text='New heading';safe.report_pages[1].widgets[0].grid.height=3;assert.equal(executionFingerprint(safe),key);for(const change of [v=>v.report_pages[1].timezone='Europe/Madrid',v=>v.report_pages[1].locale='es',v=>v.report_pages[1].future_semantic='changed',v=>v.report_pages[0].defaults[0].value.literal='3',v=>v.report_pages[0].filters[0].parameter.default.literal='4',v=>v.report_pages[1].id='other',v=>v.report_pages.pop()]){const changed=clone(d);change(changed);assert.notEqual(executionFingerprint(changed),key);}assert.equal(d.report_pages[0].widgets[0].text.text,'Hello');});
test('v3 save retains all pages and unknown outcome blocks edits and retry',async()=>{let calls=0;const s=session(paged(),async()=>{calls++;throw appError('unavailable',true);});s.edit(d=>pageContent(d,'detail').widgets.push(heading('second')));await assert.rejects(s.save());assert.equal(s.definition.report_pages.length,2);assert.equal(s.uncertain,true);await assert.rejects(s.save());assert.throws(()=>s.edit(()=>{}));assert.equal(calls,1);});

test('private preview pins require v3 exact revision/digest and published pins cannot smuggle a digest',()=>{const d=paged();d.report_pages[1].widgets=[{id:'private',kind:'block',grid:{column:0,row:0,width:12,height:3},presentation:{},block:{block:'private-chart',revision:2,digest:'a'.repeat(64),policy:'private_preview',outputs:['amount'],narrative:false}}];validateManualDefinition(d);for(const change of [v=>v.report_pages[1].widgets[0].block.digest='bad',v=>delete v.report_pages[1].widgets[0].block.digest,v=>v.report_pages[1].widgets[0].block.revision=0,v=>v.report_pages[1].widgets[0].block.policy='published']){const bad=clone(d);change(bad);assert.throws(()=>validateManualDefinition(bad));}const old=flat();old.widgets=d.report_pages[1].widgets;assert.throws(()=>validateManualDefinition(old));});
