import test from 'node:test';
import assert from 'node:assert/strict';
import {PublicationSession,checkLifecycle,publicationEligible,publishedWidgets,stageLabel,PUBLICATION_METADATA_BYTES,PUBLICATION_CUSTODY_BYTES,PUBLICATION_CUSTODY_RECORDS,validRejectionNote} from './publication.js';
import {appError,authoringTool,DraftSession} from './model.js';
import {publicationFixture,clone} from './publication-fixture.mjs';
const block='chart-a:2';
async function session(f=publicationFixture(),invoke=f.invoke){const p=new PublicationSession(invoke);await p.open('report-a',1);return {f,p};}
async function publish(p){p.confirm('block_publish',block,true);return p.mutate('block_publish',block);}
async function rebind(p,ids=['first','second']){for(const id of ids)p.select(id,true);p.confirm('rebind_published',undefined,true);return p.mutate('rebind_published');}
async function transition(p,action){p.confirm(action,undefined,true);return p.mutate(action);}

test('full lifecycle requires separate exact confirmations and never executes data or promotes private artifacts',async()=>{const {f,p}=await session(),original=clone(f.report().definition);assert.equal(p.view.blocks[0].block.outputs.length,2);await assert.rejects(p.mutate('block_publish',block),/busy/);await publish(p);assert.equal(f.state().version,1);assert.equal(f.report().private,true);assert.equal(f.report().definition.report_pages[0].widgets[0].block.policy,'private_preview');await p.open('report-a',1);assert.equal(publishedWidgets(p.view).length,2);await assert.rejects(p.mutate('rebind_published'),/busy/);await rebind(p,['first']);assert.equal(f.report().definition.report_pages[0].widgets[1].block.policy,'private_preview');assert.deepEqual(f.report().definition.report_pages[1],original.report_pages[1]);await p.open('report-a',2);assert.throws(()=>p.confirm('review',undefined,true),/conflict/);await rebind(p,['second']);await p.open('report-a',3);await transition(p,'review');assert.equal(f.state().draft_revision,0);assert.equal(f.state().review_revision,3);assert.equal(f.report(3).private,true);await p.open('report-a',3);assert.equal(p.view.stage,'review');await assert.rejects(p.mutate('publish'),/busy/);await transition(p,'publish');await p.open('report-a',3);assert.equal(p.view.stage,'published');assert.equal(f.state().review_revision,0);assert.equal(f.report(3).private,false);assert(f.calls.every(c=>!['reporting_run','reporting_authoring_preview_v1','reporting_authoring_execute_v1','reporting_authoring_block_validate_v1'].includes(c.name)));assert.deepEqual(f.calls.find(c=>c.name===authoringTool('block_publish')).args,{block:'chart-a',expected_version:8,revision:2,digest:'a'.repeat(64),evidence:'validation-a'});});

test('rebind uses selected exact pins only and selection changes invalidate approval',async()=>{const {f,p}=await session();await publish(p);await p.open('report-a',1);p.select('first',true);p.confirm('rebind_published',undefined,true);p.select('second',true);await assert.rejects(p.mutate('rebind_published'),/busy/);p.select('second',false);p.confirm('rebind_published',undefined,true);await p.mutate('rebind_published');const args=f.calls.find(c=>c.name===authoringTool('rebind_published')).args;assert.deepEqual(Object.keys(args),['report','expected_version','revision','digest','widgets']);assert.deepEqual(args.widgets,[{widget:'first',block:'chart-a',revision:2,digest:'a'.repeat(64)}]);});

test('publish success and rebind conflict retain chart publication with no rollback or transition',async()=>{const f=publicationFixture(),{p}=await session(f,async(name,args)=>name===authoringTool('rebind_published')?Promise.reject(appError('conflict')):f.invoke(name,args));await publish(p);await p.open('report-a',1);await assert.rejects(rebind(p),/conflict/);assert.match(p.message,/remain published/);assert.equal(p.view,null);assert.equal(f.blocks.get(block).block.private,false);assert.equal(f.report().private,true);assert.equal(f.report().definition.report_pages[0].widgets[0].block.policy,'private_preview');assert(!f.calls.some(c=>c.name===authoringTool('report_transition')));});

test('unknown publication blocks retries through reload and resolves only via exact published inspection',async()=>{const f=publicationFixture();let lose=true;const {p}=await session(f,async(name,args)=>{const result=await f.invoke(name,args);if(name===authoringTool('block_publish')&&lose)throw appError('unavailable',true);return result;});await assert.rejects(publish(p),/unavailable/);const op=p.records('report-a')[0];assert.equal(op.status,'unknown');p.invalidate();await p.open('report-a',1);assert.equal(p.blocked('report-a'),true);await assert.rejects(p.mutate('block_publish',block),/busy/);await p.inspectOperation(op);assert.equal(op.status,'observed');assert.deepEqual(f.calls.at(-1).args,{block:'chart-a',revision:2});assert.equal(f.calls.filter(c=>c.name===authoringTool('block_publish')).length,1);});

test('unchanged exact state cannot clear an unknown in-flight CAS, while later version advancement fences it',async()=>{const f=publicationFixture(),{p}=await session(f,async(name,args)=>{if(name===authoringTool('block_publish'))throw appError('cancelled_or_timed_out',true);return f.invoke(name,args);});await assert.rejects(publish(p));const op=p.records('report-a')[0];await p.inspectOperation(op);assert.equal(op.status,'unknown');assert.match(p.message,/still unknown/);f.blocks.get(block).block.state.version++;await p.inspectOperation(op);assert.equal(op.status,'changed');assert.equal(p.blocked('report-a'),false);});

test('unknown rebind recovers from original report revision and checks whole transformed definition at new exact draft',async()=>{const f=publicationFixture(),{p}=await session(f,async(name,args)=>{const result=await f.invoke(name,args);if(name===authoringTool('rebind_published'))throw appError('unavailable',true);return result;});await publish(p);await p.open('report-a',1);await assert.rejects(rebind(p,['first']));const op=p.records('report-a').find(o=>o.action==='rebind_published');const view=await p.inspectOperation(op);assert.equal(op.status,'observed');assert.equal(view.report.revision,2);assert.deepEqual(f.calls.slice(-2).map(c=>c.args),[{report:'report-a',revision:1},{report:'report-a',revision:2}]);assert.equal(view.report.definition.report_pages[0].widgets[1].block.policy,'private_preview');});

test('unknown report publication inspects original reviewed revision after both private pointers clear',async()=>{const f=publicationFixture();f.definitions.get(1).report_pages[0].widgets=[];const {p}=await session(f,async(name,args)=>{const result=await f.invoke(name,args);if(name===authoringTool('report_transition')&&args.operation==='publish')throw appError('unavailable',true);return result;});await transition(p,'review');await p.open('report-a',1);await assert.rejects(transition(p,'publish'));const op=p.records('report-a').find(o=>o.action==='publish');const view=await p.inspectOperation(op);assert.equal(op.status,'observed');assert.equal(view.stage,'published');assert.deepEqual(f.calls.at(-1).args,{report:'report-a',revision:1});});

test('double click dispatches once and late mutation success cannot replace a navigated inspection',async()=>{const f=publicationFixture();let finish;const {p}=await session(f,async(name,args)=>{if(name===authoringTool('block_publish'))await new Promise(resolve=>finish=resolve);return f.invoke(name,args);});p.confirm('block_publish',block,true);const first=p.mutate('block_publish',block);await assert.rejects(p.mutate('block_publish',block),/busy/);p.invalidate();finish();assert.equal(await first,null);assert.equal(p.view,null);assert.equal(p.records('report-a')[0].status,'confirmed');assert.equal(f.calls.filter(c=>c.name===authoringTool('block_publish')).length,1);});

test('late inspection and close never repopulate view or confirmation',async()=>{const f=publicationFixture();let resolve;const p=new PublicationSession(()=>new Promise(r=>resolve=r)),opening=p.open('report-a',1);p.invalidate();resolve(f.lifecycle({report:'report-a',revision:1}));assert.equal(await opening,null);assert.equal(p.view,null);const late=p.open('report-a',1);p.close();resolve(f.lifecycle({report:'report-a',revision:1}));assert.equal(await late,null);assert.equal(p.operations.size,0);assert.equal(p.view,null);});

test('stale confirmation cannot authorize a changed version, output list, digest or evidence',async()=>{for(const change of [p=>p.view.blocks[0].block.state.version++,p=>p.view.blocks[0].block.outputs.push({id:'new-output',kind:'table'}),p=>p.view.blocks[0].block.digest='d'.repeat(64),p=>p.view.blocks[0].block.validation.id='new-evidence']){const {f,p}=await session();p.confirm('block_publish',block,true);change(p);await assert.rejects(p.mutate('block_publish',block),/busy/);assert.equal(f.calls.length,1);}});

test('validation requires current evidence, exact validated draft and server publish hint',async()=>{const f=publicationFixture(),item=f.blocks.get(block);assert.equal(publicationEligible(item),true);for(const change of [v=>v.can_publish=false,v=>v.validation_fresh=false,v=>v.block.state.draft_state='draft',v=>v.block.validation.expires_at='2000-01-01T00:00:00Z',v=>v.block.validation.definition_digest='f'.repeat(64),v=>v.block.private=false,v=>v.block.state.archived=true]){const v=clone(item);change(v);assert.equal(publicationEligible(v),false);}});

test('inspection rejects mixed target/revision, omitted outputs, contradictory publication and invented scope',()=>{const f=publicationFixture(),target={report:'report-a',revision:1};for(const change of [v=>v.report.state.id='foreign',v=>v.report.revision=2,v=>v.blocks[0].publication_scope='selected_output',v=>v.blocks[0].audience_effect='everyone',v=>v.blocks[0].block.outputs=[],v=>v.blocks[0].block.private=false,v=>v.report.digest='bad',v=>v.stage='review']){const v=f.lifecycle(target);change(v);assert.throws(()=>checkLifecycle(v,target),/stale_validation/);}});

test('missing optional tools block only their actions before dispatch',async()=>{const f=publicationFixture(),p=new PublicationSession(f.invoke,name=>name!==authoringTool('block_publish'));await p.open('report-a',1);p.confirm('block_publish',block,true);await assert.rejects(p.mutate('block_publish',block),/busy/);assert.equal(f.calls.length,1);const absent=new PublicationSession(f.invoke,()=>false);await assert.rejects(absent.open('report-a',1),/forbidden/);});

test('review is recoverable by explicit stage and editing preserves independent review pointer',async()=>{const f=publicationFixture();f.definitions.get(1).report_pages[0].widgets=[];const {p}=await session(f);await transition(p,'review');const draft=new DraftSession(f.invoke);await draft.open('report-a','review');assert.equal(draft.stage,'review');assert.equal(stageLabel(draft.stage),'Pending review');assert.deepEqual(f.calls.at(-1).args,{report:'report-a',revision:0,stage:'review'});draft.edit(d=>d.metadata[0].title='New draft title');await draft.save();assert.equal(draft.stage,'draft');assert.equal(draft.state.review_revision,1);assert.equal(draft.state.draft_revision,2);await p.open('report-a',2);assert.throws(()=>p.confirm('review',undefined,true),/forbidden/);await draft.open('report-a','review');assert.equal(draft.revision,1);assert.equal(draft.definition.metadata[0].title,'Lifecycle report');});

test('explicit retry requires an unchanged exact inspection, fresh confirmation and byte-identical original request',async()=>{const f=publicationFixture(),sent=[];let attempt=0;const {p}=await session(f,async(name,args)=>{if(name===authoringTool('block_publish')){sent.push(clone(args));if(attempt++===0)throw appError('unavailable',true);}return f.invoke(name,args);});await assert.rejects(publish(p));const op=p.records('report-a')[0];await assert.rejects(p.retry(op),/busy/);await p.inspectOperation(op);assert.equal(op.status,'unknown');assert.equal(p.retryEligible(op),true);assert.match(p.message,/identical metadata-only request/);await assert.rejects(p.retry(op),/busy/);p.confirmRetry(op,true);await p.retry(op);assert.equal(op.status,'confirmed');assert.deepEqual(sent[0],sent[1]);assert.equal(p.retryEligible(op),false);assert.equal(f.blocks.get(block).block.state.version,9);});

test('competing original commit makes an explicit retry conflict remain unknown until exact inspection',async()=>{const f=publicationFixture();let first=true;const {p}=await session(f,async(name,args)=>{if(name===authoringTool('block_publish')&&first){first=false;throw appError('unavailable',true);}return f.invoke(name,args);});await assert.rejects(publish(p));const op=p.records('report-a')[0];await p.inspectOperation(op);p.confirmRetry(op,true);await f.invoke(authoringTool('block_publish'),clone(op.args));await assert.rejects(p.retry(op),/conflict/);assert.equal(op.status,'unknown');assert.equal(p.retryEligible(op),false);await p.inspectOperation(op);assert.equal(op.status,'observed');assert.equal(f.blocks.get(block).block.state.version,9);});

test('retry confirmation cannot survive navigation, expired evidence, or a denied capability hint',async()=>{const f=publicationFixture(),{p}=await session(f,async(name,args)=>{if(name===authoringTool('block_publish'))throw appError('unavailable',true);return f.invoke(name,args);});await assert.rejects(publish(p));const op=p.records('report-a')[0];await p.inspectOperation(op);p.confirmRetry(op,true);p.invalidate();await assert.rejects(p.retry(op),/busy/);await p.inspectOperation(op);p.confirmRetry(op,true);op.retryView.blocks[0].block.validation.expires_at='2000-01-01T00:00:00Z';await assert.rejects(p.retry(op),/busy/);await p.inspectOperation(op);op.retryView.blocks[0].can_publish=false;assert.throws(()=>p.confirmRetry(op,true),/forbidden/);});

test('unknown rebind retry is independently confirmed and preserves the original selected widgets',async()=>{const f=publicationFixture(),sent=[];let fail=true;const {p}=await session(f,async(name,args)=>{if(name===authoringTool('rebind_published')){sent.push(clone(args));if(fail){fail=false;throw appError('unavailable',true);}}return f.invoke(name,args);});await publish(p);await p.open('report-a',1);await assert.rejects(rebind(p,['first']));const op=p.records('report-a').find(o=>o.action==='rebind_published');await p.inspectOperation(op);p.confirmRetry(op,true);await p.retry(op);assert.deepEqual(sent[0],sent[1]);assert.equal(f.report().definition.report_pages[0].widgets[1].block.policy,'private_preview');});

test('unknown review retry never changes to publication and original report digest remains pinned',async()=>{const f=publicationFixture();f.definitions.get(1).report_pages[0].widgets=[];let fail=true;const {p}=await session(f,async(name,args)=>{if(name===authoringTool('report_transition')&&fail){fail=false;throw appError('unavailable',true);}return f.invoke(name,args);});await assert.rejects(transition(p,'review'));const op=p.records('report-a')[0];await p.inspectOperation(op);p.confirmRetry(op,true);await p.retry(op);assert.equal(f.state().review_revision,1);assert.equal(f.state().published_revision,0);assert.equal(f.calls.at(-1).args.operation,'review');});

test('current snapshot identity uses native digest and CAS rather than JSON key ordering',async()=>{const {p}=await session(),r=p.view.report;const editor={state:clone(r.state),revision:r.revision,digest:r.digest,dirty:false,definition:{timezone:'UTC',schema_version:3}};assert.equal(p.current(editor),true);editor.digest='f'.repeat(64);assert.equal(p.current(editor),false);editor.digest=r.digest;editor.dirty=true;assert.equal(p.current(editor),false);});

test('unknown block custody prevents another report from dispatching the same publication',async()=>{const f=publicationFixture(),{p}=await session(f,async(name,args)=>{if(name===authoringTool('block_publish'))throw appError('unavailable',true);return f.invoke(name,args);});await assert.rejects(publish(p));p.invalidate();await p.open('report-b',1);p.confirm('block_publish',block,true);await assert.rejects(p.mutate('block_publish',block),/busy/);});

test('old timed-out mutation and explicit retry race through the same CAS with only one logical effect',async()=>{const f=publicationFixture();let originalArgs,releaseRetry,attempt=0;const {p}=await session(f,async(name,args)=>{if(name===authoringTool('block_publish')){if(attempt++===0){originalArgs=clone(args);throw appError('cancelled_or_timed_out',true);}await new Promise(resolve=>releaseRetry=resolve);}return f.invoke(name,args);});await assert.rejects(publish(p));const op=p.records('report-a')[0];await p.inspectOperation(op);p.confirmRetry(op,true);const retry=p.retry(op),failed=assert.rejects(retry,/conflict/);assert.equal(p.pending,true);const lateOriginal=f.invoke(authoringTool('block_publish'),originalArgs);releaseRetry();await lateOriginal;await failed;assert.equal(f.blocks.get(block).block.state.version,9);assert.equal(f.calls.filter(c=>c.name===authoringTool('block_publish')).length,2);assert.equal(op.status,'unknown');p.invalidate();assert.equal(p.view,null);await p.inspectOperation(op);assert.equal(op.status,'observed');assert.equal(p.view,null,'exact block recovery does not restore another report view');});

test('changed native head refuses identical retry even when earlier confirmation existed',async()=>{const f=publicationFixture(),{p}=await session(f,async(name,args)=>{if(name===authoringTool('block_publish'))throw appError('unavailable',true);return f.invoke(name,args);});await assert.rejects(publish(p));const op=p.records('report-a')[0];await p.inspectOperation(op);p.confirmRetry(op,true);f.blocks.get(block).block.state.version++;await p.inspectOperation(op);assert.equal(op.status,'changed');assert.equal(p.retryEligible(op),false);await assert.rejects(p.retry(op),/busy/);});


test('lifecycle metadata accepts detached responses above 2 MiB through the native 3 MiB boundary',()=>{const f=publicationFixture(),target={report:'report-a',revision:1},large=f.lifecycle(target);large.blocks[0].block.metadata=[{locale:'en-US',title:'Large synthetic metadata',description:'x'.repeat((2<<20)+(512<<10))}];const bytes=new TextEncoder().encode(JSON.stringify(large)).length;assert(bytes>2<<20);assert(bytes<PUBLICATION_METADATA_BYTES);const checked=checkLifecycle(large,target);large.blocks[0].block.metadata[0].description='changed';assert(checked.blocks[0].block.metadata[0].description.length>2<<20);const oversized=f.lifecycle(target);oversized.blocks[0].block.metadata=[{description:'x'.repeat(PUBLICATION_METADATA_BYTES)}];assert.throws(()=>checkLifecycle(oversized,target),/limit_exceeded/);const wide=f.lifecycle(target);wide.blocks[0].block.metadata=[{description:'🌊'.repeat(PUBLICATION_METADATA_BYTES/3)}];assert.throws(()=>checkLifecycle(wide,target),/limit_exceeded/);});

test('unknown publication custody retains every output identity and title without copying full mappings',async()=>{const f=publicationFixture();f.blocks.get(block).block.outputs[0].mapping.synthetic_metadata='x'.repeat((2<<20)+(128<<10));const {p}=await session(f,async(name,args)=>{if(name===authoringTool('block_publish'))throw appError('unavailable',true);return f.invoke(name,args);});p.confirm('block_publish',block,true);assert(p.token('block_publish',block).length<4096);await assert.rejects(p.mutate('block_publish',block));const op=p.records('report-a')[0];assert.deepEqual(op.disclosure,[{id:'amount',kind:'chart',title:'Revenue'},{id:'other',kind:'table',title:''}]);assert(p.custodyBytes<16<<10);await p.inspectOperation(op);assert.equal(p.retryEligible(op),true);assert(p.custodyBytes<16<<10);assert.equal(op.retryView.blocks[0].block.outputs[0].mapping,undefined);assert.equal(op.args.digest,'a'.repeat(64));assert.equal(op.args.evidence,'validation-a');});

async function custodyFixture({large=false,mode='unknown'}={}){const f=publicationFixture();await f.invoke(authoringTool('block_publish'),{block:'chart-a',revision:2,expected_version:8,digest:'a'.repeat(64),evidence:'validation-a'});if(large){const page=f.definitions.get(1).report_pages[1];page.widgets=Array.from({length:24},(_,i)=>({id:'text-'+i,kind:'text',grid:{column:0,row:i,width:12,height:1},presentation:{},text:{format:'plain',text:'x'.repeat(32768)}}));}const sent=[],p=new PublicationSession(async(name,args)=>{if(name===authoringTool('rebind_published')){sent.push(clone(args));if(mode==='unknown'||args.report==='report-0')throw appError('unavailable',true);return {id:args.report,version:args.expected_version+1,draft_revision:args.revision+1};}return f.invoke(name,args);});const add=async index=>{await p.open('report-'+index,1);p.select('first',true);p.confirm('rebind_published',undefined,true);try{await p.mutate('rebind_published');return null;}catch(error){return error;}};return {f,p,sent,add};}

test('aggregate 16 MiB recovery custody refuses a new dispatch without evicting unknown original requests',async()=>{const {p,sent,add}=await custodyFixture({large:true});let refused=false;for(let index=0;index<64;index++){const before=Array.from(p.operations.keys()),calls=sent.length,error=await add(index);assert(p.custodyBytes<=PUBLICATION_CUSTODY_BYTES);if(error?.code==='limit_exceeded'){assert.equal(sent.length,calls);assert.deepEqual(Array.from(p.operations.keys()),before);refused=true;break;}assert.equal(error?.code,'unavailable');}assert(refused);assert(sent.length>10);assert(sent.length<64);assert.equal(p.operations.size,sent.length);assert(Array.from(p.operations.values()).every(op=>op.status==='unknown'));const original=p.records('report-0')[0];assert.deepEqual(original.args,sent[0]);await p.inspectOperation(original);assert.equal(p.retryEligible(original),true,'compact exact inspection remains available for unresolved custody');assert(p.custodyBytes<=PUBLICATION_CUSTODY_BYTES);});

test('aggregate custody prunes only terminal known records and preserves unknown bases and exact args',async()=>{const {p,sent,add}=await custodyFixture({large:true,mode:'success'});assert.equal((await add(0)).code,'unavailable');const unknown=p.records('report-0')[0],base=JSON.stringify(unknown.base),args=clone(unknown.args);for(let index=1;index<=28;index++){assert.equal(await add(index),null);assert(p.custodyBytes<=PUBLICATION_CUSTODY_BYTES);}assert.equal(sent.length,29);assert(p.operations.size<29);assert.equal(p.operations.get(unknown.id),unknown);assert.equal(unknown.status,'unknown');assert.equal(JSON.stringify(unknown.base),base);assert.deepEqual(unknown.args,args);assert.equal(p.records('report-1').length,0);assert.equal(p.records('report-28')[0].status,'confirmed');});

test('64-record cap preserves all unknown custody and rejects before the sixty-fifth dispatch',async()=>{const {p,sent,add}=await custodyFixture();for(let index=0;index<PUBLICATION_CUSTODY_RECORDS;index++)assert.equal((await add(index)).code,'unavailable');const original=Array.from(p.operations.keys());assert.equal((await add(PUBLICATION_CUSTODY_RECORDS)).code,'limit_exceeded');assert.equal(sent.length,PUBLICATION_CUSTODY_RECORDS);assert.deepEqual(Array.from(p.operations.keys()),original);assert(p.custodyBytes<PUBLICATION_CUSTODY_BYTES);});

test('64-record cap prunes terminal records while retaining an earlier unresolved request',async()=>{const {p,add}=await custodyFixture({mode:'success'});assert.equal((await add(0)).code,'unavailable');const unknown=p.records('report-0')[0];for(let index=1;index<=70;index++)assert.equal(await add(index),null);assert.equal(p.operations.size,PUBLICATION_CUSTODY_RECORDS);assert.equal(p.operations.get(unknown.id),unknown);assert.equal(p.records('report-1').length,0);assert.equal(p.records('report-70')[0].status,'confirmed');});


async function reviewedSession({newer=false,published=false,wrap=fn=>fn}={}){const f=publicationFixture();f.definitions.get(1).report_pages[0].widgets=[];const {p}=await session(f,wrap(f.invoke));if(published){await transition(p,'review');await p.open('report-a',1);await transition(p,'publish');await f.invoke(authoringTool('save'),{report:'report-a',expected_version:f.state().version,revision:1,definition:clone(f.report(1).definition)});await p.open('report-a',2);}const revision=p.view.report.revision;await transition(p,'review');if(newer){const definition=clone(f.report(revision).definition);definition.metadata[0].title='Newer draft must survive';await f.invoke(authoringTool('save'),{report:'report-a',expected_version:f.state().version,revision,definition});}await p.open('report-a',revision);return {f,p,revision};}
function confirmReject(p,note='Please amend the title.'){p.setRejectNote(note);p.confirm('reject',undefined,true);}

test('native Reject requires its own capability, a bounded meaningful note and separate confirmation',async()=>{const {f,p}=await reviewedSession();await assert.rejects(p.mutate('reject'),/busy/);assert.throws(()=>p.confirm('reject',undefined,true),/invalid_request/);for(const note of ['', '   ', 'bad\u0000note', '🌊'.repeat(513)])assert.equal(validRejectionNote(note),false);assert.equal(validRejectionNote('🌊'.repeat(512)),true);confirmReject(p);p.setRejectNote('A changed note needs fresh approval.');await assert.rejects(p.mutate('reject'),/busy/);p.confirm('reject',undefined,true);p.view.can_reject=false;await assert.rejects(p.mutate('reject'),/busy/);p.view.can_reject=true;p.confirm('reject',undefined,true);await p.mutate('reject');assert.equal(f.state().review_revision,0);assert.equal(f.state().draft_revision,1);assert.equal(f.state().published_revision,0);assert.equal(f.report(1).private,true);assert.deepEqual(f.calls.at(-1).args,{report:'report-a',expected_version:2,revision:1,operation:'reject',note:'A changed note needs fresh approval.'});await p.open('report-a',1);assert.equal(p.rejected('report-a',1),true);assert.throws(()=>p.confirm('review',undefined,true),/forbidden/);});

test('Reject preserves an independent newer draft and an existing publication',async()=>{const {f,p,revision}=await reviewedSession({newer:true,published:true}),before=clone(f.state()),draft=clone(f.report(before.draft_revision));confirmReject(p);const op=await p.mutate('reject');assert.equal(op.state.draft_revision,before.draft_revision);assert.equal(op.state.published_revision,before.published_revision);assert.equal(op.state.review_revision,0);assert.deepEqual(f.report(before.draft_revision).definition,draft.definition);assert.equal(f.report(revision).private,true);assert.equal(f.report(before.published_revision).private,false);assert.match(p.message,/newer draft and current publication are preserved/);assert(!f.calls.some(c=>c.name==='reporting_run'));});

test('unknown Reject recovers exact private returned state without treating publication as rejection',async()=>{const {f,p,revision}=await reviewedSession({newer:true,published:true,wrap:fn=>async(name,args)=>{const result=await fn(name,args);if(name===authoringTool('report_transition')&&args.operation==='reject')throw appError('unavailable',true);return result;}});confirmReject(p);await assert.rejects(p.mutate('reject'));const op=p.records('report-a').find(o=>o.action==='reject');const view=await p.inspectOperation(op);assert.equal(op.status,'observed');assert.equal(view.report.private,true);assert.equal(view.stage,'private_revision');assert.match(p.message,/remains private/);assert.match(p.message,/does not identify which caller/);assert.deepEqual(f.calls.at(-1).args,{report:'report-a',revision});});

test('unknown Reject followed by someone publishing the reviewed revision reports changed, never rejection',async()=>{let rejectArgs;const {f,p,revision}=await reviewedSession({wrap:fn=>async(name,args)=>{if(name===authoringTool('report_transition')&&args.operation==='reject'){rejectArgs=clone(args);throw appError('unavailable',true);}return fn(name,args);}});confirmReject(p);await assert.rejects(p.mutate('reject'));const op=p.records('report-a').find(o=>o.action==='reject');await f.invoke(authoringTool('report_transition'),{...rejectArgs,operation:'publish',note:''});const view=await p.inspectOperation(op);assert.equal(op.status,'changed');assert.equal(view.stage,'published');assert.equal(view.report.private,false);assert.equal(p.rejected('report-a',revision),false);assert(!p.message.includes('returned for amendment'));await assert.rejects(p.retry(op),/busy/);});

test('unchanged Reject retry preserves its original note and cannot become a publication action',async()=>{let fail=true;const sent=[];const {f,p}=await reviewedSession({wrap:fn=>async(name,args)=>{if(name===authoringTool('report_transition')&&args.operation==='reject'){sent.push(clone(args));if(fail){fail=false;throw appError('unavailable',true);}}return fn(name,args);}});confirmReject(p,'Keep the newer draft and correct the reviewed copy.');await assert.rejects(p.mutate('reject'));const op=p.records('report-a').find(o=>o.action==='reject');await p.inspectOperation(op);assert.equal(p.retryEligible(op),true);p.setRejectNote('This later field edit does not replace the original request.');p.confirmRetry(op,true);await p.retry(op);assert.deepEqual(sent[0],sent[1]);assert.equal(f.state().published_revision,0);assert.equal(f.state().review_revision,0);});


test('native rejected metadata survives fresh app custody and requires a new amended revision',async()=>{const {f,p}=await reviewedSession();confirmReject(p);await p.mutate('reject');p.close();const fresh=new PublicationSession(f.invoke);await fresh.open('report-a',1);assert.equal(fresh.view.rejected,true);assert.equal(fresh.view.can_review,false);assert.throws(()=>fresh.confirm('review',undefined,true),/forbidden/);const amended=clone(f.report(1).definition);amended.metadata[0].title='Amended report';await f.invoke(authoringTool('save'),{report:'report-a',expected_version:f.state().version,revision:1,definition:amended});await fresh.open('report-a',2);assert.equal(fresh.view.rejected,false);assert.equal(fresh.view.can_review,true);fresh.confirm('review',undefined,true);await fresh.mutate('review');assert.equal(f.state().review_revision,2);});

test('missing rejection receipt never fabricates successful rejection from pointer changes',async()=>{const {f,p}=await reviewedSession({wrap:fn=>async(name,args)=>{const result=await fn(name,args);if(name===authoringTool('report_transition')&&args.operation==='reject')throw appError('unavailable',true);if(name===authoringTool('lifecycle'))delete result.rejected;return result;}});confirmReject(p);await assert.rejects(p.mutate('reject'));const op=p.records('report-a').find(o=>o.action==='reject');await p.inspectOperation(op);assert.equal(op.status,'changed');assert.equal(p.rejected('report-a',1),false);assert(!p.message.includes('returned for amendment'));});

test('Reject CAS conflict cannot discard a concurrently created newer draft',async()=>{const {f,p,revision}=await reviewedSession();confirmReject(p);const definition=clone(f.report(revision).definition);definition.metadata[0].title='Concurrent newer draft';await f.invoke(authoringTool('save'),{report:'report-a',expected_version:f.state().version,revision,definition});await assert.rejects(p.mutate('reject'),/conflict/);assert.equal(f.state().review_revision,revision);assert.equal(f.state().draft_revision,2);assert.equal(f.report(2).definition.metadata[0].title,'Concurrent newer draft');assert.equal(p.records('report-a').find(o=>o.action==='reject').status,'failed');});

test('duplicate Reject and late response are fenced without restoring old review or note after navigation',async()=>{let release;const {p,f}=await reviewedSession({newer:true,wrap:fn=>async(name,args)=>{if(name===authoringTool('report_transition')&&args.operation==='reject')await new Promise(resolve=>release=resolve);return fn(name,args);}});confirmReject(p,'Return only the old review.');const pending=p.mutate('reject');await assert.rejects(p.mutate('reject'),/busy/);p.invalidate();release();assert.equal(await pending,null);assert.equal(p.view,null);assert.equal(p.rejectNote,'');assert.equal(f.state().draft_revision,2);assert.equal(f.state().review_revision,0);assert.equal(f.calls.filter(c=>c.args.operation==='reject').length,1);});
