import test from 'node:test';
import assert from 'node:assert/strict';
import {ReportApp} from './app.js';
import {publicationFixture,multiChartFixture,clone} from './publication-fixture.mjs';
import {authoringTool,appError} from './model.js';
class Element {
 constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.attributes={};this.listeners={};this.dataset={};this.style={setProperty(name,value){this[name]=value;}};this._text='';this.disabled=false;this.value='';this.checked=false;}
 set textContent(value){this.children=[];this._text=String(value);}get textContent(){return this._text+this.children.map(c=>c.textContent||'').join('');}
 append(...children){this.children.push(...children);}replaceChildren(...children){this._text='';this.children=children;}
 setAttribute(name,value){this.attributes[name]=String(value);}getAttribute(name){return this.attributes[name]??null;}
 addEventListener(name,fn){this.listeners[name]=fn;}emit(name,event={}){this.listeners[name]?.({target:this,currentTarget:this,preventDefault(){},stopPropagation(){},...event});}
 querySelectorAll(tag){return this.children.flatMap(c=>[...(c.tagName===tag.toUpperCase()?[c]:[]),...(c.querySelectorAll?.(tag)||[])]);}
 getBoundingClientRect(){return {width:1000,height:800};}
}
const buttons=(root,label)=>root.querySelectorAll('button').filter(b=>b.textContent===label);
function tickBox(root,label){const box=root.querySelectorAll('input').find(i=>i.getAttribute('aria-label')===label);assert(box,label);assert.equal(box.disabled,false);box.checked=true;box.emit('change');}
async function setup({supports=()=>true,wrap=(fn)=>fn,fixture=publicationFixture}={}){globalThis.document={createElement:tag=>new Element(tag),createElementNS:(_,tag)=>new Element(tag),documentElement:new Element('html')};const root=new Element('main'),f=fixture(),invoke=wrap(f.invoke),app=new ReportApp(root,{resize(){},supportsTool:supports,async call(name,args){return {structuredContent:{result:await invoke(name,args)}};}});app.mode='builder';await app.openDraft('report-a');app.render();return {root,f,app};}
async function chartPublish(app,root){await app.inspectPublication();app.render();tickBox(root,'I confirm publishing the entire chart revision and all listed outputs.');await app.publishAction('block_publish','chart-a:2');app.render();}
async function bindAll(app){app.publication.select('first',true);app.publication.select('second',true);app.publication.confirm('rebind_published',undefined,true);await app.publishAction('rebind_published');app.render();}

test('controls disclose all outputs before explicit whole-revision publish and separate selected-widget rebind',async()=>{const {root,f,app}=await setup();assert(!buttons(root,'Publish entire chart revision').length);await app.inspectPublication();app.render();assert.match(root.textContent,/ENTIRE immutable chart revision/);assert.match(root.textContent,/other · table/);assert.match(root.textContent,/Audience details are unavailable/);assert.equal(buttons(root,'Publish entire chart revision')[0].disabled,true);tickBox(root,'I confirm publishing the entire chart revision and all listed outputs.');assert.equal(buttons(root,'Publish entire chart revision')[0].disabled,false);await app.publishAction('block_publish','chart-a:2');app.render();assert.equal(app.session.definition.report_pages[0].widgets[0].block.policy,'private_preview');assert(!buttons(root,'Rebind selected widgets').length);tickBox(root,'Summary / first · first · chart-a revision 2');assert.equal(buttons(root,'Rebind selected widgets')[0].disabled,true);tickBox(root,'I confirm rebinding only the selected widgets to their exact published chart revisions.');await app.publishAction('rebind_published');assert.equal(app.session.revision,2);assert.equal(app.session.definition.report_pages[0].widgets[1].block.policy,'private_preview');assert.match(app.message,/still private/);assert(!f.calls.some(c=>c.name==='reporting_run'));app.close();});

test('controller full journey preserves preview privacy, recovers review list and only Browse discovers publication',async()=>{const {root,f,app}=await setup();await chartPublish(app,root);await bindAll(app);const preview={summary:{private:true,target:{id:'report-a',revision:1},state:'completed'},pages:[]};app.preview=preview;app._uiPreviewDefinition=clone(f.report(1).definition);app._uiPreviewOrigin={report:'report-a',revision:1};app.render();assert.equal(buttons(root,'Submit report for review')[0].disabled,true);tickBox(root,'I confirm submitting this exact report revision for review.');await app.publishAction('review');assert.equal(app.session.stage,'review');assert.equal(app.session.state.draft_revision,0);assert.equal(app.drafts[0].stage,'review');assert.equal(preview.summary.private,true);app.render();assert.match(root.textContent,/Pending review · revision 2/);assert(!root.textContent.includes('Private draft · revision 2'));assert.match(root.textContent,/Editing and saving creates a new draft/);await app.openDraft('report-a','review');await app.inspectPublication();app.render();tickBox(root,'I confirm publishing this exact reviewed report revision.');await app.publishAction('publish');assert.equal(app.session.stage,'published');assert.equal(app.session.revision,2);assert.deepEqual(f.calls.filter(c=>c.name===authoringTool('lifecycle')).at(-1).args,{report:'report-a',revision:2});assert.equal(f.calls.filter(c=>c.name==='reporting_run').length,0);app.preview=preview;await app.changeMode('consumer');assert.equal(app.preview,null);assert.equal(app.retained.outputs?.size||0,0);assert.equal(app.catalog[0].target.revision,2);assert.equal(preview.summary.private,true);app.close();});

test('native false publish hint suppresses confirmation even when transition tool exists',async()=>{const {root,f,app}=await setup({wrap:fn=>async(name,args)=>{const value=await fn(name,args);if(name===authoringTool('lifecycle'))value.can_publish=false;return value;}});await chartPublish(app,root);await bindAll(app);app.publication.confirm('review',undefined,true);await app.publishAction('review');app.render();assert(!buttons(root,'Publish reviewed report').length);assert.match(root.textContent,/native authority/);assert.throws(()=>app.publication.confirm('publish',undefined,true),/forbidden/);assert(!f.calls.some(c=>c.args.operation==='publish'));app.close();});

test('missing lifecycle hides controls; each missing mutation suppresses its exact action',async()=>{for(const action of ['lifecycle','block_publish','rebind_published','report_transition']){const {root,app}=await setup({supports:name=>name!==authoringTool(action)});if(action==='lifecycle'){assert(!root.textContent.includes('Publication and review'));}else{await app.inspectPublication();app.render();if(action==='block_publish')assert(!buttons(root,'Publish entire chart revision').length);if(action==='rebind_published'){await chartPublish(app,root);assert(!root.textContent.includes('Use published charts in this report'));}if(action==='report_transition'){await chartPublish(app,root);await bindAll(app);assert(!buttons(root,'Submit report for review').length);}}app.close();}});

test('late report inspection after navigation never changes new report or exposes prior metadata',async()=>{let release,hold=false;const {f,app}=await setup({wrap:fn=>async(name,args)=>{if(hold&&name===authoringTool('lifecycle'))await new Promise(resolve=>release=resolve);return fn(name,args);}});hold=true;const inspect=app.inspectPublication();await app.openDraft('report-b');release();await inspect;assert.equal(app.session.state.id,'report-b');assert.equal(app.publication.view,null);assert.equal(app.message,'');app.close();});

test('unknown publish survives navigation and reopens recovery without exposing private data in Browse',async()=>{const {root,app}=await setup({wrap:fn=>async(name,args)=>{const value=await fn(name,args);if(name===authoringTool('block_publish'))throw appError('unavailable',true);return value;}});await app.inspectPublication();app.publication.confirm('block_publish','chart-a:2',true);await assert.rejects(app.publishAction('block_publish','chart-a:2'));await app.changeMode('consumer');app.render();assert(!root.textContent.includes('Unknown block publish'));await app.changeMode('builder');await app.openDraft('report-a');app.render();assert.match(root.textContent,/Unknown block publish outcome/);assert.equal(app.canEdit(),false);const op=app.publication.records('report-a')[0];await app.inspectPublicationOperation(op);assert.equal(op.status,'observed');assert.equal(app.canEdit(),true);assert.match(app.message,/Exact inspection confirms/);app.close();});

test('controller double clicks are gated while late publication cannot replace another open report',async()=>{let release;const {app,f}=await setup({wrap:fn=>async(name,args)=>{if(name===authoringTool('block_publish'))await new Promise(resolve=>release=resolve);return fn(name,args);}});await app.inspectPublication();app.publication.confirm('block_publish','chart-a:2',true);const mutation=app.perform(()=>app.publishAction('block_publish','chart-a:2'));await app.perform(()=>app.publishAction('block_publish','chart-a:2'));const before=app.epoch;await app.changeMode('consumer');release();await mutation;assert(app.epoch>before);assert.equal(app.mode,'consumer');assert.equal(app.session.state,null);assert.equal(app.publication.view,null);assert.equal(f.calls.filter(c=>c.name===authoringTool('block_publish')).length,1);app.close();});

test('unchanged unknown operation offers a separately confirmed identical retry without source work',async()=>{let lose=true;const {root,app,f}=await setup({wrap:fn=>async(name,args)=>{if(name===authoringTool('block_publish')&&lose){lose=false;throw appError('unavailable',true);}return fn(name,args);}});await app.inspectPublication();app.publication.confirm('block_publish','chart-a:2',true);await assert.rejects(app.publishAction('block_publish','chart-a:2'));const op=app.publication.records('report-a')[0];app.render();assert(!buttons(root,'Retry identical inspected request').length);await app.inspectPublicationOperation(op);app.render();assert.match(root.textContent,/earlier request may still be completing/);assert.match(root.textContent,/other · table/);assert.equal(buttons(root,'Retry identical inspected request')[0].disabled,true);tickBox(root,'I confirm retrying this identical inspected request with its original version and revision.');await app.retryPublicationOperation(op);assert.equal(op.status,'confirmed');assert.equal(app.session.definition.report_pages[0].widgets[0].block.policy,'private_preview');assert.equal(f.calls.filter(c=>c.name==='reporting_run').length,0);app.close();});

test('late publication error after mode navigation cannot overwrite the new screen message',async()=>{let reject;const {app}=await setup({wrap:fn=>async(name,args)=>name===authoringTool('block_publish')?new Promise((_,r)=>reject=r):fn(name,args)});await app.inspectPublication();app.publication.confirm('block_publish','chart-a:2',true);const pending=app.perform(()=>app.publishAction('block_publish','chart-a:2'));await app.changeMode('consumer');app.message='New screen';reject(appError('unavailable',true));await pending;assert.equal(app.message,'New screen');assert.equal(app.publication.view,null);app.close();});

test('successful publication and failed follow-up read disclose the committed chart without claiming rollback',async()=>{let failRead=false;const {app}=await setup({wrap:fn=>async(name,args)=>{if(name===authoringTool('lifecycle')&&failRead)throw appError('unavailable');const value=await fn(name,args);if(name===authoringTool('block_publish'))failRead=true;return value;}});await app.inspectPublication();app.publication.confirm('block_publish','chart-a:2',true);await app.perform(()=>app.publishAction('block_publish','chart-a:2'));assert.match(app.message,/entire chart revision is published/);assert.match(app.message,/follow-up inspection is unavailable/);assert.equal(app.publication.records('report-a')[0].status,'confirmed');assert.equal(app.session.definition.report_pages[0].widgets[0].block.policy,'private_preview');app.close();});

async function reviewForReturn(app,f,{newer=false}={}){f.definitions.get(1).report_pages[0].widgets=[];await app.openDraft('report-a');await app.inspectPublication();app.publication.confirm('review',undefined,true);await app.publishAction('review');if(newer){app.edit(d=>{d.metadata[0].title='Newer draft preserved';});await app.save();await app.openDraft('report-a','review');}await app.inspectPublication();app.render();}
function rejectionNote(root,value){const input=root.querySelectorAll('textarea').find(i=>i.getAttribute('aria-label')==='Reason for returning review');assert(input);input.value=value;input.emit('input');}

test('Return review requires note and checkbox, then loads the preserved newer draft rather than old content',async()=>{const {root,f,app}=await setup();await reviewForReturn(app,f,{newer:true});assert.equal(app.session.revision,1);assert.equal(app.session.state.draft_revision,2);assert.equal(buttons(root,'Return reviewed report')[0].disabled,true);assert.match(root.textContent,/Keep any newer draft and the current publication/);rejectionNote(root,'Please amend the reviewed title.');assert.equal(buttons(root,'Return reviewed report')[0].disabled,true);tickBox(root,'I confirm rejecting this exact reviewed revision with the note above.');rejectionNote(root,'Please amend the title and subtitle.');assert.equal(buttons(root,'Return reviewed report')[0].disabled,true);tickBox(root,'I confirm rejecting this exact reviewed revision with the note above.');await app.publishAction('reject');app.render();assert.equal(app.session.revision,2);assert.equal(app.session.stage,'draft');assert.equal(app.session.definition.metadata[0].title,'Newer draft preserved');assert.equal(app.session.state.review_revision,0);assert.equal(app.publication.view.rejected,false);assert.match(app.message,/Review returned for amendment/);assert.equal(f.calls.filter(c=>c.name===authoringTool('report_transition')&&c.args.operation==='reject').length,1);assert(!f.calls.some(c=>c.name==='reporting_run'));app.close();});

test('returned sole draft shows native amendment-required state and has no resubmit action after reopening',async()=>{const {root,f,app}=await setup();await reviewForReturn(app,f);rejectionNote(root,'Amend this revision before resubmitting.');tickBox(root,'I confirm rejecting this exact reviewed revision with the note above.');await app.publishAction('reject');assert.equal(app.session.stage,'draft');assert.equal(app.session.revision,1);app.publication.operations.clear();await app.openDraft('report-a');await app.inspectPublication();app.render();assert.match(root.textContent,/Edit and save a new revision before resubmitting/);assert(!buttons(root,'Submit report for review').length);app.edit(d=>{d.metadata[0].title='Amended';});await app.save();await app.inspectPublication();app.render();assert.equal(app.publication.view.rejected,false);assert(buttons(root,'Submit report for review').length);app.close();});

test('unknown Reject inspection keeps older exact private history read-only and offers current draft',async()=>{const {root,f,app}=await setup({wrap:fn=>async(name,args)=>{const result=await fn(name,args);if(name===authoringTool('report_transition')&&args.operation==='reject')throw appError('unavailable',true);return result;}});await reviewForReturn(app,f,{newer:true});app.publication.setRejectNote('Return the older reviewed revision.');app.publication.confirm('reject',undefined,true);await assert.rejects(app.publishAction('reject'));const op=app.publication.records('report-a').find(o=>o.action==='reject');await app.inspectPublicationOperation(op);app.render();assert.equal(op.status,'observed');assert.equal(app.session.revision,1);assert.equal(app.session.stage,'private_revision');assert.equal(app.canEdit(),false);assert.match(root.textContent,/older private revision is available for inspection/);assert.equal(buttons(root,'Open current draft')[0].disabled,false);assert.throws(()=>app.session.edit(d=>d.metadata[0].title='Must not overwrite newer content'),/forbidden/);await app.openDraft('report-a','draft');assert.equal(app.session.revision,2);assert.equal(app.session.definition.metadata[0].title,'Newer draft preserved');app.close();});

test('missing native Reject hint hides note and return action despite generic transition tool presence',async()=>{const {root,f,app}=await setup({wrap:fn=>async(name,args)=>{const result=await fn(name,args);if(name===authoringTool('lifecycle'))result.can_reject=false;return result;}});await reviewForReturn(app,f);assert(!buttons(root,'Return reviewed report').length);assert(!root.querySelectorAll('textarea').some(i=>i.getAttribute('aria-label')==='Reason for returning review'));app.publication.setRejectNote('Cannot bypass denied current authority.');assert.throws(()=>app.publication.confirm('reject',undefined,true),/forbidden/);app.close();});
test('publication workflow is compact by default and deliberate inspection stays expanded',async()=>{const {app,root}=await setup();const panel=()=>root.querySelectorAll('details').find(n=>n.getAttribute('aria-label')==='Publication and review');assert.equal(panel().open,false);panel().open=true;panel().emit('toggle');app.render();assert.equal(panel().open,true);await app.inspectPublication();app.render();assert.equal(panel().open,true);panel().open=false;panel().emit('toggle');app.render();assert.equal(panel().open,false);await app.openDraft('report-a');app.render();assert.equal(panel().open,false);app.close();});

test('publication guidance follows native gates and returns through the reader to a new amendment',async()=>{
 const {root,f,app}=await setup({wrap:invoke=>async(name,args)=>{
  if(name==='reporting_describe')return {resource:{target:args.target,title:'Lifecycle report'},filters:[],timezone:'UTC'};
  if(name==='reporting_runs')return {items:[],next:''};
  return invoke(name,args);
 }});
 await app.inspectPublication();app.render();assert(root.textContent.includes('1 · Publish charts'));
 await chartPublish(app,root);assert(root.textContent.includes('2 · Link published charts'));
 await bindAll(app);assert(root.textContent.includes('3 · Submit for review'));
 app.publication.confirm('review',undefined,true);await app.publishAction('review');app.render();assert(root.textContent.includes('4 · Publish report'));
 app.publication.confirm('publish',undefined,true);await app.publishAction('publish');app.render();const published=clone(f.report(2));
 buttons(root,'Open published report')[0].emit('click');for(let i=0;i<20&&app.busy;i++)await new Promise(resolve=>setImmediate(resolve));assert.equal(app.busy,false);assert.equal(app.mode,'consumer');assert.equal(app.selected.target.revision,2);assert(buttons(root,'Edit report').length);
 await app.editPublished();assert.equal(app.session.stage,'published');app.edit(d=>d.metadata[0].title='Amended report');await app.save();assert.equal(app.session.stage,'draft');assert.equal(app.session.revision,3);assert.deepEqual(f.report(2).definition,published.definition);
 await app.inspectPublication();app.publication.confirm('review',undefined,true);await app.publishAction('review');app.publication.confirm('publish',undefined,true);await app.publishAction('publish');assert.equal(app.session.stage,'published');assert.equal(app.session.revision,3);assert.deepEqual(f.report(2).definition,published.definition);assert(!f.calls.some(c=>/preview|execute|reporting_run$/.test(c.name)));app.close();
});


test('twelve-chart controls disclose exact revisions, batch only after confirmation, and explicitly select all links',async()=>{const {root,f,app}=await setup({fixture:multiChartFixture});await app.inspectPublication();app.render();assert.equal(buttons(root,'Publish 12 ready charts')[0].disabled,true);assert.equal(root.querySelectorAll('article').filter(el=>el.textContent.includes('Included in ready charts')).length,12);assert.match(root.textContent,/every listed output/);tickBox(root,'I confirm publishing all 12 ready chart revisions and every listed output.');assert.equal(buttons(root,'Publish 12 ready charts')[0].disabled,false);await app.publishChartBatch();app.render();assert.equal(app.publication.records('report-a').length,12);assert.equal(app.session.revision,1);assert(app.session.definition.report_pages.flatMap(p=>p.widgets).every(w=>w.block.policy==='private_preview'));buttons(root,'Select all 12 components')[0].emit('click');assert.equal(app.publication.selection.size,12);assert.equal(app.publication.confirmed('rebind_published'),false);tickBox(root,'I confirm rebinding only the selected widgets to their exact published chart revisions.');await app.publishAction('rebind_published');assert.equal(app.session.revision,2);assert(app.session.definition.report_pages.flatMap(p=>p.widgets).every(w=>w.block.policy==='published'));assert(!f.calls.some(c=>c.name==='reporting_run'));app.close();});
