import {appError,authoringTool,copyData,validID} from './model.js';
import {reportPages,pageContent} from './pages.js';
import {FilterOptionLookup} from './filters.js';
import {filterInputState,renderFilterInput} from './filter-controls.js';
const reportFilterKey=(page,name)=>JSON.stringify([page,name]);
function rfNode(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=String(text);return e;}
function rfButton(title,fn,disabled=false){const b=rfNode('button',title);b.type='button';b.disabled=disabled;b.addEventListener('click',fn);return b;}
function rfText(value){return value?.items?value.items.map(x=>x===''?'Empty text':x).join(', '):value?.date_range?`${value.date_range.start} until ${value.date_range.end_exclusive} (exclusive)`:value?.literal===''?'Empty text':value?.literal??'Use parameter default';}
export class ReportFilterControls{
 constructor(app){this.app=app;this.editor=null;this.lookups=new Map();this.temporary=new Map();this.accepted=null;}
 snapshot(){return JSON.stringify([...this.temporary].sort(([a],[b])=>a.localeCompare(b)));}
 reset(){this.editor=null;this.temporary.clear();this.accepted=null;for(const lookup of this.lookups.values()){lookup.values=[];if(lookup.result)lookup.result={...lookup.result,options:[],next:'',complete:false,values_available:false};}}
 close(){this.reset();for(const value of this.lookups.values())value.close();this.lookups.clear();}
 pageInputs(definition){return reportPages(definition).flatMap(p=>{const filters=(p.filters||[]).filter(f=>this.temporary.has(reportFilterKey(p.id,f.parameter.name))).map(f=>({name:f.parameter.name,value:copyData(this.temporary.get(reportFilterKey(p.id,f.parameter.name)))}));return filters.length?[{page:p.id,filters,overrides:[]}]:[];});}
 current(editor){const a=this.app;return this.editor===editor&&!a.closed&&editor.epoch===a.epoch&&editor.generation===a.pageGeneration;}
 open(filter,page,mode){const a=this.app,content=mode==='default'?pageContent(a.session.definition,page):null,value=mode==='default'?filter.parameter.default:this.temporary.get(reportFilterKey(page,filter.parameter.name))??filter.parameter.default;this.editor={filter:copyData(filter),page,mode,epoch:a.epoch,generation:a.pageGeneration,state:filterInputState(filter.parameter,value),lookup:null};a.render();}
 async search(editor,search,cursor){const a=this.app;if(!this.current(editor)||!a.authoring('report_options','option_status','option_control'))throw appError('forbidden');const published=editor.mode==='run';if(!published&&a.session.dirty)throw appError('conflict');let report,revision,digest;
  if(published){report=a.description?.resource.target.id;revision=a.description?.resource.target.revision;digest=a.description?.definition_digest;}
  else{report=a.session.state?.id;revision=a.session.revision;const view=await a.invoke(authoringTool('read'),{report,revision});if(!this.current(editor))return;if(view.state?.id!==report||view.revision!==revision||view.state.draft_revision!==revision)throw appError('stale_validation');digest=view.digest;}
  if(!validID(report)||!Number.isSafeInteger(revision)||! /^[a-f0-9]{64}$/.test(digest||''))throw appError('stale_validation');
  const target={report:{policy:published?'published':'private_preview',report,revision,digest,page:editor.page,filter:editor.filter.parameter.name}},key=JSON.stringify(target);let lookup=this.lookups.get(key);if(!lookup){if(this.lookups.size>=32)throw appError('limit_exceeded');lookup=new FilterOptionLookup((name,args)=>a.invoke(name,args),target,{locale:a.locale});this.lookups.set(key,lookup);}editor.lookup=lookup;await lookup.search(search,cursor);
 }
 async inspect(editor,action){if(!this.current(editor)||!editor.lookup)throw appError('stale_validation');await editor.lookup.inspect(action);}
 done(editor,value){if(!this.current(editor))return;const a=this.app,name=editor.filter.parameter.name;this.editor=null;if(editor.mode==='default')a.editPage(d=>{if(!d.filters?.some(f=>f.parameter.name===name))throw appError('stale_validation');d.filters.find(f=>f.parameter.name===name).parameter.default=copyData(value);},editor.page);else{this.temporary.set(reportFilterKey(editor.page,name),copyData(value));a.message='Temporary filters changed. Run or preview explicitly to update values.';a.render();}}
 renderEditor(parent){const e=this.editor,a=this.app;if(!e||!this.current(e))return;const search=a.authoring('report_options','option_status','option_control')&&(e.mode==='run'?!!a.description?.definition_digest:!!a.session.state&&!a.session.dirty&&a.session.state.draft_revision===a.session.revision);renderFilterInput(parent,e.state,{label:`${e.filter.label||e.filter.parameter.name} · ${e.mode==='default'?'saved default':'temporary selection'}`,lookup:e.lookup,disabled:a.busy,onSearch:search?(q,c)=>void a.perform(()=>this.search(e,q,c)):undefined,onInspect:e.lookup?action=>void a.perform(()=>this.inspect(e,action)):undefined,onDone:value=>this.done(e,value),onCancel:()=>{if(this.current(e)){this.editor=null;a.render();}}});if(!search&&['dimension_value','dimension_set'].includes(e.state.type))parent.append(rfNode('p','Option search needs a saved current draft binding (or current published report) and a host with governed option-search support.'));}
 renderDefaults(parent,definition){const a=this.app,page=a.activePageID,section=rfNode('details');section.className='filter-editor';section.open=!!this.editor;section.append(rfNode('summary','Business filters'),rfNode('p','Saved defaults and temporary preview selections are separate. Editing never runs a query.'));
  for(const filter of definition.filters||[]){const name=filter.parameter.name,key=reportFilterKey(page,name),card=rfNode('section'),label=rfNode('label','Filter label'),input=rfNode('input');input.value=filter.label;input.maxLength=256;input.setAttribute('aria-label','Filter label');input.addEventListener('change',()=>a.editPage(d=>{d.filters.find(f=>f.parameter.name===name).label=input.value;},page));label.append(input);card.append(label,rfNode('p',`Saved: ${rfText(filter.parameter.default)}`),rfButton('Change saved default',()=>this.open(filter,page,'default'),a.busy),rfButton('Choose temporary preview value',()=>this.open(filter,page,'preview'),a.busy));
   if(this.temporary.has(key))card.append(rfNode('p',`Next preview: ${rfText(this.temporary.get(key))}`),rfButton('Use saved default for preview',()=>{this.temporary.delete(key);a.render();},a.busy));
   for(const widget of definition.widgets||[])for(const binding of widget.bindings||[])if(binding.filter===name)card.append(rfNode('p',`Applies to ${widget.presentation?.title||widget.id}`),rfButton('Remove from '+(widget.presentation?.title||widget.id),()=>a.editPage(d=>{const w=d.widgets.find(w=>w.id===widget.id);w.bindings=w.bindings.filter(b=>b.filter!==name);},page),a.busy));
   card.append(rfButton('Remove filter',()=>{this.editor=null;this.temporary.delete(key);a.editPage(d=>{d.filters=d.filters.filter(f=>f.parameter.name!==name);for(const w of d.widgets)w.bindings=w.bindings?.filter(b=>b.filter!==name);},page);},a.busy));section.append(card);
  }this.renderEditor(section);parent.append(section);
 }
 renderRun(parent){const a=this.app,d=a.description,form=rfNode('fieldset');form.append(rfNode('legend','Run this report'),rfNode('p','A run may query approved sources and creates a new retained result.'));
  for(const f of d.filters||[]){const key=reportFilterKey(f.page,f.parameter.name),row=rfNode('div'),label=f.label||f.parameter.name;row.append(rfNode('p',`${label}: ${this.temporary.has(key)?rfText(this.temporary.get(key)):'Use published default'}`),rfButton('Choose '+label,()=>this.open(f,f.page,'run'),a.busy||!a.capabilities.can_execute));if(this.temporary.has(key))row.append(rfButton('Use published default',()=>{this.temporary.delete(key);a.render();},a.busy));form.append(row);}
  this.renderEditor(form);form.append(rfButton('Run with these filters',()=>void a.perform(()=>a.runPublished()),a.busy||!a.capabilities.can_execute||a.uncertainRun||d.dynamic));if(d.dynamic)form.append(rfNode('p','Dynamic widgets are unavailable in this manual app.'));if(!a.capabilities.can_execute)form.append(rfNode('p','Current access permits retained reads only.'));parent.append(form);
 }
 publishedInputs(){const pages=new Map();for(const f of this.app.description?.filters||[]){const value=this.temporary.get(reportFilterKey(f.page,f.parameter.name));if(value===undefined)continue;if(!pages.has(f.page))pages.set(f.page,[]);pages.get(f.page).push({name:f.parameter.name,value:copyData(value)});}return Array.from(pages,([page,filters])=>({page,filters,overrides:[]}));}
}
