import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import * as presentation from './presentation.js';
import * as viewer from './app.js';
test('viewer exports the exact shared presentation functions',()=>{for(const name of ['boundedJSON','exact','renderChart','amountDisclosureLines','validateRetainedView','renderRetainedOutput'])assert.equal(viewer[name],presentation[name]);});
test('presentation imports do not initialize a host or register browser listeners',async()=>{const source=await readFile(new URL('./presentation.js',import.meta.url),'utf8');for(const absent of ['class Bridge','class Viewer','postMessage(','window.addEventListener(','document.addEventListener(','getElementById(','ui/initialize','tools/call'])assert.equal(source.includes(absent),false,absent);const context=vm.createContext({get document(){throw Error('presentation accessed DOM while loading');},get window(){throw Error('presentation accessed host while loading');}});new vm.Script(source.replaceAll('export ','')).runInContext(context);});
test('self-contained viewer compilation keeps the bridge and one presentation implementation',async()=>{const common=await readFile(new URL('./presentation.js',import.meta.url),'utf8'),host=await readFile(new URL('./app.js',import.meta.url),'utf8'),names='VERSION, KINDS, boundedJSON, exact, renderChart, amountDisclosureLines, validateRetainedView, renderRetainedOutput, viewerInternals';const script=`const {${names}}=(()=>{\n${common.replaceAll('export ','')}\nreturn {${names}};\n})();\n`+host.split('\n').filter(line=>!line.startsWith('import ')&&!line.startsWith('export {')).map(line=>line.replaceAll('export ','')+'\n').join('');new vm.Script(script).runInNewContext({});for(const name of ['class Bridge','class Viewer','function renderRetainedOutput','function renderChart'])assert.equal(script.split(name).length-1,1);assert.equal(script.includes('ui/initialize'),true);assert.equal(script.includes('import '),false);});
