from pathlib import Path

def update(path,old,new):
 p=Path(path);text=p.read_text();assert old in text,(path,old);p.write_text(text.replace(old,new))
update('README.md','Status: implementation planning. This repository does not yet claim a working Go service or completed source migration.','Status: the Go foundation and verified operational authority (phases 01–04) are implemented with real PostgreSQL acceptance tests. Analytics/reporting implementation and full source migration remain in the subsequent phases.')
update('README.md','Business JWT enforcement, analytics and reporting remain later phases.','JWT verification and signed-scope enforcement now protect the operational consumer; analytics and reporting remain later phases.')
update('GETTING-STARTED.md','# Running the phase 01–02 foundation','# Running the phase 01–04 verified foundation')
update('GETTING-STARTED.md','This build implements configuration, lifecycle/health and the PostgreSQL metadata foundation. It does **not** implement authentication, NLQ, reporting, MCP, rendering or Bifrost inference yet. Those remain separate numbered phases. Pengui is still the sole authority issuer; this build exposes no business endpoint and creates no local credentials.','This build implements configuration, lifecycle/health, PostgreSQL metadata, Pengui JWT verification and signed-scope enforcement on its operational APIs. It does **not** implement NLQ, reporting, the full MCP server, rendering or Bifrost inference yet. Pengui remains the sole authority issuer; Chartworks creates no credentials or local identity policy.')
update('GETTING-STARTED.md','broad listeners are deliberately unavailable until the JWT enforcement phases.','broad listeners and external TLS deployment remain with the wider transport phase. JWT verification is active on every registered operational endpoint.')
update('GETTING-STARTED.md','The key probe confirms structurally usable public keys, **not** JWT authentication: phase 03 will connect its verifier/cache to this health seam.','The real JWT verifier and readiness use the same bounded trusted public-key cache; a readiness result does not authorize an individual request.')
update('GETTING-STARTED.md','`/metrics` and all `/v1/*` paths return 404. The real Prometheus exporter is an in-process interface with conformance tests; a protected metrics endpoint is left to the authenticated API phase.','Operational `/v1/*` and `/metrics` requests now require a valid Pengui bearer plus their separately registered action and addressed reach. Anonymous requests return 401; a valid caller receives a nondisclosing 404 for unregistered/inaccessible resources. Metrics also needs `ops.metrics` and returns 404 when disabled. Use the operation manifest below; there is no local login or default administrator token.')
update('GETTING-STARTED.md','python3 scripts/run_phase_acceptance.py --phase 02\n','python3 scripts/run_phase_acceptance.py --phase 02\npython3 scripts/run_phase_acceptance.py --phase 03\npython3 scripts/run_phase_acceptance.py --phase 04\n')
update('GETTING-STARTED.md','The other 32 phases remain unimplemented','The other 30 phases remain unimplemented')
update('GETTING-STARTED.md','This does not block acceptance of phases 01–02.','This does not block acceptance of the implemented phases 01–04.')
update('GETTING-STARTED.md','It is **not** publicly callable before Pengui JWT enforcement.','The bounded synchronous sweep is now reachable only through the registered Pengui-JWT-protected operational service; unattended scheduling is not implemented here.')
# Prevent planned-template prose from contradicting the implemented status.
for phase in ('03','04'):
 p=next(Path('docs/plans').glob('phase-'+phase+'-*.md'));text=p.read_text().replace('No runtime completion is claimed.','Runtime acceptance and integration boundaries are recorded below.').replace('No runtime completion/deviation is claimed; record implementation findings and equivalent behavior here before closure.','Implementation evidence and deliberate boundaries are recorded below.');p.write_text(text)
# Keep new configuration rows within one Markdown table.
p=Path('docs/configuration.md');text=p.read_text();text=text.replace('limit. |\n\n| `auth.max_token_bytes`','limit. |\n| `auth.max_token_bytes`');p.write_text(text)
