from pathlib import Path
import json

p=Path('test/acceptance/phase03_test.go');s=p.read_text().replace('"path/filepath"','"io/fs"')
s=s.replace('for _, root := range []string{"../../internal", "../../cmd", "../../sdk"} {','repo,err:=os.OpenRoot("../..");if err!=nil{t.Fatal(err)};defer func(){_ = repo.Close()}()\n for _, root := range []string{"internal", "cmd", "sdk"} {')
s=s.replace('filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {','fs.WalkDir(repo.FS(),root, func(path string, d fs.DirEntry, err error) error {')
s=s.replace('// #nosec G304 -- repository source files discovered under fixed test-owned roots, never user paths.\n\t\t\t\tb, err := os.ReadFile(path)','b, err := repo.ReadFile(path)')
p.write_text(s)
p=Path('internal/auth/keys.go');s=p.read_text().replace('c := http.Client{Transport: http.DefaultTransport.(*http.Transport).Clone()}','transport:=http.DefaultTransport\nif base,ok:=transport.(*http.Transport);ok{copyTransport:=base.Clone();copyTransport.MaxResponseHeaderBytes=64<<10;transport=copyTransport}\nc := http.Client{Transport:transport}');p.write_text(s)
p=Path('internal/foundation/server.go');s=p.read_text().replace('// Handler exposes no metrics, configuration values, authority bypass, or business endpoints.','// Handler serves public content-free health and delegates operational routes to the verifier/enforcer.');p.write_text(s)
p=Path('docs/configuration.md');s=p.read_text().replace('# Implemented foundation configuration','# Implemented configuration and authority').replace('The full application/provider APIs remain in later phases.','Operational APIs now require verified Pengui authority; analytics and full MCP transports remain in their owning phases.')
s=s.replace('| `auth.audience` | string or env reference | required | Nonempty, at most 512 bytes; no spaces/control separators. Exact intended audience is reserved for phase 03 enforcement. |','| `auth.audience` | string or env reference | required unless using pair | Explicit same-audience shorthand for both surfaces, at most 512 bytes. Cannot be combined with nonempty `auth.audiences`. |\n| `auth.audiences.http` / `.mcp` | strings or env references | required together when shorthand absent | Exact per-surface intended audiences, at most 512 bytes each. Distinct values deny cross-surface replay. |')
s=s.replace('0–1 minute; validated/reserved for the phase 03 verifier, not used to extend the health probe\'s key freshness.','0–1 minute; applies to registered token-time validation and envelope deadline, never to JWKS freshness.')
s=s.replace('Positive, at most 24 hours; validated/reserved for phase 03. No token is accepted by this foundation.','1 second–24 hours; integer `exp - iat` must be positive and within the limit.')
needle='The key-health probe rejects duplicate IDs/fields, symmetric/private key material, invalid public coordinates/moduli and incompatible declared algorithms. It does not authenticate requests. Phase 03 must consume the same health seam with its real verifier/cache, not mistake the probe for JWT verification or add a local issuer.'
replacement='''| `auth.max_token_bytes` | integer bytes | 32768 | 1024–65536; entire compact token bound before decoding. |
| `auth.max_claim_bytes` | integer bytes | 24576 | 512–token bound; decoded claims. JOSE header is separately capped at 2048 bytes. |
| `auth.max_scopes` | integer count | 32 | 1–32, matching the actual Pengui provider-minter maximum. |
| `auth.max_scope_bytes` | integer bytes | 4096 | 1–4096 summed scope-string bytes; each scope also has a fixed 256-byte ceiling. |

The real verifier and readiness share one bounded public-key cache. It rejects duplicate IDs/fields, symmetric/private material, invalid coordinates/moduli and key/algorithm mismatch; fetch failure does not extend last-success freshness. Rotation is single-flight and interval-bounded, including unknown-kid traffic. JSON nulls, duplicate claims, alternate authority representations and token-selected URLs are denied. Only the actual `tenant/user/session/scopes` issuer representation is accepted. See [provider registration](contracts/pengui-provider-registration.md).'''
assert needle in s;s=s.replace(needle,replacement)
s=s.replace('The exporter is not mounted on the public/health router.','`/metrics` is protected by explicit Pengui-issued `ops.metrics` and tenant read reach; false returns 404 even to a permitted operator.')
old='`/capabilities` reports implemented foundation functionality and explicitly says business API and authentication are unavailable. It never returns provider credentials, source IDs or deployment DSNs. `/metrics`, `/mcp`, `/v1/*`, login and bootstrap paths are absent. Later authenticated API registration owns protected metric/audit access.'
new='`/capabilities` reports verified authentication, signed-scope enforcement and operational APIs as implemented, with analytical business APIs still unavailable. It never returns tokens, source IDs or DSNs. Health is public; the [registered operational routes](contracts/chartworks-operations.json) require Pengui-issued authority. No login/bootstrap/token/grants/principals routes exist. The optional metrics switch cannot disable authentication.'
assert old in s;s=s.replace(old,new);p.write_text(s)
# Close only phases with their real named runtime acceptance already exercised.
p=Path('docs/plans/phase-registry.json');d=json.loads(p.read_text())
for n in ('03','04'):
 d['phases'][n]['status']='shipped'
 phase=next(Path('docs/plans').glob('phase-'+n+'-*.md'));text=phase.read_text().replace('Status: in_progress.','Status: shipped.')
 text+='\n## Implementation record — 2026-09-05\n\nThe six named acceptance criteria have real Go assertions and first consumers. See [provider handoff](../contracts/pengui-provider-registration.md) and [adversarial review](../reviews/phase-03-04-adversarial.md). No production platform credential or deployed session was used; issuer-shaped synthetic signing fixtures feed the actual verifier and PostgreSQL API/SDK consumer. No local policy database or issuer was added.\n'
 if n=='03':text+='\n`internal/auth` now owns the key cache shared with readiness, bounded JWT decoder and golang-jwt cryptographic verification. HTTP and MCP intended audiences are exact; the full MCP transport stays phase22. Token scope limits match the actual provider minter: 32 / 256 bytes each / 4096 bytes total.\n'
 else:text+='\n`internal/access` supplies Require/Constrain and execution/artifact partition gates; `internal/securityapi` applies them before the existing real metadata/maintenance consumer and again in-process. All six protected routes have SDK coverage and a checked operation manifest. Reporting/source domains must still supply complete server-resolved dependency manifests in their owning phases; no unimplemented reporting API is advertised.\n'
 phase.write_text(text)
p.write_text(json.dumps(d,indent=2)+'\n')
# Keep current operational entry points visible without rewriting historical verification records.
for name in ('README.md','GETTING-STARTED.md'):
 p=Path(name);text=p.read_text();text+='\n## Verified operational access (phases 03/04)\n\nThe production `serve` command now protects retention policy, audit, synchronous retention sweep, diagnostics and metrics with Pengui JWTs and signed addressed scopes. The old health-only foundation boundary is superseded for these implemented operations, not for the later analytical/MCP features. The listener remains explicit-loopback; a trusted backend supplies credentials. See [operator registration](docs/contracts/pengui-provider-registration.md), [operation manifest](docs/contracts/chartworks-operations.json) and [authority contract](docs/contracts/pengui-authority.md). The public Go client is `sdk/chartworks`; its caller supplies a current Pengui token provider. Chartworks issues no credentials.\n';p.write_text(text)
p=Path('CHANGELOG.md');s=p.read_text();pos=s.find('\n');s=s[:pos+1]+'\n## Unreleased — verified authority foundation\n\nPengui JWT verification, exact signed resource/action enforcement, current-envelope query constraints, protected real operational consumers and public SDK parity. Shared bounded JWKS rotation/freshness, issuer-shaped fixtures, adversarial tests and compiled JWT-to-PostgreSQL lifecycle coverage. No new IAM tables or local issuer.\n'+s[pos+1:];p.write_text(s)
# Mirror ownership remains unchanged; explicitly point both rule files at the implemented handoff.
for name in ('AGENTS.md','CLAUDE.md'):
 p=Path(name);s=p.read_text();s+='\n## Implemented authority baseline\n\nD-059–D-061 and docs/contracts/pengui-provider-registration.md pin the consumed Pengui bearer format and actual operational scope registry. The only production envelope constructor caller is the verifier; raw store coordinates are never authentication. Keep issuer limits, exact audience policy, shared cache freshness, expiry-bound selections and service-level enforcement intact when adding consumers. No production signing/renewal/local-policy path is authorized.\n';p.write_text(s)
# RFC points to accepted implementation detail without changing future domain coverage.
p=Path('RFC-001-Chartworks.md');s=p.read_text();s+='\n## Phase 03/04 authority implementation\n\nD-059–D-061 implement the existing Pengui provider-scope seam with one JWT verifier/cache and immutable signed envelope. [The operator handoff](docs/contracts/pengui-provider-registration.md) and [actual operation manifest](docs/contracts/chartworks-operations.json) describe the implemented consumer. Scope limits are 32 entries, 256 bytes each, 4096 total; exact HTTP/MCP audiences may be configured separately. Synchronous operational routes and SDK clients are present, but no local issuer, grants database, reporting API or full MCP transport is added by this milestone.\n';p.write_text(s)
